### ISSUE TITLE
[1.10.2][1.0.5 beta]

### ISSUE THREAD

**Issue by savosdarkran** [MJRLegends/Space-Astronomy-2-Feedback-#1]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes
### Description of Issue
After a random period of time, I get block lag.  I ran /forge tps and mean tick time is over 100

### Steps to Reproduce Issue
Randomly hit block
Wait
Randomly  hit block

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
fml-client-latest.log -> http://paste.ubuntu.com/24921958/
latest.log -> http://paste.ubuntu.com/24921977/

**Version of Mod Pack using:** [VERSION] 1.0.5 beta

### Additional Information
I see in the console [22:49:45] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 13919ms behind, skipping 278 tick(s)

**Comment by MJRLegends** [comment]
How much ram do you have assigned?

**Comment by MJRLegends** [comment]
and what CPU and GPU do you have?

**Comment by savosdarkran** [comment]
6Giggers, 4790K, 32GB Total, GTX 1080

**Comment by MJRLegends** [comment]
See i dont get these issues on my side :(

**Comment by savosdarkran** [comment]
:(

**Comment by MJRLegends** [comment]
i will do some testing, there will be a update tomorrow anyways

**Comment by MJRLegends** [comment]
its due to biomes o plenty. i might release a version in a min without the mod

**Comment by savosdarkran** [comment]
Do you have a community on twitch/discord for your packs?

**Comment by MJRLegends** [comment]
@savosdarkran how long were you in the world for before you left and posted this?

**Comment by savosdarkran** [comment]
Well the log that I posted I was in for about five minutes, but the first time I noticed it (before I restarted my PC "just in case") it was about 15 minutes.

**Comment by MJRLegends** [comment]
I will speak to the mod devs i need to speak to tomorrow

**Comment by savosdarkran** [comment]
Sweet :D  I will continue to test.

**Comment by MJRLegends** [comment]
@savosdarkran Do you see tps lag or just the /forge tps command showing low tps?

**Comment by savosdarkran** [comment]
Both.  If it makes a difference I was in a new biome that I've never seen before with BOP.  I can't remember the name, but some of the terrain had WIP on them.

**Comment by MJRLegends** [comment]
Ok thanks im working on improving stuff :D

**Comment by MJRLegends** [comment]
Im going to close this since it will approve as updates happen :D

**Comment by savosdarkran** [comment]
I still have this issue when launching from the Twitch App but not MultiMC.

**Comment by MJRLegends** [comment]
Whats the issue

**Comment by savosdarkran** [comment]
TPS lag.

**Comment by savosdarkran** [comment]
TPS lag :)

**Comment by MJRLegends** [comment]
Dont put the same message twice its spammy and just use multi mc then. I dont make the curse launcher so this isnt anything i can change for you haha if not contact curse support

**Comment by savosdarkran** [comment]
Sorry about the duplicate message.  I'll leave you be.
