### ISSUE TITLE
Unable to craft the Alumium Nugget from rockhounding mod chemistry

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-2-Feedback-#10]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

Unable to craft the Alumium Nugget from rockhounding mod chemistry or from any other Alumium to nugget

### Steps to Reproduce Issue
1. There is no recipe in JEI, and is need for some other stuff in rockhounding mod chemistry
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** 1.0.8 beta

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Will be fixed in 1.0.9 Beta

**Comment by MJRLegends** [comment]
This isnt a bug since theres another Alumium Nugget, it just means the rockhounding mod chemistry Alumium Nugget needs to be hidden from JEI
