### ISSUE TITLE
Twitch unable to install modpack

### ISSUE THREAD

**Issue by Drayes** [MJRLegends/Space-Astronomy-2-Feedback-#100]
### Description of Issue
when i attempt to install space astronamy 2 threw twitch, it fails.

**Comment by MJRLegends** [comment]
Please make sure to look at closed issues theres already 10000 of these, i cant do anything i make the mod pack not the launcher, its a launcher issue they are working on it

**Comment by MJRLegends** [comment]
@Drayes The Twitch App mod pack install/update issues have been solved, You just need to switch to be using the Beta Version and then install or update the mod pack/s. This is how you change your launcher to the Beta Version: http://imgur.com/a/un33N
