### ISSUE TITLE
Geiger Counter from ExtraPlanet not craftebel

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-2-Feedback-#102]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Geiger Counter from ExtraPlanet not craftebel

### Steps to Reproduce Issue
1. Check JEI, find no recipe, but can be spawned in by cheating

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [1.2.7]

**Where did this bug happen:** Single Player

### Additional Information
Not sure if you have implemented, a crafting recipe

**Comment by MJRLegends** [comment]
Not fully implement yet

**Comment by MJRLegends** [comment]
I've implemented it fully for v1.2.8
