### ISSUE TITLE
Sleeping reduced radiation from 76% to 0

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-2-Feedback-#103]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
When after sleeping in  bed in the overworld, it reduced my radiation from 76% to 0

### Steps to Reproduce Issue
1. Sleep in a bed

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 
![2017-08-31_09 51 39](https://user-images.githubusercontent.com/20618588/29912585-6f5b8e16-8e32-11e7-85e1-a024ea522ac1.png)

**Version of Mod Pack using:** [1.2.7]

**Where did this bug happen:** [Single Player]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Fixed it was a #blame java moment
