### ISSUE TITLE
Open Modular Turrets deal no damage

### ISSUE THREAD

**Issue by kickrazz** [MJRLegends/Space-Astronomy-2-Feedback-#104]
### Description of Issue
Open Modular turrets. All turrets except the laser turret deals no damage.

### Steps to Reproduce Issue
1. Place any turret base with a turret on top.
2. Add ammo and power to the turret base.
3. Watch the turret attack neutral/aggressive mobs and deal no damage.

### Logs
Added a log
[log.txt](https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/files/1268524/log.txt)

**Version of Mod Pack using:**
1.2.6
issue still persists after updating to 1.2.8

**Where did this bug happen:** 
Tested on both multiplayer and singleplayer with the same results

### Additional Information
I think it has something to do with the damage type.
Java version 1.80_25 - 64bit

**Comment by MJRLegends** [comment]
Ok so i've just tested this with the latest version, and im not getting the issue 
see https://gyazo.com/e6334efab236c052582f6d8922213269

**Comment by kickrazz** [comment]
After reinstalling the pack the issue no longer occurred. all turrets work as they should.

**Comment by MJRLegends** [comment]
No problem
