### ISSUE TITLE
Unknown crash, unknown cause

### ISSUE THREAD

**Issue by Drayes** [MJRLegends/Space-Astronomy-2-Feedback-#105]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
Give self speed upgrade(s) 
place in fluid retrevial node

**Crash log/Log (if applicable):** https://pastebin.com/X3g6EayF

**Version of Mod Pack using:** 1.2.5

**Where did this bug happen:** Single Player

### Additional Information
i used NEI to spawn in 4 speed upgrades from extra utilities and attempted to place them in a retrevial node.

**Comment by MJRLegends** [comment]
Update to latest theres no reason you should be using 3 versions back
