### ISSUE TITLE
Endermen do not drop skulls with TiC beheading.

### ISSUE THREAD

**Issue by Croxalicious** [MJRLegends/Space-Astronomy-2-Feedback-#106]
Description of Issue
Endermen don't seem to drop heads when killed.

Steps to Reproduce Issue
1. Apply 100% beheading to TiC Cleaver in creative.
2. Kill Enderman.

Version of Mod Pack using: 1.2.7

Where did this bug happen: Single Player

Additional Information
Is this intentional? Being unable to make most high-end Ender IO things doesn't seem like a good idea.

**Comment by MJRLegends** [comment]
Yeah its intentional but the recipes need any head so skeletons will work
