### ISSUE TITLE
Lab Blender using too many resources

### ISSUE THREAD

**Issue by Hazmatik** [MJRLegends/Space-Astronomy-2-Feedback-#107]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
If you fill up more than one slot in the Lab Blender from Rockhounding Chemistry it uses the amount the recipe calls for from each slot but only gives the result for one.

### Steps to Reproduce Issue
1. Place Lab Blender and insert fuel
2. Place a stack of any items used in recipes in the lab blender (sulfur, salt, or coal are easy to test with)
3. Turn on the machine and watch resources pulled from each slot but only the result for one recipe shows in the output slot.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 
Here the recipe calls for 3 coal to make 2 Crack Coal Compost and you can see it takes 3 from each stack for a total of 6 coal but only gives 2 Crack Coal Compost as a result.
[![https://gyazo.com/c15f5d69110436ad733b3d3664e356bc](https://i.gyazo.com/c15f5d69110436ad733b3d3664e356bc.gif)](https://gyazo.com/c15f5d69110436ad733b3d3664e356bc)
**Version of Mod Pack using:** [VERSION]
1.2.7
**Where did this bug happen:** [Single Player or Server]
FrozenSoul server node 1
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Reported here https://github.com/GlobbyPotato/Rockhounding_Chemistry/issues/14

**Comment by MJRLegends** [comment]
Will be fixed in v1.3.0 that will be out next week as it wasnt able to make the v1.2.9 version due to curse issues which have now been fixed :D
