### ISSUE TITLE
Game crashing on load up

### ISSUE THREAD

**Issue by Issacozzman** [MJRLegends/Space-Astronomy-2-Feedback-#109]
The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.RuntimeException: net.minecraft.client.renderer.StitcherException: Unable to fit: advanced_solar_panels:models/particles - size: 256x256 - Maybe try a lowerresolution resourcepack?### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes 

### Steps to Reproduce Issue
trying to mod mod pack

**Crash log/Log (if applicable):**  https://pastebin.com/sn4t2Fgq

**Screenshots (if applicable):**  none 

**Version of Mod Pack using:** 1.2.8

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
This isnt a mod pack thing, you need to change back the resolution stuff in the twitch settings

**Comment by MJRLegends** [comment]
see #55
