### ISSUE TITLE
animatons bug

### ISSUE THREAD

**Issue by JaTuTylkoSpie** [MJRLegends/Space-Astronomy-2-Feedback-#110]
### ---Issue Report---
a new issue (probably)
### Description of Issue
hands and camera are rapidly shaking
### Steps to Reproduce Issue
probably inreproducable
**Crash log/Log :**
i can't find it for now
**Screenshots :** 
video is this scenario better link bellow
**Version of Mod Pack using:** 
v1.20
**Where did this bug happen:** 
singleplayer
### Additional Information
hands are shaking only on F5 and in inventory
camera is shaking only while i'm moving on ground
all mobs (floathing only don't do that) are also doing this
link: https://drive.google.com/file/d/0B7kWohg_z7RkODhGaVdYbnFhc2M/view?usp=sharing
lag spike are caused by this bug

**Comment by MJRLegends** [comment]
You need to update to v1.2.8 of the pack being 8 version behind isn't a good idea

**Comment by JaTuTylkoSpie** [comment]
Well that was fast.

**Comment by JaTuTylkoSpie** [comment]
ok now i can't do any thing with this modpack only play with 3 mods but this is launcher bug.
