### ISSUE TITLE
Client Crash using iChisel, Glass to Quite Clear Glass

### ISSUE THREAD

**Issue by JiFMike** [MJRLegends/Space-Astronomy-2-Feedback-#111]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
Twice now I have used the iChisel to change Minecraft Glass to Ender IO Quite Clear Glass and the game has crashed to desktop. My server is not impacted.

### Steps to Reproduce Issue
1. Grab some glass and use the iChisel
2. Select glass, and then select quite clear glass in the menu
3. Hit the chisel button, game crashes
4. Upon reloading client and logging in, glass is chiseled as expected.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/4hJzbiFZ

**Screenshots (if applicable):** 

**Version of Mod Pack using:**
 v1.2.8

**Where did this bug happen:** 
Server (mine)

### Additional Information
None that I can think of, but I will give you any info you request.

**Comment by mlard811** [comment]
Just updated to v1.2.9, same thing happens.

**Comment by MJRLegends** [comment]
It seems its already reported here https://github.com/Chisel-Team/Chisel/issues/514 and has been fixed so hopefully it will be released in a version soon
