### ISSUE TITLE
Invalid Egg found in the Pam's HarvestCraft Market

### ISSUE THREAD

**Issue by Emax220x** [MJRLegends/Space-Astronomy-2-Feedback-#113]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]
Can't use the Ghast's egg from Pam's HarvestCraft
### Steps to Reproduce Issue
1. [First step]
Buy the egg from the Market
2. [Second step]
Try to spawn the Ghast
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]
1.2.8
**Where did this bug happen:** [Single Player or Server]
Single Player
### Additional Information
[Any other information that may be able to help me with the problem]
I don't know if this is intended or not, but the egg's id is just "Spawn"

**Comment by MJRLegends** [comment]
Its not a Ghast Egg its just a egg without a mob/animal, Its ment to be a Llama egg i think which dont exist in mc 1.10.2. So its intended but i will hidden that from the market
