### ISSUE TITLE
Nether quartz block in a LightningCraft "Lightning Crusher" crashes the game.

### ISSUE THREAD

**Issue by Bongohmu** [MJRLegends/Space-Astronomy-2-Feedback-#116]
### ---Issue Report---
**I checked and no one has reported this**

### Description of Issue
When you place a Nether Quartz block in a LightningCraft "Lightning Crusher," it crashes the game.

### Steps to Reproduce Issue
1. Make a LightningCraft "Lightning Crusher"
2. Place a block of Nether Quartz inside

**I don't have the crash log**

**No screenshots** 

**Version of Mod Pack using:** [V1.2.9]

**Where did this bug happen:** [Server]

### Additional Information
none

**Comment by MJRLegends** [comment]
Im going to need the crash log please, as im unable to look at a crash issue without the main thing.

**Comment by Bongohmu** [comment]
Let me replicate crash, hold up.

**Comment by Bongohmu** [comment]
It doesn't crash in single player. That's odd.

**Comment by MJRLegends** [comment]
which server are you on?

**Comment by Bongohmu** [comment]
A private server. The host was out to dinner, so I need to wait until he comes back.

**Comment by Bongohmu** [comment]
When I get new info I will be sure to post it.

**Comment by MJRLegends** [comment]
Ok im going to close this for the time being since its not a issue on single player so 9/10 out of ten either a sponge issue or a server/plugin caused issue

**Comment by Bongohmu** [comment]
We didn't add anything though. I figured it was all the same mods. Also, this is just an opinion but, I feel that you should be able to turn quartz block back into nether quarts w/ LC because you can w/ other mods; for example IC2.

**Comment by Bongohmu** [comment]
well that was worded poorly

**Comment by MJRLegends** [comment]
if it works in single player then it should work on a pure forge server with no edits or plugins or sponge, so sorry but i dont think i can do anything

**Comment by Bongohmu** [comment]
It's not really a problem for me I can just get over it, I was just wanting someone to be aware that this is something that happens. When the server owner come back I'll we what update of forge we have. Also if it was a plugin, I would have to have that also installed to my client to play on the server, in turn crashing in single player as well. So we exclude plugins being an issue.
