### ISSUE TITLE
Audio Manager crashing Minecraft

### ISSUE THREAD

**Issue by Yurameki** [MJRLegends/Space-Astronomy-2-Feedback-#118]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Audio manager seems to keep crashing and restarting and then crashes Minecraft randomly.

### Steps to Reproduce Issue
1. Play for awhile
2. Watch audio manager tell you it crashed
3. Restarts itself, crashes again
4. Eventually Minecraft crashes entirely

**Crash log/Log (if applicable):** [PASTEBIN. https://pastebin.com/vh5vKF6u]

**Version of Mod Pack using:** [1.2.9]

**Where did this bug happen:** [Single Player]

**Comment by MJRLegends** [comment]
Please remove TickProfiler and try again, as i see just before you got the crash, TickProfiler stuff was being run..

**Comment by MJRLegends** [comment]
Yeah and it seems your not assigning enough ram, im going to call this down to this and my above point

**Comment by MJRLegends** [comment]
Will reopen if anyone else gets this issue :D

**Comment by Yurameki** [comment]
It was happening without TickProfiler, I threw that in there to see if I could find if the occassional hangups I'm getting are from the audio manager crashing or entities.

Also how is 4 GB not enough RAM exactly?

**Comment by MJRLegends** [comment]
5GB-6GB is the requirement that i've set anything below that is not supported as i know issues will happen

**Comment by MJRLegends** [comment]
Also does it only happen when IC2 machines are near by/making a sound

**Comment by Yurameki** [comment]
Guess I missed that note somewhere. I'll try again later with more RAM.

And no, it doesn't only happen with IC2 machines around. It was happening before I built any IC2 things originally.

**Comment by MJRLegends** [comment]
Please repost a log/crash log here with that RAM change and Tick profiler removed and then i will see where we are at

**Comment by Yurameki** [comment]
Not sure if it's the upgrade that fixed it, but the stutter and crash appear to both be gone after some light testing. I'll let you know if anything changes in the future on this. Thanks!
