### ISSUE TITLE
Bucket do not get consumed when turning infected water to clean water

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-2-Feedback-#119]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes 
### Description of Issue
Bucket do not get consumed when turning infected water to clean water, and make it a dupe bug

### Steps to Reproduce Issue
1. Use crafting grid 

 
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 
![2017-09-15_12 43 49](https://user-images.githubusercontent.com/20618588/30479045-b4116f84-9a13-11e7-8914-7775b47c7697.png)

**Version of Mod Pack using:** [1.3.0]

**Where did this bug happen:** [Single Player]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
This isnt a bug it was intended

**Comment by Jin16** [comment]
it give you a Empty bucket and a bucket of clean water

**Comment by MJRLegends** [comment]
Yeah intended use
