### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by DecepticusPrime** [MJRLegends/Space-Astronomy-2-Feedback-#12]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue

Sudden stop of launch, before the Mojang screen is even  #reached

### Steps to Reproduce Issue
1. Pres play
2. Wait a few seconds, then play again

**Crash log/Log (if applicable):** 
[fnT30JuW-2.txt](https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/files/1103506/fnT30JuW-2.txt)

**Version of Mod Pack using:** [v1.0.8 beta]

### Additional Information

Running on Mac OS El Capitan 10.11.6, 3 GB RAM assigned (read somewhere that assigning more RAM may fix it)

**Comment by MJRLegends** [comment]
You need Java 8 to run the pack

**Comment by DecepticusPrime** [comment]
Cheers, sorry for wasting your time!

**Comment by MJRLegends** [comment]
No problem :D
