### ISSUE TITLE
Large TPS drop with Colossal Chest and RS External Storage

### ISSUE THREAD

**Issue by mlard811** [MJRLegends/Space-Astronomy-2-Feedback-#120]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes

### Description of Issue
Built an 11x11x11 Colossal Obsidian Chest, added an RS external storage onto the core and my server TPS went from 19, to 7. Removed the external storage and it went back up to 19, replaced and down to 7 again.

### Steps to Reproduce Issue
See description

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
N/A

**Screenshots (if applicable):** 
Before placing external storage
https://i.imgur.com/DK3vrzl.png

After placement on chest core
https://i.imgur.com/dMEnd71.png

**Version of Mod Pack using:**
v1.3.0

**Where did this bug happen:**
Server

### Additional Information
TPS drop happens over a couple seconds. I have found tickets related to this on RS github and the conclusion is not good from what I've read. I doubt you can do anything about this, but I figured I would report it. Below is a list of relevant issues, but no solutions. The blame is placed on the CyclopsCore mod. I'm still digging for info, but figured I would report it.

https://github.com/raoulvdberge/refinedstorage/issues/1239
https://github.com/raoulvdberge/refinedstorage/issues/325

**Comment by MJRLegends** [comment]
Thanks for the bug report, Nothing can be done with this sorry

**Comment by MJRLegends** [comment]
This has been added to the known issues #99 :D
