### ISSUE TITLE
[Question] Was the sound effects mod removed? How to enable dynamic FOV?

### ISSUE THREAD

**Issue by joserobjr** [MJRLegends/Space-Astronomy-2-Feedback-#122]
I updated from 1.2.4 (I think) to 1.3.0 and I can't hear the waterfall, crafting, environment sounds anymore. Was the mod removed?

An other question, how do I re-enable the dynamic FOV (sprint camera effect)?

**Comment by MJRLegends** [comment]
You can find the change log here https://pastebin.com/sT3e0wLd
