### ISSUE TITLE
Tinker's picks not breaking Mars stone

### ISSUE THREAD

**Issue by miahash123** [MJRLegends/Space-Astronomy-2-Feedback-#123]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]
I am unable to break Mars stone variants with a Tinker's pick, I have tested it on other planets and with different picks and they all seem to work fine, just Mars and tinkers.
### Steps to Reproduce Issue
1. [First step]
2. [Second step]
Grab a tinker's pick and try to break Mars stone blocks
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 
![2017-09-16_16 49 59](https://user-images.githubusercontent.com/32024063/30516252-4555d732-9aff-11e7-841a-ea6abe3e5488.png)

**Version of Mod Pack using:** [VERSION]
1.3.0
**Where did this bug happen:** [Single Player or Server]
Single Player
### Additional Information
[Any other information that may be able to help me with the problem]
The screen shot shows me trying to break the stone with no progression and a non-broken pick, hammer doesn't work either

**Comment by MJRLegends** [comment]
Which tinkers pick you using, like what is it made out of

**Comment by miahash123** [comment]
Cobalt, but i tried several others to no avail including manyllyn, and as a side note ores were fine just not that

**Comment by miahash123** [comment]
also I'm pretty sure it was working before the update

**Comment by MJRLegends** [comment]
Yeah its intended the Galacticraft pickaxes will work for it a few others
