### ISSUE TITLE
Conduit Probe crafting issue

### ISSUE THREAD

**Issue by KepQwet** [MJRLegends/Space-Astronomy-2-Feedback-#124]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**
Yes

### Description of Issue
Crafting recipe for conduit probe not working with refined storage silicon.

### Steps to Reproduce Issue
1. Try to craft the conduit probe item with silicon from the refined storage mod
2. Cry because it won't let you

**Crash log/Log (if applicable):**
N/A

**Screenshots (if applicable):** 
N/A

**Version of Mod Pack using:** [VERSION]
1.2.7

**Where did this bug happen:**
Server (FrozenSoul SA2-1)

### Additional Information

**Comment by MJRLegends** [comment]
@KepQwet Please retest with v1.3.0 of the pack

**Comment by KepQwet** [comment]
Tested in 1.3.0. Still not working @MJRLegends

**Comment by MJRLegends** [comment]
@KepQwet Works for me 
![](https://i.gyazo.com/cd09545f0defa3b6913e7c5eef0ee562.png)
![](https://i.gyazo.com/cf11cd51f0cd81972e2c611101f0e2d9.png)
