### ISSUE TITLE
Graphite dust

### ISSUE THREAD

**Issue by SilkMars187** [MJRLegends/Space-Astronomy-2-Feedback-#125]
### Description of Issue
The issue is not major but when you have Graphite dust in your inv and drag and drop to throw it out it throws it out but its still in your inv so you keep doing it and you look down and there is a bunch of graphite dust i started with 4 now i have over 4 stacks 

**Version of Mod Pack using:** [VERSION]
1.2.7

**Where did this bug happen:**
server 2

**Comment by MJRLegends** [comment]
This is a server thing not a pack thing
