### ISSUE TITLE
ContainerThermalEvaporationController Crash

### ISSUE THREAD

**Issue by onehappyballoon** [MJRLegends/Space-Astronomy-2-Feedback-#126]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
[Description of the issue]
Game crashes when opening saved game

### Steps to Reproduce Issue
Well, when I try to open my saved game, it crashes in a few moments.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/JEUhWfck

**Version of Mod Pack using:** [crashing started while using version 1.2.9, but even after updating the pack, the game crashed (quite obvious)]

**Where did this bug happen:** [Single Player or Server]
Singleplayer

### Additional Information
[Any other information that may be able to help me with the problem]
Ask anything you need. Probably my fault though :(

**Comment by MJRLegends** [comment]
Thanks for the bug report, i've reported this to the devs but im sure its just a rare random weird issue haha https://github.com/aidancbrady/Mekanism/issues/4701

**Comment by onehappyballoon** [comment]
Ahh that sucks, I was hoping to play in that world again soon :S 
Last backup was made like a week earlier :D

**Comment by onehappyballoon** [comment]
So I changed my location using NBTExplorer and now my world does not crash anymore. Thanks :P

**Comment by MJRLegends** [comment]
I've added this to the known issues over at #99
