### ISSUE TITLE
Mekanism & Power armor issue

### ISSUE THREAD

**Issue by Berserker66** [MJRLegends/Space-Astronomy-2-Feedback-#127]
### Steps to Reproduce Issue
1. You take this simple power armor config: https://i.imgur.com/pSGKNxT.png
2. Put that in a Energy Cube on the minus end: https://i.imgur.com/PPBNAV6.png

**Version of Mod Pack using:** Latest, aka 1.3.0
**Where did this bug happen:** Single Player

You take this simple power armor config: https://i.imgur.com/pSGKNxT.png
Put that in a Energy Cube on the minus end: https://i.imgur.com/PPBNAV6.png

And you will charge your energy cube to full:
https://i.imgur.com/vlsYwaB.png

It does not happen instantly, one can see how the power armor is charging the cube and how the cube is charging the power armor.

You can put the armor in the plus afterwards to also fill it up.

**Comment by MJRLegends** [comment]
Please fill out the following

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Version of Mod Pack using:** [VERSION]

**Where did this bug happen:** [Single Player or Server]

**Comment by Berserker66** [comment]
1. You take this simple power armor config: https://i.imgur.com/pSGKNxT.png
2. Put that in a Energy Cube on the minus end: https://i.imgur.com/PPBNAV6.png

**Version of Mod Pack using:** Latest, aka 1.3.0
**Where did this bug happen:** Single Player

**Comment by MJRLegends** [comment]
Thanks for the bug report, i've reported it to both devs https://github.com/MachineMuse/MachineMusePowersuits/issues/818 https://github.com/aidancbrady/Mekanism/issues/4702

**Comment by lehjr** [comment]
Found the issue, applied the fix, and should have a fixed version uploaded by the end of the day.
