### ISSUE TITLE
Trying to ride a horse damages it

### ISSUE THREAD

**Issue by remco082000** [MJRLegends/Space-Astronomy-2-Feedback-#129]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**
Yes, didn't find similar issue.

### Description of Issue
When I try to ride a horse, it damages it when I mount it.

### Steps to Reproduce Issue
1. Try to ride a horse
2. Damages the horse

**Crash log/Log (if applicable):**
Not applicable.

**Screenshots (if applicable):** 
https://imgur.com/PqcFF9q

**Version of Mod Pack using:**
v1.3.0

**Where did this bug happen:** [Single Player or Server]
Singleplayer

### Additional Information
Switched the mouse buttons (lmb = use item / place block, rmb = attack / destroy)
This doesn't happen when the mouse buttons are in their default settings!

**Comment by MJRLegends** [comment]
So it doesnt happen with the normal assigned keys?

**Comment by remco082000** [comment]
Yes, @MJRLegends

**Comment by MJRLegends** [comment]
@remco082000 Since the changes of them keys being changed it low im going to class this as not a bug since it works in the context its made for also could be a vanilla bug in which case its never getting fixed for 1.10 mc

**Comment by MJRLegends** [comment]
Thanks for the bug report though :D
