### ISSUE TITLE
Iron duping.

### ISSUE THREAD

**Issue by cheeseburgur101** [MJRLegends/Space-Astronomy-2-Feedback-#13]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** ye
### Description of Issue
The "crushing gear" from Rockhounding Mod: Chemistry costs 1 iron ingot to make, while putting it in the smeltery to melt it back down returns 208mb, even though 144mb = 1 ingot.

### Steps to Reproduce Issue
1. throw a crushing gear into a smeltery
2. it will give you 64mb more iron then when you started

**Crash log/Log (if applicable):** No crash

**Version of Mod Pack using:** 1.0.8 (server hasn't updated yet)
### Additional Information
Nope.

**Comment by MJRLegends** [comment]
Fixed in V1.1.0 Beta, Thanks for the bug report
