### ISSUE TITLE
Galacticraft Gas Liquefier won't connect

### ISSUE THREAD

**Issue by RayYung** [MJRLegends/Space-Astronomy-2-Feedback-#130]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Galacticraft Gas Liquefier does not connect to any power cables.
I tried Aluminum Wire, Heavy Aluminum Wire, EnderIO energy conduit, Mekanism Universal Cable. 

### Steps to Reproduce Issue
1. Craft Gas Liquefier
2. connect cables or wires

**Crash log/Log (if applicable):** 

**Screenshots (if applicable):** 

**Version of Mod Pack using:** v1.3.0

**Where did this bug happen:** Single Player

### Additional Information
Other Galacticrft machines seems fine, only this one is not taking power...

**Comment by MJRLegends** [comment]
Try connect the power to the bottom of the machine

**Comment by RayYung** [comment]
Damn, my fault....
(why this is the only one....... @_@)

**Comment by MJRLegends** [comment]
Yeah haha, The other inputs are for fluid and that
