### ISSUE TITLE
Vehicle Charger (WIP) Not Craftable

### ISSUE THREAD

**Issue by EnergySmithe** [MJRLegends/Space-Astronomy-2-Feedback-#132]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes

### Description of Issue
Vehicle charger needed for Tier 10 rocket not craftable. Has recipe that requires three batteries with exactly 9281 RF/9375 RF - but the increment/decrement for the battery in machines appears to be 125.

### Steps to Reproduce Issue
1. Place 6 Desh Ingots and 3 Galacticraft Batteries with any level in crafting grid in pattern for Vehicle Charger
2. Recipe does not work

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Screenshots (if applicable):** 
https://imgur.com/a/6LhBz

**Version of Mod Pack using:** [VERSION]
1.3.0

**Where did this bug happen:** [Single Player or Server]
Both Single Player and Server

### Additional Information
Of course, can creative it in and it works fine, so not a show stopper!  Great pack!

**Comment by MJRLegends** [comment]
Fixed in v1.3.1 which has been released
