### ISSUE TITLE
Tier 10 Electric Rocket Parachest Issue

### ISSUE THREAD

**Issue by EnergySmithe** [MJRLegends/Space-Astronomy-2-Feedback-#133]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes

### Description of Issue
In Galacticraft Core Parachest the Tier 10 Electric returns as a regular Tier 10 rocket (non-electric) without any storage.

### Steps to Reproduce Issue
1. Launch with any Tier 10 Electric rocket
2. goto planet where you parachute (can be back to overworld)
3. Parachest contains Tier 10 regular rocket, not electric.  Pad is correct though.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* 

**Screenshots (if applicable):** 
https://imgur.com/a/qb2VN

**Version of Mod Pack using:** 
1.3.0 

**Where did this bug happen:** 
Both

**Comment by MJRLegends** [comment]
Fixed in v1.3.1 which has been released
