### ISSUE TITLE
The Server Crashes When I Run It.

### ISSUE THREAD

**Issue by GokhanOfficial** [MJRLegends/Space-Astronomy-2-Feedback-#134]
### ---Issue Report---
I checked all issues.

### Description of Issue
The server crashes when I run it.

### Steps to Reproduce Issue
1. Copy old world files to new server folder.
2. Start server.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
[crash-2017-09-29_16.31.24-server.txt](https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/files/1344541/crash-2017-09-29_16.31.24-server.txt)
[fml-server-latest.log](https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/files/1344542/fml-server-latest.log)

https://pastebin.com/2vgdvHYc

(I can't upload to PASTEBIN.)

**Screenshots (if applicable):** 

**Version of Mod Pack using:** 1.3.1, latest version.

**Where did this bug happen:** on Server

### Additional Information
Since version 1.2.8 I have been playing with the same world file. I have updated other versions when they are released. I can play smoothly with version 1.3.0. I can play this version with a new record file, but I do not want it.

**Comment by MJRLegends** [comment]
Fixing now v.1.3.2 in will be out in a bit

**Comment by MJRLegends** [comment]
v1.3.2 is out :D

**Comment by GokhanOfficial** [comment]
You're too fast.
