### ISSUE TITLE
IC2 cross-breeding broken

### ISSUE THREAD

**Issue by robert3687088** [MJRLegends/Space-Astronomy-2-Feedback-#135]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]crop sticks for cross breeding won't craft

### Steps to Reproduce Issue
1. [First step]  can't craft
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82 doesn't crash just doesn't craft

**Screenshots (if applicable):** none
**Version of Mod Pack using:** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
They are disabled so this is intended
