### ISSUE TITLE
Metal Press Does Not Transform

### ISSUE THREAD

**Issue by GokhanOfficial** [MJRLegends/Space-Astronomy-2-Feedback-#136]
### ---Issue Report---
I checked all issues.

### Description of Issue
I can't set up the metal press.

### Steps to Reproduce Issue
1. Place blocks by looking at the manual.
2. Click the piston with an Engineer's Hammer.

**Screenshots (if applicable):** 
![2017-10-01_14 48 37](https://user-images.githubusercontent.com/32392391/31054265-d35a6c1e-a6b7-11e7-9648-1602a3027233.png)
![2017-10-01_14 48 44](https://user-images.githubusercontent.com/32392391/31054267-d80d06ea-a6b7-11e7-8077-f8c864fae8da.png)
![2017-10-01_14 49 03](https://user-images.githubusercontent.com/32392391/31054269-dac1e13a-a6b7-11e7-91d9-c834bfbf564a.png)

**Version of Mod Pack using:** 1.3.2 - Latest version

**Where did this bug happen:** Server

### Additional Information
I can't set up the metal press. The hammer rotates the piston. I can not complete structure. I need it.

**Comment by MJRLegends** [comment]
@GokhanOfficial Are you defo using the normal conveyors and not the redstone-ignoring ones?

**Comment by MJRLegends** [comment]
I can reproduce this issue :D i will see what i can do

**Comment by MJRLegends** [comment]
Ok so after more testing, it does work,

**Steps to make it:**
1. Use normal conveyors and not the redstone-ignoring ones
2. Make sure it looks like this and has the conveyors in the same direction
3. Click the piston
![2017-10-03_18 19 10](https://user-images.githubusercontent.com/8526321/31138754-6b645e38-a867-11e7-9cff-632f686d2f16.png)
![ezgif-4-4f1ed0964a](https://user-images.githubusercontent.com/8526321/31138866-c53e4414-a867-11e7-950b-99c8b05ffb4c.gif)
