### ISSUE TITLE
Game Lag and Crash

### ISSUE THREAD

**Issue by Wolfmatic** [MJRLegends/Space-Astronomy-2-Feedback-#137]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
The game lags and crashes when either opening or just being in a world.
### Description of Issue
[Description of the issue]
The game lags and crashes when either opening or just being in a world. I have allocated 5GB of RAM like it has been recommended and its still crashing.
### Steps to Reproduce Issue
1. [First step] Open world
2. [Second step]Crash

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]1.3.2

**Where did this bug happen:** [Single Player or Server]Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Crash log???

**Comment by Wolfmatic** [comment]
The crash log cannot be viewed

**Comment by Wolfmatic** [comment]
Please help

**Comment by MJRLegends** [comment]
You can use this to find the crash log

**How do i locate a crash log on Minecraft on Curse/Twitch? see https://gyazo.com/3c616a7dfcbe69033ea210805b093f82**

Without it its impossible for me to know your issue and be able to help you, im not able to read computer programs minds sorry

**Comment by Wolfmatic** [comment]
Dude, there is no such folder. I looked.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Wolfmatic** [comment]
It actually doesn't really crash, but it freezes my entire computer and
after half and hour I have to force shut down.

**Comment by MJRLegends** [comment]
Yeah this isnt a pack issue
