### ISSUE TITLE
Server crashes instantly, I can't seem to set it up correctly

### ISSUE THREAD

**Issue by Yarillo4** [MJRLegends/Space-Astronomy-2-Feedback-#138]
I'm trying to set up my first Space Astronomy 2 server but it doesn't seem to work.

I'm on linux with full access through SSH.

### Steps to Reproduce Issue

1. Download the server files for 1.3.2 https://minecraft.curseforge.com/projects/space-astronomy-2/files/2485457#additional-files
2. Extract. 
3. java -jar server.jar --nogui
4. accept eula
5. java -jar server.jar --nogui
6. rm -r world/*
7. java -jar forge.jar --nogui
8. Instant crash

**Crash log/Log (if applicable):** 

* https://pastebin.com/51iFa4LG

**Version of Mod Pack using:** 

* 1.3.2

**Comment by MJRLegends** [comment]
Your missing the liberties folder forge needs

**Comment by MJRLegends** [comment]
*libraries

**Comment by Yarillo4** [comment]
Ooooooooooh every goddamn time

**Comment by MJRLegends** [comment]
No problem
