### ISSUE TITLE
Tinkers Crafting station With Mekanism solar panel causes a crash

### ISSUE THREAD

**Issue by Kanakotka** [MJRLegends/Space-Astronomy-2-Feedback-#139]
### ---Issue Report---
Yup, read known issues.

### Description of Issue
Crash on placing Mekanism solar panel onto a Tinker's crafting station (rendering issue)
Encountered crash upon trying to make an advanced Mekanism solar panel
Crash is new to 1.3.2 and is not there in 1.3.0

### Steps to Reproduce Issue
1. Place a Mekanism Solar Panel (not advanced) onto a Crafting Station.

**Version of Mod Pack using:** 1.3.2
**Where did this bug happen:** Private Server

**Comment by MJRLegends** [comment]
I will be needing the crash log please before i can evem attempt to look at this

**Comment by Kanakotka** [comment]
It appears this crash does not generate a crash log for me on either single- or multiplayer, but the issue is reproducible on both single- and multiplayer and it is not related to better FPS (which i disabled as well)

It seems to be jarringly common that Minecraft does not generate crash logs for rendering issue related crashes in the new launcher.

**Comment by MJRLegends** [comment]
Im unable to help then without that crash log please post it here when you have one or post your full logs

**Comment by MJRLegends** [comment]
Crash log for this issue https://pastebin.com/DALANh9h

**Comment by MJRLegends** [comment]
Reported to devs: https://github.com/aidancbrady/Mekanism/issues/4734

**Comment by MJRLegends** [comment]
@Kanakotka Try turning off the item rendering option of Tinkers Construct, should be a workaround to this issue.

**Comment by MJRLegends** [comment]
will be fixed fully in v1.3.3

**Comment by pyscho974** [comment]
we had same issue.. did not happen till i recently updated spongeforge tho and only with tinkers crafting stations. hoping to test on the latest spongeforge later today with updated pack and see if still is a issue.

**Comment by MJRLegends** [comment]
Update is out please update
