### ISSUE TITLE
Bonemeal duping

### ISSUE THREAD

**Issue by cheeseburgur101** [MJRLegends/Space-Astronomy-2-Feedback-#14]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** ye
### Description of Issue
Bonemeal block requires 4 bonemeal to make, but converting it back gives you 9 bonemeal, 5 more than what you started with.

### Steps to Reproduce Issue
1. craft bonemeal block
2. craft back into bonemeal

**Crash log/Log (if applicable):** No crash

**Version of Mod Pack using:** 1.0.8 (server still hasn't updated)

### Additional Information
Nope.

**Comment by cheeseburgur101** [comment]
it's actually just called the "bone block", not 
bonemeal block"

**Comment by MJRLegends** [comment]
Fixed in V1.1.0 Beta, Thanks for the bug report
