### ISSUE TITLE
 Discharge of atomic disassembly

### ISSUE THREAD

**Issue by MiguelTdN** [MJRLegends/Space-Astronomy-2-Feedback-#140]
When walking with the kinect generator (modifier in the legs of the power swit) and at the same time being with atomic disassembler (mekanism) causes the atomic to completely discharge if the armor is full

1.Use the power switch pants (with full charge and modifier of power generation through the kinetic generator steps)
2.Get an atomic disassembler in hand (with a little charge so it can be discharged)

Modpack version 1.3.2

Singleplayer

I'm using the google translator, any grammatical error I'm sorry

![image](https://user-images.githubusercontent.com/32468943/31100739-0990c118-a7a1-11e7-9ba9-e1049e415b1c.png)
![image](https://user-images.githubusercontent.com/32468943/31100740-0b385f9e-a7a1-11e7-9879-5c80d723e97f.png)
![image](https://user-images.githubusercontent.com/32468943/31100746-0d9bacaa-a7a1-11e7-9227-c4d79288dba8.png)
![image](https://user-images.githubusercontent.com/32468943/31100748-10399f8a-a7a1-11e7-9be9-7eb31202d7f5.png)

**Comment by MJRLegends** [comment]
Report to devs: https://github.com/MachineMuse/MachineMusePowersuits/issues/820

**Comment by MJRLegends** [comment]
Will be fixed in v1.3.3 :P
