### ISSUE TITLE
Journey Map Death Marker

### ISSUE THREAD

**Issue by ANNOYEDCHERRY** [MJRLegends/Space-Astronomy-2-Feedback-#141]
Journey Map Death Markers not be created upon death

### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You need to post more information a title isnt going to cut it

**Comment by MJRLegends** [comment]
Works for me 
![](https://i.gyazo.com/ca880d0b193fd4a045805b34388ae53c.png)
![](https://i.gyazo.com/9e68ed894d4ac6a4357461d692a00318.png)
