### ISSUE TITLE
Engineer's Manual Crash

### ISSUE THREAD

**Issue by BlackMist1035** [MJRLegends/Space-Astronomy-2-Feedback-#142]
### ---Issue Report---
**Yes

### Description of Issue
using the Immersive Engineering book will cause game to crash 

### Steps to Reproduce Issue
Use the Engineer's Manual for like a couple of minutes

**Crash log/Log https://pastebin.com/EV7dhzeJ
**Screenshots (if applicable):** 

**Version of Mod Pack using:** 1.3.2
**Where did this bug happen:** Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
No your just not using enough ram 2GB of ram isnt going to work, you need 5GB+
```

java.lang.OutOfMemoryError: GC overhead limit exceeded
    at net.minecraft.util.EnumFacing.values(EnumFacing.java:13)
    at net.minecraft.util.EnumFacing.func_176737_a(EnumFacing.java:229)
```
