### ISSUE TITLE
IC2 Texture Missing

### ISSUE THREAD

**Issue by Grant28** [MJRLegends/Space-Astronomy-2-Feedback-#143]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [**Yes** or No]

### Description of Issue
Missing texture of IC2 generator. (Purple and Black checkered board pattern)

### Steps to Reproduce Issue
1. When I first place the generator down it is fine.
2. When I disconnect and join back the texture is missing.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 
![minecraft 1 10 2 2017-10-04_18-16-47](https://user-images.githubusercontent.com/32528028/31202323-24937e0c-a930-11e7-866e-3dd392ad1c4b.jpg)
![minecraft 1 10 2 2017-10-04_18-16-47](https://user-images.githubusercontent.com/32528028/31202331-2f66fade-a930-11e7-8e9c-1dabc9344b13.jpg)

**Version of Mod Pack using:** 
v1.3.2
**Where did this bug happen:** Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Ok

Please fill out the following questions:

Are you using a texture/resouce pack? 
Are you using Optifine?
Which server are you playing on?
Is the server you are on using sponge?

Also please could you post your latest.log and fml-latest.log files (You can drag the files in the comment box to add them here)
