### ISSUE TITLE
NeoTech Iron Nuggets are not supported

### ISSUE THREAD

**Issue by CaffeineKitty** [MJRLegends/Space-Astronomy-2-Feedback-#145]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [**Yes** or No]

### Description of Issue
NeoTech Iron Nuggets are unusable.

### Steps to Reproduce Issue
1. Cook a Poor Iron Ore in a furnace.
2. Take the resultant Iron Nugget and try to do ANYTHING with it.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using:**
1.3.2

**Where did this bug happen:** [Single Player or Server]
Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Will be fixed in v1.3.3 :P

**Comment by pyscho974** [comment]
could be used in the neo crucible and poured out as ingots. just saying :)

**Comment by MJRLegends** [comment]
Yeah the update is out noe anyways
