### ISSUE TITLE
Flux Networks point and plugs not working with Mekanism Induction Matrix

### ISSUE THREAD

**Issue by SwiftingDuster** [MJRLegends/Space-Astronomy-2-Feedback-#148]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Flux Point and Flux Plug from FluxNetworks do not work when **directly** connecting to mekanism induction matrix ports.

### Steps to Reproduce Issue
1. Make a induction matrix with 2 ports
2. Setup a FluxNetwork power system and place flux point and flux plug on the input and output of induction matrix respectively. Then charge induction matrix to a reasonable extend.
3. Try and pull/push power from and to induction matrix.
4. Look at how it fails to do so :(

**Version of Mod Pack using:** v1.3.0

**Where did this bug happen:** Server

### Additional Information
Mod author of Flux Network claims to have fixed it in dev version. Also it seems to work on 1.2.3 of Flux Network (what others commented, not tested myself). Hoping to see an update/rollback to previous working version soon if possible.
https://github.com/SonarSonic/Flux-Networks/issues/121

**Comment by MJRLegends** [comment]
I've added this to the known issues over at #99

**Comment by MJRLegends** [comment]
Should be fixed in v1.4.5 if not please let me know

**Comment by MJRLegends** [comment]
Latest version of mod was broke so this wont be fixed yet
