### ISSUE TITLE
smeltery will not pour to casting table

### ISSUE THREAD

**Issue by evilredqueen** [MJRLegends/Space-Astronomy-2-Feedback-#149]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING): yes

### Description of Issue
the smeltery will pour to the basin and make blocks but will not pour to the casting table. I have tried different metals but nothing works pouring to the casting table.

### Steps to Reproduce Issue
1. build a smeltery
2. attempt to make a cast

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using:** VERSION]1.3.2

**Where did this bug happen:** Single Player

### Additional Information
I keep switching the position of the casting table with the basin. The basin always works, the table never does. I want to cry.

**Comment by MJRLegends** [comment]
You need to put a ingot cast in it or a part cast
