### ISSUE TITLE
I cant find gold

### ISSUE THREAD

**Issue by drettraz** [MJRLegends/Space-Astronomy-2-Feedback-#150]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes
### Description of Issue
[Description of the issue]
I cant find gold. I search whole world
### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]
v.1.3.2
**Where did this bug happen:** [Single Player or Server]
Single player
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
This isnt a issue is it haha your just getting unlucky

**Comment by drettraz** [comment]
I know but I play 6 hours still cant find.
