### ISSUE TITLE
If automating complex recipes with galacticraft electric compressor ingredients disappear

### ISSUE THREAD

**Issue by calvinII** [MJRLegends/Space-Astronomy-2-Feedback-#151]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Hi, when I automatically craft Heavy-Duty-Plate using the Crafter from Refined Storage Ingredients disappear from Grid and nothing is built:

 

### Steps to Reproduce Issue
`CS==compressed Steel CA==compressed Aluminium CB==compressed Bronze HP == Heavy Duty Plate`
1. Setup: Crafter | GC Electric Compressor | RF-Source
2. Dont add some Importer or so to see the Effect
put following Items in your RF-Storage 2x CS 2xCA 2xCB 
3. insert following Pattern in crafter:  
    `CS CA CB` => `HP`
    `CS CA CB` => `HP`
4. let the crafter craft one Plate
5. Result: No Plate and the Crafting Pattern in the compressor is layed out as following:
    `CS CA CB`
    `CS`
5. the Storage has no Compressed Plates left over.
 
**Screenshots (if applicable):** 
![bildschirmfoto von 2017-10-10 21-35-57](https://user-images.githubusercontent.com/10009510/31406922-633c4814-ae03-11e7-8257-0eb3269b94da.png)
![bildschirmfoto von 2017-10-10 21-37-26](https://user-images.githubusercontent.com/10009510/31406938-6df4e3b0-ae03-11e7-8590-4896d526c040.png)

**Version of Mod Pack using:** 
    I'm playing Space Astronomy 1.3.2 on MultiMC

**Where did this bug happen:** Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by SwiftingDuster** [comment]
This happens on a multiplayer server (v1.3.0) I'm playing on as well. Met this problem yesterday too but didn't realize it magically eats your plates too.

**Comment by MJRLegends** [comment]
@calvinII and @SwiftingDuster Thank for the bug report, i've reported it to the devs here :D https://github.com/micdoodle8/Galacticraft/issues/3006

**Comment by MJRLegends** [comment]
Ok the Galacticraft devs cant fix this as its a refined storage thing, put a hopper in between refined storage crafter and a hopper
