### ISSUE TITLE
Pam's HarvestCraft Market spawn egg trading bug

### ISSUE THREAD

**Issue by SwiftingDuster** [MJRLegends/Space-Astronomy-2-Feedback-#152]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
When you try to trade emeralds for spawn eggs with the Pam's HarvestCraft market, you get spawn eggs without data, which cannot spawn anything. **This happens to all spawn eggs.**

### Steps to Reproduce Issue
1. Get a market block and at least 9 emeralds.
2. Open and click left arrow a few times to navigate to ANY spawn egg.
3. Put in 9 emeralds and make the trade.
4. Receive a blank spawn egg.

**Screenshots (if applicable):** 
Trying to trade for ocelot egg. Tried on cow/sheep/chicken too but all yield same results.
![image](https://user-images.githubusercontent.com/25877083/31502716-762418e6-afa0-11e7-8f89-0953378f88ef.png)

**Version of Mod Pack using:** v1.3.0

**Where did this bug happen:** Server

### Additional Information
Saw this issue about ghast egg with tag "fixed in the next version":
https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/issues/113
Since that guy was on 1.2.8 and I'm on 1.3.0, i suppose this is a new problem.
Don't think this can be a "it doesn't exist" problem like before since every vanilla spawn egg don't work.

**Comment by MJRLegends** [comment]
Please test with latest version

**Comment by technomancer21** [comment]
Issue confirmed in version 1.12a, direwolf20 1.12.2 modpack version 1.8 release,
Blank spawn egg received after trading via the market block. behaviour consistently reproduced.

**Comment by Natesky9** [comment]
Can confirm, still exists in 1.12.2u
any spawn eggs purchased from the market do not have NBT tags, and are just blank "Spawn "

Custom pack with no quest mods gating progression

**Comment by MJRLegends** [comment]
@Natesky9 Should I create new issue? Yes please
