### ISSUE TITLE
Navigation Upgrade from OpenComputers recipe calls for Map #0 

### ISSUE THREAD

**Issue by Kanakotka** [MJRLegends/Space-Astronomy-2-Feedback-#153]
### Description of Issue
There can only ever be 1 Map #0 because any map increments the value and map #0 has no specific crafting recipe. Perhaps change the recipe back to using Empty Map instead?

**Version of Mod Pack using:** 1.3.2

**Where did this bug happen:** Irrelevant

**Comment by MJRLegends** [comment]
Seems to work on for me

Please see the following https://gyazo.com/9d2a5db2acd3fa6b8381e857f2efeb88
