### ISSUE TITLE
[1.3.2] Cannot craft aluminum blocks from aluminum ingots

### ISSUE THREAD

**Issue by savosdarkran** [MJRLegends/Space-Astronomy-2-Feedback-#154]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue

Cannot craft aluminum blocks from aluminum ingots
### Steps to Reproduce Issue
1. put 9 ingots in a 3x3 grid.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Screenshots (if applicable):** 

**Version of Mod Pack using:**  1.3.2

**Where did this bug happen:** [Single Player or Server] Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Will be fixed in v1.3.3 :P

**Comment by savosdarkran** [comment]
ty sir
