### ISSUE TITLE
Reborn Storage bug in reopening the world

### ISSUE THREAD

**Issue by DarkPedro** [MJRLegends/Space-Astronomy-2-Feedback-#155]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
When I reopen the world and see the Refined Storage Grid, the patterns inside the Reborn Storage multi-block computer are gone from the Grid. They only come back when I break the cable and put it back.

### Steps to Reproduce Issue
1. Make a Reborn Storage Multi-Block Computer
2. Put the patterns inside the computer
3. Reopen the world and try to find the patterns in the Grid

**Screenshots (if applicable):** 
This print is before I reopen the world.
![print1](https://user-images.githubusercontent.com/32803928/31580131-6c3180fc-b11d-11e7-9bab-83fa55f434db.png)
Grid,Multi-Block Computer,Controller
![2017-10-14_20 26 52](https://user-images.githubusercontent.com/32803928/31580160-4b5530da-b11e-11e7-9412-831be557b505.png)
This print is after I reopen the world.
![screenshot_2](https://user-images.githubusercontent.com/32803928/31580227-ac07d558-b11f-11e7-854e-83dc1d877214.png)

**Version of Mod Pack using:** Space Astronomy 1.3.3 in Twitch

**Where did this bug happen:** Single Player

**Comment by MJRLegends** [comment]
@DarkPedro Are you still getting this issue, if so are you able to try out somethings to see if it fixes it

**Comment by DarkPedro** [comment]
It works if I put a Relay, and put it to be activated with redstonel, so it will turn off and connect the signal ...

**Comment by DarkPedro** [comment]
It works if I put a Relay, and put it to be activated with redstone, so it
will turn off and connect the signal ...

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-11-13 13:50 GMT-02:00 MJRLegends <notifications@github.com>:

**Comment by MJRLegends** [comment]
How many cables are connected to it and please post images with chunk borders on so i can see where each thing is and what chunk its in

**Comment by MJRLegends** [comment]
Also is it chunk loaded with anything?

**Comment by DarkPedro** [comment]
No, the chunk not have a chunk loader, or Universal Anchor

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-11-14 18:30 GMT-02:00 MJRLegends <notifications@github.com>:

**Comment by DarkPedro** [comment]
[image: Imagem inline 2][image: Imagem inline 1][image: Imagem inline 5][image:
Imagem inline 4][image: Imagem inline 3]These are the images:


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by DarkPedro** [comment]
![2017-10-14_20 26 52](https://user-images.githubusercontent.com/32803928/32891946-afc52d20-cabb-11e7-8acb-0ae4b1dd2205.png)
![2017-11-15_21 00 47](https://user-images.githubusercontent.com/32803928/32891952-b4201d4e-cabb-11e7-9062-5d262096bf4d.png)
![2017-11-15_21 01 20](https://user-images.githubusercontent.com/32803928/32891953-b4603096-cabb-11e7-83fa-6007fa442ef2.png)
![2017-11-15_20 59 54](https://user-images.githubusercontent.com/32803928/32891954-b4a7bd62-cabb-11e7-96c2-56d274d51777.png)
![2017-11-15_21 00 17](https://user-images.githubusercontent.com/32803928/32891955-b4e5b1f8-cabb-11e7-9306-d87a768ed147.png)
