### ISSUE TITLE
Game crashing at the loading part

### ISSUE THREAD

**Issue by Iluminatorr** [MJRLegends/Space-Astronomy-2-Feedback-#156]
### ---Can't start the game;---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
at the start of the game loading it just crashes at the rftools loading part. I tried to start other versions, but that keeps on going.

### Steps to Reproduce Issue
1. just start the launcher
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
![err0r2](https://user-images.githubusercontent.com/32812643/31584022-81651eb6-b1ae-11e7-8813-053a34788e96.png)

**Screenshots (if applicable):** 
![error](https://user-images.githubusercontent.com/32812643/31584024-84f2e19e-b1ae-11e7-8c93-3cdf788993fd.png)

**Version of Mod Pack using:** [a lot]

**Where did this bug happen:** [Single Player ]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Yeah your probably not aasigning enough ram also a screenshot of a crash log isnt helpful
