### ISSUE TITLE
RFTools Server Crash with shape cards - fixed in a newer version of RFTools.

### ISSUE THREAD

**Issue by ZombieSoul** [MJRLegends/Space-Astronomy-2-Feedback-#158]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
Shape card can crash the server when cycling through shapes after selecting hollow.

### Steps to Reproduce Issue
1. Craft a shape card and set the type to hollow.
2. Cycle through shapes available, the server will crash at the point when it should show the scan option.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
>https://pastebin.com/uBTfs2Cr
**Screenshots (if applicable):** 

**Version of Mod Pack using:** 
1.3.3

**Where did this bug happen:** [Single Player or Server]
Server

### Additional Information
[Any other information that may be able to help me with the problem]
Just need to update RFTools- the developer fixed this in 7.11 and 7.12 fixes other issues that may impact a server.

**Comment by MJRLegends** [comment]
Yeah hes already fixed it but thanks for the report
