### ISSUE TITLE
Universal Fluid Cell [Industrial Craft 2] missing in JEI

### ISSUE THREAD

**Issue by Karthas077** [MJRLegends/Space-Astronomy-2-Feedback-#159]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Universal Fluid Cell [Industrial Craft 2] is craft-able but cannot be searched for in the JEI interface.

### Steps to Reproduce Issue
1. Search for "Universal Fluid Cell" or any other tags for Industrial Craft 2
2. Item/recipe is not listed in JEI

**Crash log/Log (if applicable):**
N/A

**Screenshots (if applicable):** 
https://puu.sh/y0S92/e9865e80ec.jpg

**Version of Mod Pack using:**
Version 1.3.3 (Twitch Client)

**Where did this bug happen:**
Single Player

### Additional Information
The recipe can still be viewed by routing through other recipes such as Tin Item Casings, and the item appears to function as intended once crafted.

**Comment by MJRLegends** [comment]
Yeah i removed them from showing

**Comment by Karthas077** [comment]
If you can still craft them, what purpose does this serve beyond making this mod pack less accessible to those who are not familiar with Industrial Craft?
