### ISSUE TITLE
Picking up Immersive Engineering storage crate sometimes deletes contents

### ISSUE THREAD

**Issue by Hazmatik** [MJRLegends/Space-Astronomy-2-Feedback-#16]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
Sometimes, not always, when I pick up and move an immersive engineering storage crate after placing it back down all the contents inside are missing.

### Steps to Reproduce Issue
1. Place Items in crate
2. Pick up crate
3. Place crate down again
4. If items are still there try again it doesn't always happen but it does happen

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]
1.0.9 - beta

**Comment by MJRLegends** [comment]
Thanks i see you posted it here already https://github.com/BluSunrize/ImmersiveEngineering/issues/2245

**Comment by MJRLegends** [comment]
Also see my comment on the ImmersiveEngineering issue page

**Comment by MJRLegends** [comment]
Added to Known issues thread #99
