### ISSUE TITLE
Selecting fluid in Tinkers Construct kicks me out

### ISSUE THREAD

**Issue by Bomave** [MJRLegends/Space-Astronomy-2-Feedback-#164]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**

Yes

### Description of Issue
I put in several ingots and ores into the tank of the smeltery and when I try to select a fluid to pour it out, it kicks me from the server, especially happens with aluminum brass.

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

https://pastebin.com/8PWv045i

I hope this helps!

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]

1.3.4

**Where did this bug happen:** [Single Player or Server]

Server

### Additional Information
[Any other information that may be able to help me with the problem]

Just got kicked out another time but this time I wasn't using the smeltery. I was using the table to assemble a sword. I tried to click on the sword icon and got kicked out. Here the error: https://pastebin.com/ESTq54MW

I think the blood in the smeltery could be causing this. In the consol it says there's blood in the smeltery but we cannot select or see the blood in the tank when we're using the control block.

**Comment by MJRLegends** [comment]
@Bomave ok just done some tests for this and im unable to get this problem. Is it your server or are you able to get hold of the server owner?

**Comment by Bomave** [comment]
It's my server actually me and my friend play on.

**Comment by MJRLegends** [comment]
Ok i've done some more testing and i cant reproduce this. Please break the smeltery or delete it using MCEdit. http://www.mcedit.net/

If it happens again please repost here
