### ISSUE TITLE
Advanced Induction Cell missing from JEI

### ISSUE THREAD

**Issue by majorpayne0055** [MJRLegends/Space-Astronomy-2-Feedback-#166]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
Advanced Induction Cell missing from JEI, but the Basic Induction Cell is showing up twice.

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 
https://imgur.com/a/6wtGJ

**Version of Mod Pack using:** [VERSION]
1.3.4
**Where did this bug happen:** [Single Player or Server]
Multiplayer
### Additional Information
It's still craftable if you know the recipe, just not in the JEI.

**Comment by MJRLegends** [comment]
I did a test and seems to show for me: 
![](https://i.gyazo.com/d952ba4337fa44cedc5b58bde774ecf2.png)

will look in to it more though
