### ISSUE TITLE
Rockhounding titanium ingots not usable for anything

### ISSUE THREAD

**Issue by WhisperFire26** [MJRLegends/Space-Astronomy-2-Feedback-#167]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
No

### Description of Issue
Rockhounding titanium ingots do not work with Galacticraft titanium crafting recipes. You must use Galacticraft titanium instead. The Rockhounding titanium is useless.

### Steps to Reproduce Issue
Feedback only

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
N/A

**Screenshots (if applicable):** 

**Version of Mod Pack using:** 
1.3.4

**Where did this bug happen:** 
Single Player

### Additional Information
Just feedback. Game works fine otherwise.

**Comment by MJRLegends** [comment]
This is intended use for the Galacticraft recipes, the Rockhounding titanium has got uses but not with Galacticraft
