### ISSUE TITLE
[1.3.4] Quantum Generator recipe not showing

### ISSUE THREAD

**Issue by savosdarkran** [MJRLegends/Space-Astronomy-2-Feedback-#168]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
When clicking on Quantum Generator I do not get a recipe for it.

### Steps to Reproduce Issue
1. Open JEI
2. Search for Quantum Generator
3. Click on Quantum Generator

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
NA

**Screenshots (if applicable):** 
NA

**Version of Mod Pack using:** [VERSION]
1.3.4

**Where did this bug happen:** [Single Player or Server]
Single and Server

### Additional Information
Just wondering if this is by design.

**Comment by MJRLegends** [comment]
Ok after some research this is intended use as its a creative only block


See information i found below (From https://ftbwiki.org/Quantum_Generator )
> The Quantum Generator is a block added by Advanced Solar Panels. It has no crafting recipe and can only be obtained using cheats (/give, cheat mode in NEI, creative mode, and so forth). Its intended use is in adventure maps or other places where the designer of the map desires to give the player a specific quantity of permanent energy supply, but it can also be used as a blatantly cheating method of energy generation.

**Comment by MJRLegends** [comment]
I will mark this using a tooltip for the next update
