### ISSUE TITLE
Typo in quest book

### ISSUE THREAD

**Issue by cheeseburgur101** [MJRLegends/Space-Astronomy-2-Feedback-#17]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
In the achievement book, under the category "alien technology" the first achievement has a typo. it says "genetucs reborn" not "genetics reborn" 

### Steps to Reproduce Issue
1. Look at quest book

**Crash log/Log (if applicable):** No crash

**Version of Mod Pack using:** 1.0.9

### Additional Information
Nope.

**Comment by MJRLegends** [comment]
Thanks i will fix in tonights update

**Comment by MJRLegends** [comment]
Fixed in V1.1.0 Beta, Thanks for the bug report
