### ISSUE TITLE
Item not searchable in JEI

### ISSUE THREAD

**Issue by Arsomang** [MJRLegends/Space-Astronomy-2-Feedback-#170]
The Silicon for Ender IO is not searchable in JEI. Even if i do and @enderIO it doesnt show up.

**Comment by MJRLegends** [comment]
Thats because its disabled If its not in jei you shouldnt use it, press u on the item if you have any

**Comment by Arsomang** [comment]
But it crafts from sand in the crusher and it's in jei as a requirement for
some ender io components and doesn't cycle to any other silicon. Is it
still support to be used for some things like zombie electrodes and
electrical steel?

**Comment by Arsomang** [comment]
Sorry just closed how and searched again now showing other options sorry
for bothering you
