### ISSUE TITLE
Teleporter loses link

### ISSUE THREAD

**Issue by evilredqueen** [MJRLegends/Space-Astronomy-2-Feedback-#171]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
I have a teleporter set up on earth and the moon and Mars.  When I am on the moon or Mars everything is fine. When I come through back to earth after a couple minutes, I walk away or I save game and return the teleporter on Earth loses the link to the others. When I fly back all is working. I can step through and come back home but then the teleporter  ALWAYS loses the link and then I have to fly back again.
### Steps to Reproduce Issue
1. [First step]Set up teleporter on the earth and the moon. Come through and walk away for a time or save game and return.
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]
1.3.2

**Where did this bug happen:** [Single Player or Server]
Single player
### Additional Information
The teleporter .. black box with green lines and the teleporter frame.
[Any other information that may be able to help me with the problem]

PS Good game !!!!

**Comment by MJRLegends** [comment]
Please update to the latest mod pack version

**Comment by MJRLegends** [comment]
Also use chunk loaders on both sides
