### ISSUE TITLE
IE Visual Bug

### ISSUE THREAD

**Issue by TheRealMondo** [MJRLegends/Space-Astronomy-2-Feedback-#173]
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
visual bug when displaying text in the Engendering manual form IE

### Steps to Reproduce Issue
1. open book
2. go to mineral deposits
3. Profit?
**Screenshots (if applicable):** 
https://imgur.com/gallery/FidSZ
**Version of Mod Pack using:** [VERSION]
1.3.4
**Where did this bug happen:** [Single Player or Server]
Server
### Additional Information
[Any other information that may be able to help me with the problem]
Still possible to see but VERY HARD. Some are off screen. 1920X1080 full screen and maximized

**Comment by MJRLegends** [comment]
Thanks for the bug report but this one is a visual small bug, and the dev isnt updating his mod anymore so im closing this with the terms that it will never be fixed
