### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by TheRealMondo** [MJRLegends/Space-Astronomy-2-Feedback-#174]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
cant even start the game 

### Steps to Reproduce Issue
1. Start Minecraft 
2. Crash
3. Profit?

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/pDgghe04
https://pastebin.com/WdG9LfTV

**Screenshots (if applicable):** 
N/A
**Version of Mod Pack using:** [VERSION]
1.3.5 &1.3.4
**Where did this bug happen:** [Single Player or Server]
Launcher
### Additional Information
It gets basically to the end of building the pack and then crashes back to the launcher. I don't have any resource packs nor have i modified any files outside the in game graphical and key bind options

**Comment by MJRLegends** [comment]
Please see https://github.com/micdoodle8/Galacticraft/issues/3027#issuecomment-343693309 this isnt a mod pack issue so i cant do anything sorry its a gpu and texture issue
