### ISSUE TITLE
The new server files Download file mismatch

### ISSUE THREAD

**Issue by Arsomang** [MJRLegends/Space-Astronomy-2-Feedback-#176]
The new files for version 1.3.5 do not match the mods when you download the client for 1.3.5
And if i copied the mismatched mods over from the client to the server.
If i click on a PowerCell from RFTools then i get disconnected from the server.
So i had to revert back to version 1.3.4 so we could play. So for me version 1.3.5 is unplayable.

Log Files   https://pastebin.com/qAp4N8Pd

**Comment by MJRLegends** [comment]
Both files work please reinstall and download everything and make sure you have the server files

**Comment by Arsomang** [comment]
Just so i know i am doing it corretly. The server files dont have all the mods in them when i download v1.3.5 do i copy the rest from the clients 1.3.5 mod folder?

**Comment by MJRLegends** [comment]
No there's server files

**Comment by MJRLegends** [comment]
http://imgur.com/a/7WgaK

**Comment by Arsomang** [comment]
Thats what i did and i click the server file link and i downloaded the v1.3.5 but all i get is an override folder in the zip with a manifest and Modlist.html 
In the override folder there are Config  Mods resources script folders but the mod folder only has 5 mods in it

**Comment by Arsomang** [comment]
I see whats happening twitch was directing me to the curse site and i needed to go to the curse forge site to see the server files correctly. 
Sorry for bothering you

**Comment by MJRLegends** [comment]
Yeah
