### ISSUE TITLE
Neotech's Electric solidifer doesn't output anything

### ISSUE THREAD

**Issue by krofinzki** [MJRLegends/Space-Astronomy-2-Feedback-#177]
(Edited by MJRLegends)

Okay, here you go:

### ---Issue Report---
Yes

### Description of Issue
Neotech's Electric solidifer doesn't output anything due to a bug in the code. This was fixed back in may in accordance to [pull request #420](https://github.com/TeamBR-Modding/NeoTech/pull/420). Unfortunately no new release has been made since then. Perhaps the code could be merged in by building the code anyway?

I will poke the modmakers for an update as well.

### Steps to Reproduce Issue
1. Make an electric solidifier
2. Put liquids into it that you solidify with any setting (ingot, block, nugget, etc)
3. Try to get the solidified product out via conduit, refined storage importer, etc. nothing will work. only manually grabbing it.

**Crash log/Log (if applicable):**
Not applicable

**Screenshots (if applicable):** 
https://i.imgur.com/jOTDbMG.jpg

**Version of Mod Pack using:**
1.3.3 and 1.3.5 tested

**Where did this bug happen:**
Server

### Additional Information
The necessary upgrade item for controlling input/output on neotech machines; network card was in use on the machine

**Comment by MJRLegends** [comment]
Please fill out the template and i will reopen when done so

**Comment by krofinzki** [comment]
Okay, here you go:

### ---Issue Report---
Yes

### Description of Issue
Neotech's Electric solidifer doesn't output anything due to a bug in the code. This was fixed back in may in accordance to [pull request #420](https://github.com/TeamBR-Modding/NeoTech/pull/420). Unfortunately no new release has been made since then. Perhaps the code could be merged in by building the code anyway?

I will poke the modmakers for an update as well.

### Steps to Reproduce Issue
1. Make an electric solidifier
2. Put liquids into it that you solidify with any setting (ingot, block, nugget, etc)
3. Try to get the solidified product out via conduit, refined storage importer, etc. nothing will work. only manually grabbing it.

**Crash log/Log (if applicable):**
Not applicable

**Screenshots (if applicable):** 
https://i.imgur.com/jOTDbMG.jpg

**Version of Mod Pack using:**
1.3.3 and 1.3.5 tested

**Where did this bug happen:**
Server

### Additional Information
The necessary upgrade item for controlling input/output on neotech machines; network card was in use on the machine

**Comment by krofinzki** [comment]
I noticed this issue hasn't be reopened, sending a poke to @MJRLegends to help get this one going :)

**Comment by MJRLegends** [comment]
@krofinzki thank you, sorry for the slow reply :D

**Comment by MJRLegends** [comment]
I've added this to the known issues over at #99
