### ISSUE TITLE
dead on mercury

### ISSUE THREAD

**Issue by evilredqueen** [MJRLegends/Space-Astronomy-2-Feedback-#178]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
I have been playing this game for three weeks. I accidentally went to mercury instead of venus. I died on the way down and it respawned me on mercury. Now there seems to be no way for me to stay alive. WTF ? I would consider this a huge bug.
### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
This isnt a bug sorry

**Comment by evilredqueen** [comment]
Yes it is.  I am a 64 year old woman and this was my first experience with
Minecraft FTB.  To be playing a game with this much effort and then all of
a sudden to be out of the game with no hope.  I am sorry sir but that is a
huge bug.  I would not have been in this mess if the teleporters had
worked.  I had upgraded and added chunk loaders as you had suggested. Still
didn't work. This game has left a bad taste in my mouth.

**Comment by MJRLegends** [comment]
There's/home /spawn and creative mode

**Comment by MJRLegends** [comment]
All can be used to get to the overworld
