### ISSUE TITLE
character glitching out in singleplayer and multiplayer

### ISSUE THREAD

**Issue by littlegangster1** [MJRLegends/Space-Astronomy-2-Feedback-#179]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes but i was not able to find this sort of glitch

### Description of Issue
[Description of the issue] 

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** i have some gifs https://gyazo.com/b4449ddcb85e4d604594f582a4be3f03  https://gyazo.com/6017235518f8f0c1dffba0620f6d378a

**Version of Mod Pack using:** [VERSION] v1.3.4

**Where did this bug happen:** [Single Player or Server] Multiplayer and Single player

### Additional Information
[Any other information that may be able to help me with the problem] When i launch the game and i join a multiplayer or singleplayer session my character is glitching out i'm not able to walk normal or destroy blocks and my character is going all over the place

**Comment by MJRLegends** [comment]
Plesse update to latest version
