### ISSUE TITLE
Broken Recipe

### ISSUE THREAD

**Issue by Hazmatik** [MJRLegends/Space-Astronomy-2-Feedback-#18]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
Unable to craft the Smart Wrench from RFtools, recipe conflicts with Little Utility Knife from LittleTiles mod.

### Steps to Reproduce Issue
1. Attemp to craft

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]
1.0.9
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Fixed in v1.1.1 Beta thanks for the report

**Comment by MJRLegends** [comment]
Probably will be out Friday

**Comment by Hazmatik** [comment]
Thanks
