### ISSUE TITLE
Server Load Crash

### ISSUE THREAD

**Issue by Holick364** [MJRLegends/Space-Astronomy-2-Feedback-#181]
### ---Issue Report---
YES - check here and online for several solutions. none have help. One popular has been log out and log in. I have tried this several times.

### Description of Issue
On loading server. I get this issue

Connection Lost
Internal Exception: java.lang..nullpointerexception

### Steps to Reproduce Issue
1. Load Twitch profile
2. Multiplayer- select node 1 or 2
3. Logging in.... then soon later with connection lost

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using:** Loaded from twitch today. v1.3.5

**Where did this bug happen:** Server
### Additional Information
I have loaded my RAM to 7,000 on twitch

**Comment by MJRLegends** [comment]
Please contact frozen soul network staff i have nothing to do with these servers
