### ISSUE TITLE
Internal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Bobicus** [MJRLegends/Space-Astronomy-2-Feedback-#182]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Every time I load up Space Astronomy 2 and attempt to log into one of the available frozen soul servers I receive the error message in the title of this post along with "Connection Lost" and I cannot figure out why this is happening. Please help]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [1.3.5]

**Where did this bug happen:** [Server]

### Additional Information
[]

**Comment by MJRLegends** [comment]
I dont own these server sorry please report the issue to them :D

**Comment by MJRLegends** [comment]
Also you need to use v1.3.4

**Comment by Bobicus** [comment]
thanks

**Comment by MJRLegends** [comment]
no problem
