### ISSUE TITLE
Cannot survive on Mercury

### ISSUE THREAD

**Issue by Jamdog** [MJRLegends/Space-Astronomy-2-Feedback-#183]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
I am unable to survive on the surface of Mercury for more than a few seconds, despite wearing a Tier 2 Space Suit, and Tier 3 Thermal Padding, and a Shield Controller.  I die rapidly from Radiation as soon as I set foot on the planet.

### Steps to Reproduce Issue
1. Prepare to go to Mercury
2. Go to Mercury
3. Die, in seconds.

**Crash log/Log (if applicable):** No crash, so no log

**Screenshots (if applicable):** 
Video: https://youtu.be/J1FtjvYvlk0

**Version of Mod Pack using:** v1.3.5

**Where did this bug happen:** Server

### Additional Information
I built a Tier 3 rocket, and went to Mercury wearing the required Tier 1 Space Suit and Tier 3 Thermal Padding.  Before my lander reached the surface, I had taken lots of damage, and died as soon as I stepped out onto the planet surface.

As I had brought the pieces to make a Stargate, I respawned, and quickly broke my gravestone and placed the first 2 blocks of the Stargate, then repeated this death/respawn/build 1-2 Stargate blocks until the Stargate was built, then did /home.  I can now visit Mercury by Stargate at any time, but still die within seconds.  I have since upgraded to Tier 2 Space Suit, but this makes no difference.

I can prolong my life using the Genetics Reborn Dragon Health Crystal, but this makes it very hard to move around because I am constantly twitching from the damage.

**Comment by MJRLegends** [comment]
Please check out the pre launch checklist which is a GC item this will tell you everything you need

**Comment by MJRLegends** [comment]
Your probably missing oxygen tanks and that

**Comment by MJRLegends** [comment]
Checkout https://youtu.be/1EwhN1sLY5o if your still stuck or join my discord https://discord.gg/VEgV7Pk

**Comment by Jamdog** [comment]
I have the feeling you neither read my description, or watched my video.  Your comment:

> Please check out the pre launch checklist which is a GC item this will tell you everything you need

assumes I'm an idiot, when in fact, I said in my description, and showed in my video that I had all the necessary items required for Mercury, and in fact had more, higher-tier items than the checklist requires.

You also suggested: 

> Your probably missing oxygen tanks and that

yet, if you look in my video at 4:15, you will see that I have all this equipped.

The video that you suggested I watch is from Whisperfire, a member of the server I am playing on.  I actually discussed my issue with Whisperfire, and showed her my video, and she actually suggested that I log the issue here.  I also watched her video before going to Mercury in the first place...

**Comment by WhisperFire26** [comment]
MJR, I have access to this multiplayer server and Jam discussed the issue with me before submitting the ticket. I have repeated the steps and found this to be an issue but for some reason on my single player game it works fine.

**Comment by MJRLegends** [comment]
I need your fml-latest-server.log file please

**Comment by MJRLegends** [comment]
@Jamdog i've removed your comment, its rude and not needed. Your video just shows intended features, you need to sleep to wear off the radiation, your video doesnt show thing...

**Comment by MJRLegends** [comment]
Please provide fml-latest-server.log file , and a video showing you sleeping. Also a mod list of any server side things if you have added any extra mods or plugins
