### ISSUE TITLE
Instant Death on Mercury

### ISSUE THREAD

**Issue by DigitalSketch** [MJRLegends/Space-Astronomy-2-Feedback-#184]
---Issue Report---

Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING): [Yes, one closed, but no good solution]

Description of Issue

I have a tier 2 space suit, tier 3 thermal padding, shield controller, parachute, and have the standard frequency module, oxygen mask, oxygen gear and oxygen tanks equipped (all the checklist items)., yet when I step foot on Mercury, I nearly instantly die.  If i didn't have /home or a charged porter, I'd be in a death loop. 

Steps to Reproduce Issue

Put on equipment, go to mercury, not have a good time.

Screenshots (if applicable):
Friend recorded us (himself) going here: https://youtu.be/J1FtjvYvlk0

Version of Mod Pack using: v1.3.5

Where did this bug happen: Server

**Comment by WhisperFire26** [comment]
MJR, I have access to this server and have already repeated the steps and have this same issue on multiplayer.

**Comment by DigitalSketch** [comment]
We did some testing, and it would appear that if your radiation level will never dissipate, and thats whats happening.

**Comment by MJRLegends** [comment]
One issue is enough please
