### ISSUE TITLE
Mekanism Mod beeing uncooperative when breaking their Machines

### ISSUE THREAD

**Issue by tobiyas** [MJRLegends/Space-Astronomy-2-Feedback-#185]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
It seems like Mekanism machines and pipes are disapearing after breaking them without dropping the item. It seems to have about 1/3 chance to drop the item for me. Tested with different Mining utilities (Dissassembler, Tinker's Pickaxe, Power Fist), nothing seemed to have an influence if the item dropped or not. Also tested with a Cardbox. Same result.

### Steps to Reproduce Issue
1. Place down any Mekanism Machine (retested and confirmed with 'Basic Infusing Factory')
2. Destroy the block with any tool (tested with the ones above).
3. No item drop of the Block.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
Can't provide that, since I'm only a Player on that Server.

**Screenshots (if applicable):** 
I did a sequence of screenshots.
[Before placing](https://www.dropbox.com/s/te4kol89pc804x6/after_breaking.png?dl=0)
[After placing](https://www.dropbox.com/s/67vhrc8xuoxpejs/after_place.png?dl=0)
[After breaking](https://www.dropbox.com/s/te4kol89pc804x6/after_breaking.png?dl=0)
[No drops](https://www.dropbox.com/s/vmffu8an08yqeiq/no_drop.png?dl=0)

**Version of Mod Pack using:** 1.3.4

**Where did this bug happen:**  Server: space2-2.frozensoul.co

### Additional Information
Told the Mods on the Server, they told me to open a ticket here.

Detailed information that might be interesting:
- On Overworld
- In OWN claimed area
- No vacuum stuff near, that could suck it up

**Comment by MJRLegends** [comment]
Please contact frozen soul staff

**Comment by MJRLegends** [comment]
This isnt my issue
