### ISSUE TITLE
Ender-Lily causing fps drop

### ISSUE THREAD

**Issue by jasmine2785** [MJRLegends/Space-Astronomy-2-Feedback-#186]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
When Ender-Lily are on ground as a item or in hand FPS goes down to 1 from 60 fps

### Steps to Reproduce Issue
1. get Ender-Lily
2. hold in hand

**Version of Mod Pack using:** 1.3.5

**Where did this bug happen:** Server and single player

### Additional Information
Looks like it was fixed after a update of extra utilizes 
https://github.com/scalda/FoolCraft/issues/854

**Comment by MJRLegends** [comment]
See change log already fixed
