### ISSUE TITLE
"The game crashed whilst initializing game The game crashed whilst initializing game Error: java.lang.OutOfMemoryError: GC overhead limit exceeded"

### ISSUE THREAD

**Issue by Manafinn** [MJRLegends/Space-Astronomy-2-Feedback-#187]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You need to allocate more ram, How Do I Change My Ram Assignment/Usage For Minecraft On Curse/TwitchApp? http://imgur.com/a/MBcw8
