### ISSUE TITLE
Java out of memory error, what do I do to fix it?

### ISSUE THREAD

**Issue by Manafinn** [MJRLegends/Space-Astronomy-2-Feedback-#188]
The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.OutOfMemoryError: GC overhead limit exceeded

I know this isn't the game's fault but I want to know how to fix this problem. PLEASE HELP I WANT TO PLAY MODPACK!

**Comment by MJRLegends** [comment]
You need to allocate more ram, How Do I Change My Ram Assignment/Usage For Minecraft On Curse/TwitchApp? http://imgur.com/a/MBcw8
