### ISSUE TITLE
Texture glitch

### ISSUE THREAD

**Issue by yoloarf** [MJRLegends/Space-Astronomy-2-Feedback-#190]
I don't actually know what happend but it seems like this is a texture glitch i just used twitch downloaded the latest version (1.3.6) and clicked play this happend
![schermafbeelding 2017-11-30 om 19 35 13](https://user-images.githubusercontent.com/32961346/33448367-2323b49e-d606-11e7-9a7b-c118e919d7c4.png)

**Comment by MJRLegends** [comment]
Are you using optifine

**Comment by MJRLegends** [comment]
Or are you on a mac?

**Comment by yoloarf** [comment]
im on mac indeed

**Comment by MJRLegends** [comment]
Yeah this is a vanilla mc problem with macs sorry im unable to change anything from my side with it

**Comment by yoloarf** [comment]
so i can't play

**Comment by MJRLegends** [comment]
Its a bug with vanilla mc so sorry but i cant do anything from the mod pack side of things

**Comment by yoloarf** [comment]
f*** mac nothing works with modpacks

**Comment by MJRLegends** [comment]
Yeah macs are not great for gaming

**Comment by MJRLegends** [comment]
But ive seen this befoee mac have a problem with render stuff see https://github.com/MJRLegends/Space-Astronomy-Feedback-/search?q=mac&type=Issues&utf8=✓ this is from my first mod pack
