### ISSUE TITLE
updated server crashes

### ISSUE THREAD

**Issue by Jacketedcorn** [MJRLegends/Space-Astronomy-2-Feedback-#191]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Server Crashes

### Steps to Reproduce Issue
1. I just updated the server

https://pastebin.com/Lq8ug9aR

> *How do I locate a crash log on Minecraft on Curse/Twitch? see* N/A

**Screenshots (if applicable):** 

**Version of Mod Pack using:** Newest

**Where did this bug happen:**  Server

### Additional Information
Loading the second jar (not the forge one) the server starts up

**Comment by MJRLegends** [comment]
Your missing some files please reupload them all

**Comment by Jacketedcorn** [comment]
There are no crash files on the server. Not that I can find at least.

**Comment by MJRLegends** [comment]
You need to reupload the server files you missing some of them

**Comment by Jacketedcorn** [comment]
Oh alright, Ill do that.

**Comment by Jacketedcorn** [comment]
The issue is still occurring, should I just download a backup of the world and delete all the files?

**Comment by MJRLegends** [comment]
Are you not using the latest pack version?

**Comment by Jacketedcorn** [comment]
I'am updated the server with the newest version and it wouldn't work. I just freshly installed the server and it doesn't work.

**Comment by Jacketedcorn** [comment]
https://pastebin.com/bnXiPsJF

**Comment by MJRLegends** [comment]
That last crash log says 

```
> [01:55:47] [Server thread/ERROR] [FML]: The mod deepresonance (DeepResonance) requires mods [compatlayer] to be available
> [01:55:47] [Server thread/ERROR] [FML]: Mod deepresonance (DeepResonance) requires [compatlayer@[0.2.6,)]
> [01:55:47] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.MissingModsException: Mod deepresonance (DeepResonance) requires [compatlayer@[0.2.6,)]
Missing Mods:
compatlayer : [0.2.6,)
```

Your missing mods

**Comment by Jacketedcorn** [comment]
What I'm trying to say is I just uploaded the folder I downloaded. I re downloaded the server folder from the site and I still get an error.

**Comment by Jacketedcorn** [comment]
Well I got it to work but alot of the blocks changed
