### ISSUE TITLE
RF Tools Crash

### ISSUE THREAD

**Issue by RussianSanity** [MJRLegends/Space-Astronomy-2-Feedback-#192]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Crash when starting the server

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.] https://pastebin.com/KThReRu2

**Screenshots (if applicable):** 

**Version of Mod Pack using:** 1.3.6

**Where did this bug happen:** Server with spongeforge

**Comment by MJRLegends** [comment]
https://github.com/McJty/RFTools/issues/1466

**Comment by josephcsible** [comment]
FYI, a fix has been implemented; see my last comment on the linked bug.

**Comment by MJRLegends** [comment]
Nice thanks
