### ISSUE TITLE
insta crash

### ISSUE THREAD

**Issue by greenwolfninja** [MJRLegends/Space-Astronomy-2-Feedback-#194]
### ---Issue Report---
yes

### Description of Issue
the server crashes as soon as it starts

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/gvJ97JFW

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]
latest version

happened on a server

### Additional Information
not sure if this is a pack issue or a server issue

**Comment by MJRLegends** [comment]
Please update as it seems your using a old version of the mod pack
