### ISSUE TITLE
Can't Dig anything with tools

### ISSUE THREAD

**Issue by ErTangia** [MJRLegends/Space-Astronomy-2-Feedback-#195]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING): YES

### Description of Issue
In the server people cant dig stone with pickaxe or sanything else with any kind of instruments except for the some modded pickaxe that can't anyway dig the stone...

### Steps to Reproduce Issue
1. login in the server:www.ceneridiatlantis.it:30001
2. try to do something

**Crash log/Log (if applicable):

**Screenshots (if applicable):** 

**Version of Mod Pack using:1.36

**Where did this bug happen:** Server 1.36 www.ceneridiatlantis.it

### Additional Information
have seen during the client gameloading that some mods miss from the server files.

PS. thank you for your help

**Comment by MJRLegends** [comment]
You cant use vanilla tools see the tool tip on them

**Comment by ErTangia** [comment]
Ok i tried but anyway i can't use it on the Stone kind elements and stillicidio doesnt, it is possibile depends in domenica server permissions?

**Comment by ErTangia** [comment]
As soon i can i will try with the different mods pickaxe

**Comment by MJRLegends** [comment]
Not sure sorry but it works on with single player and forge servers and sponge forge servers so it must me something specific with your server. Sorry
