### ISSUE TITLE
IC2 Wrenches

### ISSUE THREAD

**Issue by MalkD13** [MJRLegends/Space-Astronomy-2-Feedback-#196]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
I just started working with the IC2 mod and none of the wrenches work for picking up the machines. This makes moving MFE's impossible.

### Steps to Reproduce Issue
1. Place an IC2 machine.
2. Try to right click or shift+right click with any IC2 wrench

**Version of Mod Pack using:** [1.3.6]

**Where did this bug happen:** [Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by Eppiox** [comment]
Tested on 1.3.6 on a stock private server(not hosted by me), the IC2 wrench 4521 is the only one that works for me with ic2 machines- also worked without sneak+right click, the sneak reverses block rotation.
Also the electric wrench 4531 worked.

**Comment by MJRLegends** [comment]
Ok i will count this as not a bug
