### ISSUE TITLE
Some Chisel blocks play the spooky dungeon noise for other players when placed/walked on

### ISSUE THREAD

**Issue by Eppiox** [MJRLegends/Space-Astronomy-2-Feedback-#199]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
The Chisel mod: The Factory block when placed or walked on (same noise) will make the spooky dungeon noise for other players but the normal noise for the placing player.  
Seems to be isolated to the sound clip that the 'Dotted Rusty Plate' uses (Which is shared by other blocks)

### Steps to Reproduce Issue
1. Craft a Factory block from the Chisel mod- try Dotted Rusty Plate- that sound is used for many other chisel blocks too
2. Place the block near another player
3. Get them to report if it made the spooky dungeon noise- can be spammed for maximum spooky dungeon noise triggering 

*No crash log
**Screenshots (if applicable):** 
**Version of Mod Pack using:** [VERSION]
1.3.6
**Where did this bug happen:** [Single Player or Server]
Server only

### Additional Information
[Any other information that may be able to help me with the problem]
Chisel mod seems to be missing armor blocks, radiation warning blocks and a bunch of other blocks that the Chisel mod normally has?

**Comment by MJRLegends** [comment]
I cant see how they is a bug?

**Comment by Eppiox** [comment]
It was intentional the play the wrong sound for block placing? Weird.   - Or do you mean it's not a bug with the pack but a bug with the chisel mod?

**Comment by R0JU** [comment]
I was looking for this bug on here as well.
It is definitely a bug.
If you place that item it sounds normal for you
If you walk on it it sounds normal to you
but,
For every single other person on the server it spams the *wrong* sound - in this case the minecraft 'creepy noises' which go on for quite a long time in some cases...

Not all factory blocks make this noise - its a specific subset of the chisel blocks that use the sound 'dotted rusty plate' uses when playing placing or walking surface sounds to other players on a server.

**Comment by MJRLegends** [comment]
Please make a video showing this as i cant reproduce it

**Comment by R0JU** [comment]
hey just an fyi - the update resolved this issue so all good now (b'.')b

**Comment by MJRLegends** [comment]
Nice
