### ISSUE TITLE
Audio System Crash - IC2

### ISSUE THREAD

**Issue by R0JU** [MJRLegends/Space-Astronomy-2-Feedback-#200]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
After some time playing the audio stops and you get an brief message that there was a problem with the audio system and that it was restarting then minecraft crashes to desktop. 
Crash log appears to indicate IC2 as the culprit.
I don't know if all IC2 machines would have the same effect, but I know on this crash for sure only the recycler was running.

### Steps to Reproduce Issue
1. place running recycler from IC2 with a few overclockers in it to speed it up
2. eventually the audio system errors out and ctd

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/WYfyFKma

**Screenshots (if applicable):** 
n/a
**Version of Mod Pack using:** [VERSION]
1.3.6
**Where did this bug happen:** [Single Player or Server]
Server
### Additional Information
Increasing the ram available for the pack up from 6gb to 8gb made it take longer to crash, but it still crashed. 
This was not an issue before we had the IC2 machines running.

**Comment by MJRLegends** [comment]
Have you been able to reproduce this more than once?

**Comment by MJRLegends** [comment]
Ref for MJRLegends: https://bt.industrial-craft.net/view.php?id=2276

**Comment by R0JU** [comment]
Yeah I've had multiple crashes from this bug over the past week. The log I uploaded was just the most recent one.

**Comment by MJRLegends** [comment]
I've added this to the known issues over at #99
