### ISSUE TITLE
Need Some Help Here Pls

### ISSUE THREAD

**Issue by darklordor** [MJRLegends/Space-Astronomy-2-Feedback-#202]
Hi, i want to play this modpack, but i recieve an error every  time i try to inicializate minecraft, 
here is my crash report: https://pastebin.com/D7nFkGHv
Any help is welcomed :D

**Comment by MJRLegends** [comment]
1. java.lang.OutOfMemoryError: Initializing game
2. Your out of memory as you havent assigned more
3. Please fill out the template when making future posts

How Do I Change My Ram Assignment/Usage For Minecraft On Curse/TwitchApp? http://imgur.com/a/MBcw8
