### ISSUE TITLE
Similar to the HardcoreQuesting bug but not caused by HardcoreQuesting?

### ISSUE THREAD

**Issue by yazzledore** [MJRLegends/Space-Astronomy-2-Feedback-#203]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

Yes.  I am not very competent at this, and can't tell if it's the same issue as this one or not (https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/934).  The part about "Description: Exception in server tick loop" is the same, as well as the nature of the crash, but this: "java.lang.AbstractMethodError" is different, and not specifically mentioned in that thread; hardcore questing isn’t mentioned in my crash log, but again, the errors seem similar in circumstances and effect.

### Description of Issue
The world crashes on loading; it brown screens for about 20 seconds when building world and then exits to the java launcher.  The description is very similar to the posted one, and occurs under the same circumstances.  Making a new world works just fine, just not loading the old one.

### Steps to Reproduce Issue
1. Try to load saved game.
2. Fail.

**Crash log/Log (if applicable):** 
https://pastebin.com/GrcTBMxu

**Screenshots (if applicable):** 

**Version of Mod Pack using:** 1.3.6

**Where did this bug happen:** 
I'm playing a single player game, but it occasionally says "server backup in progress," and lets me do all that claimed chunk stuff, so I'm not sure what that means (did it set up a server for just me on my computer or something?).  I imagine this might be important to mention because a bunch of the bugs have to do with "minecraft.server” but I think that’s how it works for everyone in this modpack?

### Additional Information
Again, not very competent at this, so I apologize for my inevitable missteps.  I think this is all relevant information.

I'm using the twitch launcher which I am pretty sure is the same as the FTB launcher.  The bug started occurring immediately after I installed the newest update.

I have tried two solutions: the first was *attempting* Solution 1 from the thread posted above.  However, I'm on a mac :/ and I cannot figure out where to find that file. (Googling says those folders in the AppStore folder on PC's are usually in Application Support on the mac, but I couldn't find it in there.  Searching doesn't work because my library folder is hidden, basically.)  If this is the same issue (very sorry if it is), could you please tell me where that file would be located on my mac?  I have invested a lot of time into this and Option 2 is not an option.

The second solution I tried was reverting to the 1.3.5 version, which said something about a lot of missing blocks and allowed me to load my world, but replaced most of my blocks with other ones and completely destroyed my base.  Refined storage system is corrupted, etc.  Might as well just start a new game, so not really a solution.  Is there a solution to this second problem?  That would otherwise seem a reasonable workaround if fixes are expected in the future.

I also tried the basic stuff: uninstalling and reinstalling the modpack, making sure I have enough RAM allocated (tried everything from 4 to 10 gigs), and making sure Java is updated.  

Creating a new world is just fine.  Backups don't load either.

**Comment by MJRLegends** [comment]
Hqm isnt in this pack?

**Comment by MJRLegends** [comment]
Your issue is #192

**Comment by yazzledore** [comment]
Sorry for missing that.  I thought it might be, but I haven't placed down any OpenComputers adapters.  Also, it said the fix was updating to the newest version, but my problem started when I did that, so I figured it wasn't the same issue.  Is there another fix for that?

**Comment by MJRLegends** [comment]
Update open computers and rf tools or use 1.3.5 of the mod pack

**Comment by yazzledore** [comment]
I did try the 1.3.5 thing but that just destroyed everything (mentioned above).  Thank you, I will try to figure out how to update the above packs.  You get back to this thread remarkably quickly; much appreciated!

**Comment by yazzledore** [comment]
Doing this (I clicked the ellipsis in the upper right corner of the profile screen to unlock it, and then clicked on rftools in the list and opencomputers and updated them to the newest version) sort of worked, but gave me the problems above that I got from updating to 1.3.5, namely, this:
<img width="1680" alt="screen shot 2017-12-18 at 10 13 49 pm" src="https://user-images.githubusercontent.com/34671020/34143271-c3674180-e440-11e7-9635-7d2937ad6c41.png">
<img width="1680" alt="screen shot 2017-12-18 at 10 13 39 pm" src="https://user-images.githubusercontent.com/34671020/34143272-c3a9bb46-e440-11e7-86fa-59ecf9bf7a87.png">

Is there anything I can do about this?  It's an enormous disaster.  Thank you so much for your patience!

**Comment by MJRLegends** [comment]
Im unable to help with that sorry if blocks have changed yo another one then thats world corruption and a backup restore will be needed

**Comment by MJRLegends** [comment]
Or its a visual thing as mac can have them a lot

**Comment by yazzledore** [comment]
My oldest backup still works, so working through them to find the newest one, but this would appear to indicate that the problem is solved!  Thank you so much again for all your patience and quick responses!  Your modpack is amazing, and I am so happy I get to keep playing it :)
