### ISSUE TITLE
Enchanting tiny progression battle axe in anvil = crash

### ISSUE THREAD

**Issue by Eppiox** [MJRLegends/Space-Astronomy-2-Feedback-#204]
### ---Issue Report---
Yes

### Description of Issue
Attempting to Enchant or copy a battleaxe from tiny progressions in a vanilla anvil will crash the client to desktop

### Steps to Reproduce Issue
1 Place a battleaxe in an anvil
2 Place a book- or another axe in the anvil
3 Crash to desktop

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You need to fill out all information and include the crash log. Will reopen when done so. Also thanks for the report
