### ISSUE TITLE
Lab Blender Sulfur-bearing Compost Recipe Not Working

### ISSUE THREAD

**Issue by ttrilobyte** [MJRLegends/Space-Astronomy-2-Feedback-#205]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
JEI shows a recipe for sulfur-bearing compost that uses Mekanism Sulfur Dust in the Rockhounding Lab Blender. However, when you put the sulfur in the blender it doesn't run, as if the recipe does not exist.

### Steps to Reproduce Issue
1. Place a Lab Blender and give it fuel
2. Press the activate button and put a stack of mekanism sulfur dust in slot 1. Nothing happens
3. Instead put industrial craft 2 sulfur dust in. The blender begins processing

**Version of Mod Pack using:** v1.3.6

**Where did this bug happen:** Single Player

### Additional Information
The sulfur dust can be placed in the machine, so it would seem that a recipe exists, but it does not run (the gear progress bar does not change, no energy is consumed and no results are produced). JEI suggests that both ic2 and mekanism versions will work (there are separate recipe entries for the two, but with identical ratios of 3 sulfur to 8 compost). It can be worked around by crafting the mekanism dust in a 2x2 into gunpowder, then putting it through an ic2 extractor to get ic2 sulfur dust.

Edit: spelling

**Comment by MJRLegends** [comment]
You just caught me in time, was just about to update the pack. Will check this now before the update
