### ISSUE TITLE
pls help crashed

### ISSUE THREAD

**Issue by nathanman213** [MJRLegends/Space-Astronomy-2-Feedback-#206]
Dear Space Astronamy 2 Maker/Makers My Game Crashed And This is it please help also i installed optifine and veinminer for fun dont know if that has anything to do with it ---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.119.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.1.jar)
  CreativePatchingLoader (CreativeCore v1.7.3 mc1.10.2.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  literalascension (literalascension-1.10.2-1.0.2.2.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.2-anarchy.jar)
  SoundUnpack (OpenSecurity-MC1.10.2-1.0-35.jar)
  IC2core (industrialcraft-2-2.6.252-ex110.jar)
  OpenModsCorePlugin (OpenModsLib-1.10.2-0.11.3.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.4.7.2.jar)
  Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.6.142-universal.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.11.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  AstralCore (astralsorcery-1.4.5.jar)
  llibrary (llibrary-1.7.7-1.10.2.jar)
  LittleLatePatchingLoader (LittleTilesCore-v1.0.0.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  LittlePatchingLoader (LittleTiles v1.4.12 mc1.10.2.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.7.1.150.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.2.3.26.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 12/26/17 3:12 PM
Description: Initializing game

java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.String.<init>(String.java:166)
	at java.lang.String.copyValueOf(String.java:3047)
	at com.google.common.base.CharMatcher.showCharacter(CharMatcher.java:235)
	at com.google.common.base.CharMatcher.anyOf(CharMatcher.java:498)
	at net.minecraftforge.fml.client.FMLClientHandler.stripSpecialChars(FMLClientHandler.java:1045)
	at net.minecraftforge.fml.common.FMLCommonHandler.stripSpecialChars(FMLCommonHandler.java:743)
	at net.minecraftforge.fml.common.ProgressManager$ProgressBar.step(ProgressManager.java:127)
	at pl.asie.foamfix.coremod.injections.client.ModelLoaderParallelHelper.lambda$bake$

**Comment by MJRLegends** [comment]
java.lang.OutOfMemoryError: GC overhead limit exceeded
