### ISSUE TITLE
Flags un-placeable and green in SP and server. 

### ISSUE THREAD

**Issue by Dynastysc2** [MJRLegends/Space-Astronomy-2-Feedback-#207]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. Craft or Spawn in Flag
2. Try and Place or look in third person.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 
https://gyazo.com/9cc6d329b09b0b5a6ddc80e493296f92
**Version of Mod Pack using:** [VERSION]
Lastest version to date: 28th/12/2017
**Where did this bug happen:** [Single Player or Server]
Both.
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
For some reason it seems you have to hold down right click while looking at where you want to place it and then it places when you have let go after holding down right click for at least 5 seconds

**Comment by MJRLegends** [comment]
See https://gyazo.com/71e6070d26c74a8447d10db36270022f

**Comment by MJRLegends** [comment]
Also i believe this is how its ment to work as it says in there wiki that holding down the right click is the way https://wiki.micdoodle8.com/wiki/Flag
