### ISSUE TITLE
Can't Configure or find anny villages!

### ISSUE THREAD

**Issue by BeefyGames** [MJRLegends/Space-Astronomy-2-Feedback-#208]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

Yes I have checked this

### Description of Issue
I did download the modpack, Looked for villages... Can't find villages. been looking for hours. No config files for changing stuff inside the biome o plenty config folder. This issue may be diffrent for others as not everyone has village issues...

### Steps to Reproduce Issue
1. Download the modpack
2. Look for villages
3. Check the config files for biome o plenty.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [newest]

**Where did this bug happen:** [Single Player]

### Additional Information
Just that maybe let biome o plenty have their config files as in 1.7 version would be the best!

**Comment by MJRLegends** [comment]
No they spawn i have seen them

**Comment by MJRLegends** [comment]
All newest isnt a mod pack version

**Comment by BeefyGames** [comment]
Yes but like i did write this can be random for each user. i have had this issue before. but then i could change it in the biome o plenty config. And now i can't do that. How the heck should i make them spawn if i can't configure them to spawn.

**Comment by MJRLegends** [comment]
You dont configure them, they spawn automatically

**Comment by BeefyGames** [comment]
I can't find anny download for the config files online either. only decripsion how to find them. Also with "newest" its obviussly the newest version!

No villages don't spawn at all! i have been changing it in the cofig files always! this issue have been a issue for litterly everey modpack i have played! including the space astronomy for 1.7 version but then i could change it in the cofigs

**Comment by BeefyGames** [comment]
Really nice helping !!!! 
How adult of you!

**Comment by MJRLegends** [comment]
Villages are turned on for certain biomes, yes, they spawn automatically you dont need to change or download or modify anything just download the packs play them

**Comment by MJRLegends** [comment]
![2018-01-02_14 43 55](https://user-images.githubusercontent.com/8526321/34487244-64a80080-efcb-11e7-9ce0-b31fd78c9158.png)
They defo spawn, and im am helping you no need to get annoyed. Im am here to help but i cant fix something that seems to work. You must just be getting unlucky with the R&G aspect. Villages are not extremely common too

**Comment by MJRLegends** [comment]
Villages will only spawn in biomes registered plains i believe so having biomes o plenty will make them more rare. You could try the mining world as i think they spawn there too

**Comment by BeefyGames** [comment]
Yes! obviusly there is the issue! with biome o plenty its just that many mods that it takes hours upon hours to find villages if you're not lucky. That is why i want to make the villages spawn often. and therefore change it in the config file. I have done this before they removed the file in 1.8 and i have no idea how to even find the correct file now anny more.

**Comment by BeefyGames** [comment]
So how do i do that?

**Comment by MJRLegends** [comment]
Sorry but i wont be taking any action as they work as intended. If you have any more issues that isn't the luck of spawning of villages please make a new issue
