### ISSUE TITLE
No Dimensions are generating

### ISSUE THREAD

**Issue by Eragon20103** [MJRLegends/Space-Astronomy-2-Feedback-#210]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
I cant get any Dimension except the Overworld to load on a Server.
In Singleplayer Everything works fine. 

### Steps to Reproduce Issue
Dont know any step ^^ It just wont load

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> No crashlog scince it does not crash the game

**Screenshots (if applicable):** 
Mining Dimension: https://puu.sh/ySNqW/a9d906d7ac.png
Nether: https://puu.sh/ySNr2/f3669f63e7.png
Nether: https://puu.sh/ySNr4/40c2547c33.png

**Version of Mod Pack using:** 1.3.8

**Where did this bug happen:** Server

### Additional Information
The first time it happend it was on the Mining Dimension so i thought its this mod that causes the Problem so i installed a older version (Aroma1997s-Dimensional-World-1.9.4-1.2.0.6) instead of (**1.2.0.7) but no look. Then i wantet to test a Dimensions mod (SimpleDimensions-MC1.10-1.3) where i can create my own "mining world" then it happend with the new dimension aswell, no generation, then i looked into the Nether and Overworld, same problem as seen in the Screenshots. I hope you have a solution :/ cause i am out of ideas. And please forgive me my bad english ^^

**Comment by MJRLegends** [comment]
This isnt anything mod pack related sorry its something with your server

**Comment by Eragon20103** [comment]
ok :/ ty tho :)

**Comment by Eragon20103** [comment]
i found a little fix IF someone is encountering it... it has something to do with the hosting site Nitrado ( every other pack worked fine) so i host a server on my computer and it worked. So i can finally enjoy your awesome modpack :)

**Comment by MJRLegends** [comment]
Oh rip for them haha yeah, im sorry i couldn't help but i 100% know that it wasnt a pack issue for sure. Hope you enjoy the pack
