### ISSUE TITLE
Loading crash

### ISSUE THREAD

**Issue by Occhioverde** [MJRLegends/Space-Astronomy-2-Feedback-#211]
Good morning.
When loading the modpack SpaceAstronomy, the loading stops when a Chisel model is loaded (Screenshot: 
![crash space astronomy 2](https://user-images.githubusercontent.com/18429412/34567795-f969f2f2-f163-11e7-8a99-3775683e8354.jpg)).

Minecraft version: 1.10.2
SpaceAstronomy version: 1.3.8
Windows version: 10 (Fall creators update) 64x

**Comment by MJRLegends** [comment]
You need to make sure you use 5+ ram also you have removed the issue template when it says dont. Please try the ram increase if not update this issue using the actual temeplate

**Comment by MJRLegends** [comment]
*5Gb+
