### ISSUE TITLE
Journeymap buggy and crashed

### ISSUE THREAD

**Issue by veiko45** [MJRLegends/Space-Astronomy-2-Feedback-#214]
### Description of Issue
Journeymap is being wierd by not displaying all the information in the overworld, but working everywhere else. Crashed when trying to make a new waypoint on the Mars

### Steps to Reproduce Issue
1. Travel to Mars with a Stargate
2. Try to make a new waypoint

**Crash log/Log (if applicable):**
https://pastebin.com/UvA221Ym

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.3.9

**Where did this bug happen:** [Single Player or Server]
SSP

**Comment by MJRLegends** [comment]
See https://github.com/TeamJM/journeymap/issues/16 & https://github.com/TeamJM/journeymap/issues/14

**Comment by MJRLegends** [comment]
Update v1.4.0 is about to be released fixing this issue
