### ISSUE TITLE
Tesselating Block Model Crashing

### ISSUE THREAD

**Issue by yazzledore** [MJRLegends/Space-Astronomy-2-Feedback-#215]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**
Yes; I couldn't find anything related to this modpack.  There seemed to be a few issues with it in other modpacks, but it was usually attributable to Optifine, which I am not using (otherwise no solutions were offered).

### Description of Issue
A few seconds of dirt-textured screen, then crash to launcher.

### Steps to Reproduce Issue
It just seems to happen randomly, but it may only be when the camera is moving (I don't think I've ever seen it happen while in the inventory of a crafting table, chest, etc.).  I think it may have started when I updated OpenComputers and RFTools to the latest versions to fix another issue, but honestly not sure.

**Crash log/Log (if applicable):**
https://pastebin.com/tSJrdthE

**Screenshots (if applicable):** 
N/A

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.3.9

**Where did this bug happen:** [Single Player or Server]
Single Player

### Additional Information
It happens fairly frequently (every 1-3 hours) is getting worse.  Been noticing pretty awful lag recently too, not sure if that's related.

**Comment by MJRLegends** [comment]
I think this is a mac only issue

**Comment by MJRLegends** [comment]
Seems to happen on windows too as i had the crash a few days ago too
