### ISSUE TITLE
JourneyMap bugs

### ISSUE THREAD

**Issue by AlexejheroYTB** [MJRLegends/Space-Astronomy-2-Feedback-#216]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
JourneyMap is very buggy, I cannot disable waypoints and I cannot teleport to them. If I try to teleport, it sais unknown command. (Also, they don't have colors)

### Steps to Reproduce Issue
1. Try to disable an waypoint
2. Try to teleport to an waypoint

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 
![2018-01-14_17 50 52](https://user-images.githubusercontent.com/32238504/34917803-a9c1388a-f953-11e7-8c41-8cca6ffbb2ca.png)
![2018-01-14_17 53 11](https://user-images.githubusercontent.com/32238504/34917818-d1f07a96-f953-11e7-9f83-7de76e201429.png)

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.3.9
**Where did this bug happen:** [Single Player or Server]
On a server I use for playing singe player
### Additional Information
None

**Comment by MJRLegends** [comment]
Already posted in #214

**Comment by MJRLegends** [comment]
Update v1.4.0 is about to be released fixing this issue
