### ISSUE TITLE
File mix-up

### ISSUE THREAD

**Issue by Sambo3975** [MJRLegends/Space-Astronomy-2-Feedback-#217]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
[The client download contains the server files, and the server download contains the client files and the server jar files]

### Steps to Reproduce Issue
1. [Download the files]
2. [You'll notice that they're wrong]

**Crash log/Log (if applicable):** [N/A]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.4.0]

**Where did this bug happen:** [Single Player AND Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
This cant be possible, Which launcher are you on?

**Comment by MJRLegends** [comment]
See on how to get either one
How Do I Install Space Astronomy 1 & 2 On The New Twitch App? http://imgur.com/a/CYxre
How Do I Download The Server Files For Space Astronomy 2? http://imgur.com/a/7WgaK
