### ISSUE TITLE
Can not convert immersive engineering lead nugget to ingots

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-2-Feedback-#219]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
can not convert immersive engineering lead nugget to ingots
lead nugget made from poor lead in tinker smeltery

### Steps to Reproduce Issue
1. Place in a crafting grid, do not show ingot

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 
https://imgur.com/a/XztML

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.4.0]
**Where did this bug happen:** [Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Thanks will be fixed in the next update
