### ISSUE TITLE
Space Astro 2 Crashes when loading at RFTools.

### ISSUE THREAD

**Issue by lonesomegaming** [MJRLegends/Space-Astronomy-2-Feedback-#22]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**
Yes

### Description of Issue
When loading the pack I get to step 4/7 (Initializing mods Phase 2) and when it gets to the point of loading RFTools (154/178) it stops loading and I get the error "Java(TM) Platform SE binary has stopped working" that is the only help windows gives me with this issue. 

### Steps to Reproduce Issue
1. [First step]
Hit play in the Curse/Twitch client.
2. [Second step]
Hit play in the Minecraft launcher.

**Crash log/Log (if applicable):** 
https://pastebin.com/8bC7fETS
This is all the information from the latest.log file within the pack folder.

**Version of Mod Pack using:** 
v1.1.0 - Beta

### Additional Information
One thing I don't understand is that a couple days ago I was able to play the pack just fine, and then yesterday (on the same version of the pack) the game threw this problem at me. Now in between both times of playing the pack I had installed more RAM into my system, which I removed to check if that was the issue. Unfortunately it was not the issue, and now I am stuck with what to do. I do also have two other mods installed additionally in the pack (Tails and Optifine). Both of which I removed and regardless of whether or not the additional mods were in the pack it seemed to crash at RFTools. However, I did remove RFTools and RFToolsctrl, which solved the problem right away. I figured I would report this to see what the cause was, as I myself am not very good at looking through the logs.

Thank you in advance for any help.

**Comment by MJRLegends** [comment]
@lonesomegaming Your crash log link doesnt show a crash log only the 3/4 of a log file, please upload just the crash log

**Comment by MJRLegends** [comment]
Also please try v1.1.1 Beta

**Comment by lonesomegaming** [comment]
I will try to load v1.1.1 Beta. Also I do apologize, but the log that I have on paste bin is all that I can find within the pack folder that shows anything related to the issue. There is no crash-reports folder within the pack directory.

**Comment by lonesomegaming** [comment]
I tried launching v1.1.1 Beta, and encountered the same problem. Minecraft just stopped loading after it got to RFTools and windows popped up with "Java(TM) Platform SE Binary has stopped working".  And then the Minecraft launcher reappeared saying "Game Crash". Same as with v1.1.0

**Comment by MJRLegends** [comment]
Does any mod pack work for you?

**Comment by MJRLegends** [comment]
like with RFTools in?

**Comment by MJRLegends** [comment]
IF not please delete SA2 and reinstall it

**Comment by lonesomegaming** [comment]
I don't actually know. I'm going to try to load another pack with RFTools in it and if it loads, I will delete and reinstall SA2. My apologies for not thinking about that prior to posting this.

**Comment by lonesomegaming** [comment]
So I did just try another pack a few minutes ago (with RFTools in it) and it did not launch. I do not know exactly what would be causing this, but sorry for not checking that prior to opening this thread.

**Comment by MJRLegends** [comment]
Ok, please contact the RF Tools developer or curse support and explained that its any mod pack with RF Tools as it seems something else to going on, sorry but i cant do anything from my side to help out :D
