### ISSUE TITLE
ExtraPlanets battery is craft as charged and can't craft the Massive battery

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-2-Feedback-#220]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
ExtraPlanets battery is craft as charged and can't craft the Massive battery

### Steps to Reproduce Issue
1. See screenshots

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 
https://imgur.com/a/0Fl4h

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.4.0]

**Where did this bug happen:** [Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You can still craft it, you will just have to drain the batteries first, i will fix this though but its still possible to craft
