### ISSUE TITLE
Error While downloading

### ISSUE THREAD

**Issue by F4CE4** [MJRLegends/Space-Astronomy-2-Feedback-#221]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
[Description of the issue]

failed to download: https://addones.cursecdnc.com/files/2394/395/BetterBuilderWands-1.10.2-0.11.1.220+f8232fe.jar

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player or Server]

On the twitch app while trying to download Space Astronomy 2

### Additional Information
I am not the only one with this problem I had 6 friends all try and download this mod pack and they all receive the same issue

**Comment by MJRLegends** [comment]
Its not a mod pack issue, please check out https://support.curse.com/hc/en-us or make a ticket for the Twitch/Curse Staff over at https://support.curse.com/hc/en-us/requests/new

**Comment by MJRLegends** [comment]
Also see https://twitter.com/CurseForge/status/955610246185193472

**Comment by F4CE4** [comment]
Thank you sorry for that

**Comment by MJRLegends** [comment]
No problem, also https://twitter.com/CurseForge/status/955622025174966272
