### ISSUE TITLE
Slime Ore giving Slime Ball without texture

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-2-Feedback-#223]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
when mining slime ore on saturn it give slime ball without texture

### Steps to Reproduce Issue
1. Mine a slime ore
2. Gives slime ball without texture

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 
https://imgur.com/a/VjEp5
**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.4.0]

**Where did this bug happen:** [Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Will be fixed two updates time so v1.4.2

**Comment by MJRLegends** [comment]
Due to issue with updating the pack due to Twitch app not working correctly this will make the v1.4.1 update
