### ISSUE TITLE
Breaking blocks with tools turns them into ghost blocks

### ISSUE THREAD

**Issue by Sambo3975** [MJRLegends/Space-Astronomy-2-Feedback-#224]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Breaking blocks with anything other than my fists turns them into ghost blocks. This started happening when I updated my server earlier today.

### Steps to Reproduce Issue
1. Created a world in 1.4.0
2. Updated server and client to 1.4.1
3. Tried to break a block with a tool

**Crash log/Log (if applicable):** n/a
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.4.1

**Where did this bug happen:** Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Its due to desync so its either a connection issue with your server or tps lag see https://minecraft.gamepedia.com/Tutorials/Ghost_blocks

This wouldnt be a mod pack issue sorry
