### ISSUE TITLE
UNABLE TO MINE OR CRAFT MINING TOOLS - V1.4.1

### ISSUE THREAD

**Issue by jeepspert** [MJRLegends/Space-Astronomy-2-Feedback-#225]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
YES

### Description of Issue
[Description of the issue]
a. UNABLE TO BREAK BLOCKS WITH STANDARD PICK AXES I.E.WOOD, STONE IRON, AND SO ON. "AOIT WORKS FINE"
b. WHEN USING CREATIVE MODE ONLY - THE SEARCH FUNCTION IS VERY GLITCHY, OFTER REVERTING TO ALL ITEMS AND RESETIN GTO TO THE TOP EVERY TIME THE SCROLL WHEEL STOPS

### Steps to Reproduce Issue
1. [First step]
TRIED TO CRAFT AND USE THE PICK AXE
2. [Second step]
SWITCHED TO CREATIVE TO ACQUIRE AN PICK AXE, SWITCHED BACK AND STILL NO JOY.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
NONE

**Screenshots (if applicable):** 
NONE

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
V1.4.1

**Where did this bug happen:** [Single Player or Server]
SINGLE PLAYER

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Thanks for the bug report 

The fact its all in caps is rude.

Your issue is you have not taken a look at the tool tips on them or even looked at the recipes in jei

**Comment by jeepspert** [comment]
sorry about the all caps, i thought it would stand out better. i looked at both, still not sure whats going wrong. im going to perform a fresh install of the mod and see what happens.

**Comment by jeepspert** [comment]
i see mow, all vanilla mining tools have been limited to craft only as long as you don't use vanilla recopies.
thanks
