### ISSUE TITLE
Huge poor ore spawns

### ISSUE THREAD

**Issue by RedBlockFilms** [MJRLegends/Space-Astronomy-2-Feedback-#226]
### ---Issue Report---

Have you checked Open/Closed Issues: Yes

### Description of Issue
It seems that huge veins of poor iron and regular iron ore spawn
### Steps to Reproduce Issue
1. Find poor iron ore
2. Vein mine

Screenshots:
https://imgur.com/a/1J0jG

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** v1.4.1

**Where did this bug happen:** Single player

### Additional Information
Maybe a railcraft bug?

**Comment by MJRLegends** [comment]
Im unable to reproduce this and poor ore shouldn't be spawning the overworld anyways, are you in the mining world or deep dark?

**Comment by RedBlockFilms** [comment]
I am in the overworld, grassland biome. I've so far gotten 2786 poor iron ore, 745 regular iron ore, 114 poor nickel ore, and 23 nickel ore. This does not include the other ores that have spawned inside.

**Comment by MJRLegends** [comment]
@RedBlockFilms Just out of interest where did you download the pack?

**Comment by MJRLegends** [comment]
As Poor Iron ore shouldn't be generating in the overworld, i've taken a look. Either someone is wrong with your configs or world. or you have downloaded it from a modified source.

Please make sure you have installed it from a official source and please try reinstalling the whole pack and test in a new world

**Comment by MJRLegends** [comment]
Ok, i've taken a look at the world gen fully, and yeah poor iron ore spawns and will spawn in certain biomes and more in some types of biomes. im fully happy with the spawn rate of them. it all seems to be working ok here :P Let me know if you get anymore issues

**Comment by RedBlockFilms** [comment]
I downloaded it from the twitch launcher. I believe if you create a Biomes O' Plenty world with world type: continents (it might also require poison pools off), with the seed -6499043103729181559 and teleport to -393 32 -311, that is the location of the huge ore spawns. I tried on a new version also and this still happens

**Comment by MJRLegends** [comment]
Please see my above comment i've fully checked this out

**Comment by RedBlockFilms** [comment]
Sorry, you posted it while I was typing so I didn't notice it

**Comment by MJRLegends** [comment]
No worries, the poor iron ore is ment to be a lot more, even more in some biomes. each Poor iron only gives you 1/9 of a iron ingot

**Comment by MJRLegends** [comment]
And will give you 4.5 of a iron ingot if you put it in a smeltery, which seems ok to me :D

**Comment by RedBlockFilms** [comment]
It still might be a little op, because the one vein gave about 700 regular iron ore as well

**Comment by MJRLegends** [comment]
700 regular iron ore i wasnt able to reproduce only seems to be a issue on your side

**Comment by RedBlockFilms** [comment]
Okay, I'll just mine somewhere else so it doesn't totally ruin my game

**Comment by MJRLegends** [comment]
Yeah your seed just looks like you got very lucky and had 3 collections of poor iron ore together. But Vanilla iron ore looks ok from my tests and isnt touched by railcraft

**Comment by RedBlockFilms** [comment]
Do you know if there is a way to disable poor iron ore anyway?

**Comment by MJRLegends** [comment]
config files in "/config/railcraft/ores/" but do note i dont support anything bug related if any changes are made even small ones like this

**Comment by RedBlockFilms** [comment]
I understand. Thanks for all the help and support

**Comment by MJRLegends** [comment]
Any time :D
