### ISSUE TITLE
setting's don't save and reverts

### ISSUE THREAD

**Issue by bghyt** [MJRLegends/Space-Astronomy-2-Feedback-#228]
i put the pack to peaceful and even lock the difficulty and when i start the game up again it forgot i put it to peaceful
 weila settings don't save, i turn it on and when i click back it turns it's self off every single time
the map renders incorrectly sometimes (this is a mod issue not a pack issue just putting it there for people looking for answers) for example you boot up the game and it only shows caves even though i told it to show only the surface no matter how high i got

also when i click a villager to open their trade menu i attack them (i swap the attack and click button's) yet it still attacks them) so left click is place abnd right click is hit and when i left click it hits them and after a few tries it open their GUI. 

i'll update this if i find anymore bugs

**Comment by MJRLegends** [comment]
```
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

```
