### ISSUE TITLE
World Settings not saving

### ISSUE THREAD

**Issue by bghyt** [MJRLegends/Space-Astronomy-2-Feedback-#229]
### ---Issue Report---
i put the pack to peaceful and even lock the difficulty and when i start the game up again it forgot i put it to peaceful, so the game automatically puts me into normal mode,

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes

### Description of Issue
game does not stay on peaceful after i reboot the game

### Steps to Reproduce Issue
1. load up game and go into my world
2. game just puts it to normal for no reason
3. mobs spawn but shouldn't because i locked it to peaceful previous session.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
none

**Screenshots (if applicable):** 
N/A

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.4.2
**Where did this bug happen:** [Single Player or Server]
single player
### Additional Information
this happens every time i open the game, i load into my world and i see mobs despite setting it to peaceful last session (i do this every session)

**Comment by MJRLegends** [comment]
Update will be coming out soon

**Comment by MJRLegends** [comment]
Update is rolling out as we speak :D

**Comment by BraveCaperCat** [comment]
I Have The Same Problem In V1.5.7
