### ISSUE TITLE
the fluid pump from immersive engineering bug

### ISSUE THREAD

**Issue by warfarevenom** [MJRLegends/Space-Astronomy-2-Feedback-#23]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
duoe bug

### Steps to Reproduce Issue
1. place the fuild pump
2. brake the pump and get back 2 

**Crash log/Log (if applicable):**
none

**Version of Mod Pack using:** 
1.1.0
### Additional Information
[Any other information that may be able to help me with the problem]
none

**Comment by MJRLegends** [comment]
Ok, i can reproduce this bug in single player. Please can you try it in single player for you, as i know you currently play on a sponge server (frozen soul servers)

**Comment by MJRLegends** [comment]
Will reopen if anyone is able to reproduce the issue :D
