### ISSUE TITLE
Short freezing spikes

### ISSUE THREAD

**Issue by jeroenMeertens** [MJRLegends/Space-Astronomy-2-Feedback-#230]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
[Every couple of seconds, the game freezes for half a second or so. I have allocated the recommended amount of RAM (5120MB) to the game, so it would seem that is not the issue.]

### Steps to Reproduce Issue
1. [Play the mod for 5 minutes]
2. [Lag spikes occur]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.4.2]

**Where did this bug happen:** [Single Player]

### Additional Information
[Other mod packs gave a similar problem, but also I found no solution. I can allocate up to about 7,5G of RAM, but don't know whether that would help. The issue is likely not with my PC (Intel Core i5-7300HQ CPU @ 2.50GHz).]

**Comment by MJRLegends** [comment]
Sorry but this isnt a mod pack issue, even more so when you said you get it with other packs, its a hardware issue sorry.

**Comment by jeroenMeertens** [comment]
Thanks for the quick reaction. Any idea where I could look for a solution?
Sorry to be of bother to you.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-02-16 16:38 GMT+01:00 MJRLegends <notifications@github.com>:

**Comment by MJRLegends** [comment]
Not sure sorry, i can only help with mod pack related issues
