### ISSUE TITLE
Crash when shifting clicking when having a item in off hand

### ISSUE THREAD

**Issue by bdpowers1607** [MJRLegends/Space-Astronomy-2-Feedback-#231]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

### Description of Issue
[Description of the issue]
Space Astronomy 2 crashes when I use the shift key to crouch or move items in my inventory.
### Steps to Reproduce Issue
1. [First step] get into Space Astronomy
2. [Second step] use Shift key

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
SpaceAstronomy2Crash
https://pastebin.com/krkHh7jK

> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.4.2
**Where did this bug happen:** [Single Player or Server]
single player
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
See https://minecraft.curseforge.com/projects/better-combat-mod/issues/27
