### ISSUE TITLE
java.lang.NullPointerException while entering server

### ISSUE THREAD

**Issue by heylanwe** [MJRLegends/Space-Astronomy-2-Feedback-#232]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**I checked Open/Closed Issues before posting:**

### Description of Issue
'java.lang.NullPointerException' is shown, game did not crash but it's not possible to join the server.
Error is happening right after i see 'loading terrain' text on the screen.

### Steps to Reproduce Issue
1. Download Space Astronomy 2 through twitch  launcher
2. Run the game
3. When it's loaded try joining official server

**Crash log/Log (if applicable): no crush log available but I have log form the minecraft launcher
[logs java exception.txt](https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/files/1734009/logs.java.exception.txt)

**Screenshots (if applicable):** for better view i uploaded photos of error
![java exception pic1](https://user-images.githubusercontent.com/36573111/36344560-eda5c6ae-141c-11e8-8402-89e136518620.PNG)
![java exception pic2](https://user-images.githubusercontent.com/36573111/36344561-edc759c2-141c-11e8-8f83-f85655885e17.PNG)
![java exception 3](https://user-images.githubusercontent.com/36573111/36344608-662b9a0e-141d-11e8-82aa-305e7b654359.PNG)

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

 "updated last wednesday" 1.4.2, Forge version: forge-12.18.3.2511
last wednesday means it was last updated on 14.02.2018

**Where did this bug happen:** 
While joining Server

### Additional Information
I assigned 4096 mb of ram to modpack. Erased all other minecrafts and launchers. Erased all Javas on my laptop. Currently i have Java 8 update 161 (64 bit) and Java 9.0.4 (64 bit). I also degraded all visual effects.
I've also restarted my laptop several times.

**Comment by MJRLegends** [comment]
You are using the wrong version of the mod pack, it says on the multiplayer screen which version you need, also any issues with the frozen soul servers its best not to report them here as they wont see them
