### ISSUE TITLE
Rockhounding Gear - more of a FYI than a issue

### ISSUE THREAD

**Issue by Wolf68k** [MJRLegends/Space-Astronomy-2-Feedback-#235]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
I wanted to know the iron ingot to nugget recipe is the way it is. Then I saw the recipe for the Rockhounding Gear. Then I looked up issues here to see if it had come up and I saw #5. In it he said "one iron should become one crusing gear from rockhounding mod chemistry
but can only make iron nuggets" This was back in 1.0.7-beta, according to the issue report.

This is confusing to me. I looked at the same version of Rockhounding Chemistry that is in that version of the pack but in a separate instance (with it as the only mod and JEI) and the recipe there is iron ingot in the middle with nuggets top/bottom/left/right.

That aside the gear can be made within the current version of the pack using Rockhounding Chemistry item Casting Bench. You place it down, left-click it with an empty hand to change the cast, then right-click with the item (iron ingot). It makes the item (no power/energy needed). Then right-click again to get the new item.

This should allow you to remove the recipes you had to add before.

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please use the discord or curseforge comments for non bug talk, or if its a bug please fill out the template in full
