### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by Fukacu** [MJRLegends/Space-Astronomy-2-Feedback-#236]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [No]

### Description of Issue
[When i star my world is start fast but when i have 3 or 5 min of play i start to have some spike of lag for example when i open a chest, the chest open but with a dilay of 1-3 second and that happens to all my stuff and i dont have much because i just start to play ]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.4.2]

**Where did this bug happen:** [Single Player]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
This is no way a valid issue report, please make correct issue reports or i will have to remove your access from posting here

**Comment by MJRLegends** [comment]
You need to provide samples or tick profiler reports and details to how this is ExtraPlanets and you need to actually fill out the template
