### ISSUE TITLE
Refined Reborn multiblock disconnected each time during login

### ISSUE THREAD

**Issue by IyaTaisho** [MJRLegends/Space-Astronomy-2-Feedback-#237]
### ---Issue Report---

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes, I did see one issue similar (#155), but it was closed.

### Description of Issue
I recently built a Reborn Storage multi-block for storing all of my crafting recipes due that it was way easier than a wall of Crafters.  When I built the block, it worked great.

The next time I loaded the game, I could not find my recipes within my Refined Storage system.  I ended up moving a few blocks that were near it that emitted a Red Stone signal (levers to be exact) while trying to figure it out.

The following time I loaded up the game, I had the same issue.  I moved some Disk Drives that were near the Storage system and added a cable instead to touch it.  This fixed the issue.

Each time I come into the game I experience the same issue.  I have to cut the cable, sometimes break part of the block itself, and keep doing it over and over until the system decides I do have the Reborn Storage.

### Steps to Reproduce Issue
1. Build a Reborn Storage system.
2. Load some patterns into it.
3. Make sure you can auto-craft those items.
4. Save and quit.
5. Load game again.
6. Try to auto-craft those items.

**Screenshots (if applicable):**  I can provide if you like.

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.4.2

**Where did this bug happen:** Single Player

### Additional Information
Nothing else really.  It happens only on loading in.  Lasts maybe 5 minutes at most, but is super annoying especially if you were already auto-crafting something and the system forgets what it was doing.

**Comment by MJRLegends** [comment]
Thanks for the reply, yeah this is a know issue to me, but seems to be only in certain cases. If im honest im not sure what to do in terms on fixing it or getting it fixed...

**Comment by IyaTaisho** [comment]
Thanks for getting back to me.  It is annoying, lol.  Oh well, I just wanted to make sure you were aware.

Btw, thanks for the great mod pack.  I've really enjoyed playing so far, aside from the murderous drones spawning at times.  I look forward to completing it.  It seems to be more of a challenge as is to getting off of Earth than the first pack.

**Comment by Wolf68k** [comment]
I getting this as well. 

In the past I would I used a workaround with a ComputerCraft turtle to detect when I was on the server and then auto break and replace a block.
OpenBlocks use to have a player online detector, if I can find something like that in this pack with a block breaker and placer should work.
