### ISSUE TITLE
Opening inventory causes lagspike

### ISSUE THREAD

**Issue by RedBlockFilms** [MJRLegends/Space-Astronomy-2-Feedback-#238]
### ---Issue Report---

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Opening any inventory whatsoever drops my fps to 0 for 2-3 seconds

### Steps to Reproduce Issue
Open an inventory with Jei/Nei layout enabled

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.4.2]

**Where did this bug happen:** [Single Playerr]

### Additional Information
I've tried increasing my ram to 6gb and putting random letters in search to clear the item list to no avail. It may just be my crappy computer, but turning down graphics doesn't stop the lag.

**Comment by MJRLegends** [comment]
Please can you screenshot your inventory and jei when its open either when its freezing or after and drag the picture in to the mesaage box here to upload it :)

**Comment by RedBlockFilms** [comment]
During Lag:
![2018-02-24_21 36 20](https://user-images.githubusercontent.com/30029228/36637858-dcbfa876-19aa-11e8-98ba-13a258ae32e0.png)
After lag (average fps in-game is 60):
![2018-02-24_21 36 46](https://user-images.githubusercontent.com/30029228/36637867-0500b5a0-19ab-11e8-9c63-5bd1cee78355.png)

**Comment by MJRLegends** [comment]
Remove mekanim from the search bar and test please

**Comment by RedBlockFilms** [comment]
Do you want me to clear the nei from items?

**Comment by MJRLegends** [comment]
Just remove anything being in the search bar

**Comment by RedBlockFilms** [comment]
![2018-02-24_21 46 53](https://user-images.githubusercontent.com/30029228/36637941-40664370-19ac-11e8-8bac-f7ff4b0ea768.png)

**Comment by MJRLegends** [comment]
did it lag still?

**Comment by RedBlockFilms** [comment]
Yes, it lags no matter what you're searching

**Comment by MJRLegends** [comment]
Does it do it on other packs? as im starting to think this is a computer level issue

**Comment by RedBlockFilms** [comment]
No, this is the first pack I've had this issue

**Comment by MJRLegends** [comment]
Im not sure sorry...

**Comment by MJRLegends** [comment]
Could try removing the blur mod

**Comment by RedBlockFilms** [comment]
What is that mod called?

**Comment by MJRLegends** [comment]
Blur

**Comment by RedBlockFilms** [comment]
Oh, blur I guess

**Comment by RedBlockFilms** [comment]
Okay, so I was looking for mod options on the title screen, and I clicked the little spinning arrow in the top right corner and that completely stopped the lag

**Comment by MJRLegends** [comment]
Ok sorted then
