### ISSUE TITLE
game not able to launch because of scaffolding issue

### ISSUE THREAD

**Issue by shades619** [MJRLegends/Space-Astronomy-2-Feedback-#239]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes
### Description of Issue
when i got the pack i tried to launch it several times and it failed, upon looking at the console for minecraft it seemed to be a problem with immersive engineering and the scaffolding side variable or what ever

### Steps to Reproduce Issue
1. open minecraft
2. wait

**Crash log/Log (if applicable):** https://pastebin.com/QZUw1Adi

**Screenshots (if applicable):** 
![help me](https://user-images.githubusercontent.com/36973584/36875987-5387ad3e-1d78-11e8-9cf0-9689bbc506bb.PNG)

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.4.4
**Where did this bug happen:** [Single Player or Server]
literally opening the game
### Additional Information
[Any other information that may be able to help me with the problem]
problem seems to be caused by immersive engineering and modmanager

**Comment by MJRLegends** [comment]
How much ram are you assigned to the twitch app?
