### ISSUE TITLE
Broken Recipe

### ISSUE THREAD

**Issue by Grandmaster-Jax** [MJRLegends/Space-Astronomy-2-Feedback-#24]
### ---Issue Report---

Invalid recipe for rockhounding mod crushing gear
### Description of Issue
The crushing gear from rockhounding mod uses a single iron ingot in a vanilla bench to craft but instead produces 9 iron nuggets

### Steps to Reproduce Issue
1. place iron in bench
2. recieve nuggets instead of gear

Modpack version 1.1.1

**Comment by MJRLegends** [comment]
Thanks will be fixed in v1.1.2 Beta which is out tomorrow :D
