### ISSUE TITLE
[1.4.4] Items mispelled in achievement book

### ISSUE THREAD

**Issue by savosdarkran** [MJRLegends/Space-Astronomy-2-Feedback-#240]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
When looking at the Farming Technology achievement line, I noticed that Agriculture was spelled Agricurlture.

### Steps to Reproduce Issue
1. Open book to Farming Technology section.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 
![2018-03-01_22 13 05](https://user-images.githubusercontent.com/26523998/36881757-d63ee830-1d9d-11e8-816c-ad4ffc8ea1f7.png)

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.4.4

**Where did this bug happen:** [Single Player or Server] Both

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by savosdarkran** [comment]
You're welcome to use this fixed file.

[achievementList.txt](https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/files/1773601/achievementList.txt)

**Comment by MJRLegends** [comment]
Update is coming out as we speak
