### ISSUE TITLE
Spawner Changer not working for Villagers

### ISSUE THREAD

**Issue by IyaTaisho** [MJRLegends/Space-Astronomy-2-Feedback-#242]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
I decided to build a Villager Spawner to increase my emerald production and went about it using a method I had seen direwolf20 perform.  However, the plan had a hitch in it with the tool from Actually Additions called Spawner Changer.  When I Shift + Click on a Villager with said tool, nothing happens.  If I use the Spawner Changer on any other mob, it works perfectly fine.  Villagers however look at me and simply go "Eh".

### Steps to Reproduce Issue
1. Build an Actually Additions tool called Spawner Changer.
2. Shift + Right Click on a Villager.  It will do nothing.
3. Attempt the same process on any other mob, this works.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.4.6

**Where did this bug happen:** Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Thanks for the bug report but this is intended

**Comment by IyaTaisho** [comment]
Ah, I see.  Gotcha ;)  I had a feeling but never could confirm.  Thanks!
