### ISSUE TITLE
Mob Fan Distance Upgrades not Working as intended

### ISSUE THREAD

**Issue by Soa666** [MJRLegends/Space-Astronomy-2-Feedback-#243]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 

Yes

### Description of Issue

Mob Fan Upgrade #7616/2
Mob Fan from mob_grinding_utils #7606

The Mob Fan Upgrades only works 3 Blocks.
If you insert 10 it doesn´t change.

### Steps to Reproduce Issue

1. Build Mob Fan
2. insert Mob Fan Upgrades
3. let you push

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

If wanted i can make Screenshots

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 

1.4.6

**Where did this bug happen:** 

SinglePlayer

### Additional Information
No

**Comment by MJRLegends** [comment]
Sorry for the delay but yeah i can reproduce this, i will report it to the mod dev and see if hes able to fix it

**Comment by MJRLegends** [comment]
Reported to mod dev over at https://github.com/vadis365/Mob-Grinding-Utils/issues/84

**Comment by vadis365** [comment]
Hey,
Not sure if this is the cause but any blocks in the same line of blocks as the fan at the same level as the fan will stop the fan at that block. I added this on purpose as a safety feature.
If any block is directly in front of a fan this will happen - even a torch.
Cheers,
Me.

**Comment by MJRLegends** [comment]
@vadis365 Sorry for the slow reply, Yeah you are correct it works as you described cc @Soa666
