### ISSUE TITLE
Cant load the modpack

### ISSUE THREAD

**Issue by kameronnaxton** [MJRLegends/Space-Astronomy-2-Feedback-#244]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
Cant load the mods and its stuck at forge mod loader and it just becomes stuck

### Steps to Reproduce Issue
1. play profile
2. launch pack

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 
https://gyazo.com/986beba592961a7d43622b75e9df7875

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.4.6v

**Where did this bug happen:** [Single Player or Server]
Trying to load the mocpack

### Additional Information
[Any other information that may be able to help me with the problem]
no additional information

**Comment by MJRLegends** [comment]
You need 5+Gb of ram also your issue is very basic and very unhelpful for me to see details to your issue. But i cant bet its a ram issue for sure
