### ISSUE TITLE
Crash on launcher

### ISSUE THREAD

**Issue by chaotix8000** [MJRLegends/Space-Astronomy-2-Feedback-#246]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes

### Description of Issue
Crashes with this error
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from SG Craft (sgcraft)

### Steps to Reproduce Issue
1. launch
2. crash

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

https://pastebin.com/wH7Nr9FB

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
v1.4.7

**Where did this bug happen:** [Single Player or Server]

launcher

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
@chaotix8000 Thanks for the bug report, sorry for the delay on a message back, please can you try and reinstall the whole mod pack

**Comment by chaotix8000** [comment]
I've deleted and reinstalled a few times. Even uninstalled twitch app just in case.

**Comment by MJRLegends** [comment]
@chaotix8000 Please try with latest and if you still get the issue please post back here
