### ISSUE TITLE
Lanucher crash

### ISSUE THREAD

**Issue by y40775568** [MJRLegends/Space-Astronomy-2-Feedback-#248]
---Issue Report---
(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)

Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING): [Yes or No]
No

Description of Issue
After click play and to the loading screen,then the Minecraft will be crash and go back to the launcher shows the crash report. And the Space Astronomy 1 have not this problem i can run it 

Steps to Reproduce Issue
Start launcher and then crash
5.crash
Crash log/Log (if applicable): [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

log too big to be put into paste bin uploaded to mega.nz

https://pastebin.com/5URKzpSm

Screenshots (if applicable):

Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'): [VERSION]

1.4.7

Where did this bug happen: [Single Player or Server]

single player

Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Dont post multiple issues
