### ISSUE TITLE
clouds turned into rotisserie chicken texture

### ISSUE THREAD

**Issue by dedrahn** [MJRLegends/Space-Astronomy-2-Feedback-#249]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
All the clouds in game have become the texture of hi res rotisserie chicken...turning off weather 2 or any vanilla weather has no effect

### Steps to Reproduce Issue
1. Logged into it like that...started during an F0 tornado spawned by weather2
2. 

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 
![base profile screenshot 2018 04 01 - 14 47 47 39](https://user-images.githubusercontent.com/37985476/38176834-ec64c7d4-35bb-11e8-8b7e-c64a86d3b846.png)

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.4.7 for MC 1.10.2

**Where did this bug happen:** Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Lol the amount of people who has reported it as a bug today haha its April fools Easter egg by Mojang
