### ISSUE TITLE
Computercrafts: Advanced Monitor do not form

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-2-Feedback-#25]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
Trying to place 4x4 Advanced Monitor from computercraft

### Steps to Reproduce Issue
1. place 4x4 Advanced Monitor 
2. do not form 

As  seen here
http://imgur.com/a/JtCpV

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** 1.1.1 beta

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Mods being removed since we have open computers :D
