### ISSUE TITLE
Bug in the new version (1.4.8) while typing the letter "o" into the JEI search bar

### ISSUE THREAD

**Issue by jchaz12349** [MJRLegends/Space-Astronomy-2-Feedback-#252]
[crash-2018-04-13_01.17.38-client.txt](https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/files/1952033/crash-2018-04-13_01.17.38-client.txt)
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
[I updated the pack to version 1.4.8 and tried to type the word "oil" into the JEI search bar, then the world closed and the game crashed. I tried to see if it was an isolated incident so I reopened the game and the same single player world. I tried typing the word "oil" again, and the game crashed. I thought it may be a bug with an item displaying in JEI. I again reopened the same single player world and typed the letter "o" into JEI, the game crashed. Next I reopened the game and changed all key binds off of the letter "o". I opened the same world, and typed the letter "o" and the game didn't crash. I then typed the word "oil", and "canola" and the game did not crash. After that I figured the game would not crash, so I went on with my game and tried typing the word "empowered". The game crashed after that, and as of now I have not tried typing anything into JEI.]

### Steps to Reproduce Issue
1. [First step] While in game open inventory and begin typing into the JEI search bar.
2. [Second step] Simply type the letter "O", or any word containing the letter "O"

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** No applicable screenshots

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [v1.4.8]

**Where did this bug happen:** [Single Player]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Use pastebin for the crash log please

**Comment by MJRLegends** [comment]
I will let you off this once, you need fo add more ram
