### ISSUE TITLE
Crash on launcher

### ISSUE THREAD

**Issue by y40775568** [MJRLegends/Space-Astronomy-2-Feedback-#254]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]
After click play and to the loading screen, then the Minecraft will be crash and go back to the launcher shows the crash report.I try to install it, but it doesn't work
### Steps to Reproduce Issue
Start launcher and then crash

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do I locate a crash log on Minecraft on Curse/Twitch? see* 
https://pastebin.com/8Nwf3B6q

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.4.9
**Where did this bug happen:** [Single Player or Server]
Single Player 
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Ypu need to post the crash log please will reopen when you have supplied it
