### ISSUE TITLE
crash while trying to launch the latest version of the pack 

### ISSUE THREAD

**Issue by oItsSerenityo** [MJRLegends/Space-Astronomy-2-Feedback-#255]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
no
### Description of Issue
[Description of the issue]
when trying to launch the pack it keeps crashing, and this is the report i have gotten. 
### Steps to Reproduce Issue
1. [First step] simply try to launch the pack 
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* 

https://gist.github.com/oItsSerenityo/32861eee78fd86d6e98fd2abcf5ac972

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
Version 1.4.9

**Where did this bug happen:** [Single Player or Server]
single player 
### Additional Information
[Any other information that may be able to help me with the problem]
this has happened many times but this is the first time it has happened where i have gotten a crash report to send in.

**Comment by MJRLegends** [comment]
Please reinstall the whole pack

**Comment by oItsSerenityo** [comment]
that was a clean install as i just wiped the computer but i will for sure give that a try .

**Comment by MJRLegends** [comment]
Something is wrong with the install in your side either forge or mods are not being downloaded correctly. Sorry i wish i could say its a mod pack issue but its unfortunately not one

**Comment by MJRLegends** [comment]
You could try adding more ram and updating from the out dated version of java mc launcher installs and you could try switching to jar launcher in twitch app settings. Sorry i cant do anything from my side
