### ISSUE TITLE
Game Crash when placing tier 2- 4 extra planets helmet on.

### ISSUE THREAD

**Issue by Bonio55** [MJRLegends/Space-Astronomy-2-Feedback-#257]
I have experienced the game crashing back to desktop from multiple clients when attempting to wear the tier 2-4 extra planets helmets when placing into slots via the inventory gui.  The game will proceed to crash back to desktop and each time attempting to reconnect to server / local copy of the game after this point and results in the game instantly dropping back to desktop. 

Temp Fix to get back into game: 

Open up player DAT file and go to inventory and move the helmet back to a lower slot number i.e. 1-30 rather than 101-103

Work Around to wear the helmet:

It is possible to wear the helmet but the helmet must be placed on to a armor stand (using empty hand with redstone signal) and then shift click the helmet on, once player is wearing the helmet via this method it also allows for me to disconnect and reconnect to the server / local copy without getting kicked back to desktop.

**Comment by MJRLegends** [comment]
Please fill out the template you deleted, will reopen when you have done so

```
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

```
