### ISSUE TITLE
Rocket not launching to go home after landing on different planet.

### ISSUE THREAD

**Issue by Iruton13** [MJRLegends/Space-Astronomy-2-Feedback-#258]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
In creative mode, after landing on different planet, when I place a rocket down and fuel it, it doesn't launch when I enter it and can't shift out of it.

### Steps to Reproduce Issue
1. Load game, load world in creative mode.
2. Get items necessary for rocket launch from creative inventory
3. Get in fueled rocket and launch to different planet.
4. Land safely on the planet and get materials from the lander
5. Do rocket setup and try to launch with the fueled rocket. I get stuck inside without being able to launch or shift out of the rocket. Sometimes, I can't even access the rocket's inventory.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 
Can't really show how I am stuck in rocket with just a picture. Maybe video if needed.
**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
Version: v1.4.9 The only version I can play since using Twitch launcher.
**Where did this bug happen:** [Single Player or Server]
Single Player
### Additional Information
[Any other information that may be able to help me with the problem]
I have settings changed so there is less lag for my computer. Render distance 2, Clouds off, Mipmap Levels off (settings actually say mipmap), VSync and VBOs both on, Smooth Lighting off, Graphics fast, GUI Scale normal, Brightness bright, Entity Shadows on.

**Comment by MJRLegends** [comment]
Yeah use the survival rockets
