### ISSUE TITLE
Tier 2 - 4 Space Suit Crash

### ISSUE THREAD

**Issue by Aveau** [MJRLegends/Space-Astronomy-2-Feedback-#259]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue

If you try to put an space suit helmet T2/T3/T4 without having a full body set ( I only tried with space suit ) already equiped, you crash.
If you try to remove any piece of your space suit while having T2/T3/T4 helm equiped, you crash.
If you try to reconnect, minecraft crash.

### Steps to Reproduce Issue
1. Be naked 
2. Put space suit T2/T3/T4 helm on your head

or

1. Wear space suit
2. Remove any piece but helm

**Crash log/Log (if applicable):** https://pastebin.com/XJMejMTY
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** space astronomy 1.4.9

**Where did this bug happen:** Single and Multi player

### Additional Information

The only way I found is to kill player when they connect. They got another crash, then they can play normally again.
If you put on you: you're forced to put this helm last
If you remove from you: you're forced to remove this helm first

**Comment by MJRLegends** [comment]
Thanks fixed in next update, will be out later
