### ISSUE TITLE
Mekanism Universal cables don't connect to Extreme Reactors Redstone flux port

### ISSUE THREAD

**Issue by cheeseburgur101** [MJRLegends/Space-Astronomy-2-Feedback-#26]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Ye
### Description of Issue
Mekanism Universal cables don't connect to Extreme Reactors Redstone flux port

### Steps to Reproduce Issue
1. Try to get them to connect
2. won't.

**Crash log/Log (if applicable):** No crash.

**Version of Mod Pack using:** 1.1.1
### Additional Information
Sometimes they appear to connect, but no energy will be transferred.

**Comment by MJRLegends** [comment]
You can use Galacticraft Wire to connect them :D

**Comment by MJRLegends** [comment]
Ok just just checked you need to use the configurator to configure the ends :D so it works :P 
![2017-07-02_00 15 03](https://user-images.githubusercontent.com/8526321/27766050-850ec724-5ebb-11e7-8721-86473731d771.png)
