### ISSUE TITLE
Crashes at random intervals

### ISSUE THREAD

**Issue by Orientum25** [MJRLegends/Space-Astronomy-2-Feedback-#260]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** No

### Description of Issue
Hosting a server to LAN using Hamachi, game keeps on crashing at random intervals.

### Steps to Reproduce Issue
1. Launch Game
2. Wait

**Crash log/Log (if applicable):** [https://pastebin.com/QKn4xRSB]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.5.1]

**Where did this bug happen:** [Server]

### Additional Information
[We think it might be due to the use/pickup/crafting of vanilla items, although we aren't sure because it has crashed without.]

**Comment by Spellkaze** [comment]
Ouch, seems like a bug from astral sorcery. This bugs seems to repeat with galacticraft . @MJRLegends  , you probably want to check this bug report. https://github.com/HellFirePvP/AstralSorcery/issues/625
I would tell you to remove that mod if is a real pain, but wait for MJR to check if he can do something.

**Comment by MJRLegends** [comment]
Already known issue

**Comment by MJRLegends** [comment]
And the mod dev wont be fixing sorry

**Comment by MJRLegends** [comment]
Added to known issues at https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/issues/99
