### ISSUE TITLE
Crash before the load game screen

### ISSUE THREAD

**Issue by yellowpanda** [MJRLegends/Space-Astronomy-2-Feedback-#261]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Application crash on start up. 

### Steps to Reproduce Issue
1. Start Space Astronomy from Twitch
2. Crash. Before the load save game screen.

**Crash log/Log (if applicable):** 
https://pastebin.com/YM8s1cUw

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 
1.5.1

**Where did this bug happen:** 
Single Player

### Additional Information
I was playing the game and the press something that made the inventory disappear (F1???). Then the application crashed and will not start again. I tried to search for a key to bring it back. Might have changed some key bindings (really helpful NOT).

**Comment by yellowpanda** [comment]
I found the problem. To make the application start again I changed this line `key_waila.keybind.wailadisplay:-100` to `key_waila.keybind.wailadisplay:0` in `options.txt`.

Thanks for a great mod pack.

**Comment by MJRLegends** [comment]
the mod pack is submitted with key_waila.keybind.wailadisplay:0 in options.txt as the default
