### ISSUE TITLE
Bouncing across water bug

### ISSUE THREAD

**Issue by pokmon987** [MJRLegends/Space-Astronomy-2-Feedback-#262]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
When swimming in water, the player 'bounces', and essentially is flung across the water. It is controllable, though annoying, and can kill the player from fall damage

### Steps to Reproduce Issue
1. Find a suitable ocean or river
2. Try holding the space bar to swim in it and walk forward

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.5.2

**Where did this bug happen:** Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please can you post a copy of your player data file

**Comment by pokmon987** [comment]
[4ff3baa1-1c67-4a6b-a272-aa6dd5921eca.zip](https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/files/2204095/4ff3baa1-1c67-4a6b-a272-aa6dd5921eca.zip)

Hopefully that's what you need

**Comment by TheMajesticPickle** [comment]
I have the same bug, but I find it really useful for exploring, albeit very cheaty. it has nearly killed me 4 times though. Its like the fall damage builds up until you land. how can I complain?

**Comment by MJRLegends** [comment]
Sorry for the delay, i will be taking a look at this today

**Comment by MJRLegends** [comment]
Please can someone provide a video of this & please try testing in a new world

**Comment by pokmon987** [comment]
Sorry, I've been busy, though with the 1.5.3 update it seems to be fixed in my world. I have not yet tried in a new world, though if you're still curious if it's there I can try it out

**Comment by MJRLegends** [comment]
Let me know if the issue happens again on latest version @pokmon987  @TheMajesticPickle
