### ISSUE TITLE
Game wont load.

### ISSUE THREAD

**Issue by Evilslenderman1** [MJRLegends/Space-Astronomy-2-Feedback-#263]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Wont load at all

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):**Unable to create directory. 1.12.json
Name: 1.12.json
URL: https://launchermeta.mojang.com/mc/assets/1.12/e75e9535754c6f2158b0b18b35660f45c4495d78/1.12.json
Error details: Access is denied
Filename on disk: d4b4-1e79-ec40-458e
Path: C:\Users\RICKBE~1\AppData\Local\Temp\d4b4-1e79-ec40-458e
Exists: file
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.10.2]

**Where did this bug happen:** [Single Player]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Its a issue on your end sorry nothing i can do. Uninstall the mod pack and maybe twitch app and try again
