### ISSUE TITLE
Grid Power not available

### ISSUE THREAD

**Issue by thebigcarp321** [MJRLegends/Space-Astronomy-2-Feedback-#266]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
I have checked all open and closed issues for grid power, GP, and extra utilities.

### Description of Issue
I am not able to get any grid power other than the manual mill. Any other mill I place provides me no more than 0.04 GP of GP.

### Steps to Reproduce Issue
1. I've installed on a new system.
2. I've reinstalled mod pack and started a new world.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
v1.5.2
![2018-07-09_22 40 52](https://user-images.githubusercontent.com/6496593/42486279-2d8d7f84-83c9-11e8-9047-ec809652eff1.png)

**Where did this bug happen:** [Single Player or Server]
Single Player

### Additional Information
[Any other information that may be able to help me with the problem]
I have found some forum posts about something called GP lock and deleting the XUsave.dat file and I have done that and that has not done anything for me.

**Comment by MJRLegends** [comment]
All of the mils work, For the wind mill you got to have it up high with blocks only below it i believe and for the water mill has to be running/flowing water. If you find a problem when doing these things let me know
