### ISSUE TITLE
Game consistently crashing every < 5 minutes

### ISSUE THREAD

**Issue by IyaTaisho** [MJRLegends/Space-Astronomy-2-Feedback-#267]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
I started getting game crashes recently when working with Mekanism (primarily for the 5x Ore system).  Initially, I had my Ore processing done in my main base.

The setup was simple:

1. Ender Chest (w/w/w) receives items
2. Ores are pulled out via Item Conduit (filtered to only Ore) into a Large Crate
3. From here, unwanted Ores (Black Quartz and Osmium) are filtered into a Trash Can while the rest are pulled into 3 Elite Enrichment Factories (fully upgraded) and 2 Sag Mills (fully upgraded also)
4. Once the Ore gets through this layer, everything is sent to another Large Crate via Item Conduit
5. From the Large Crate, any Cobblestone is sent to a Trash Can (Sag Mills fault).  Everything else is pulled out via Item Conduit to 6 Elite Smelter Factories (fully upgraded)
6. Ingots are pulled out via Item Conduit and into another Ender Chest (w/blue/w)
7. The Ender Chest is hooked to my Refined Storage via Importer
8. All Ingots are dispersed into a series of Storage Drawers (mostly Compact Drawers, but some with simple Storage Drawers) via the Drawer Controller

I completed the 5x Ore task eventually (used it only for Gold) and it caused a HUGE amount of lag.  I ran it only once with my RFTools Builder (Quarry) just to test the system.  I could barely move, lol.

After that, I looked into how to remove the lag.  I first of all disassembled the 5x Ore system and removed everything down to 3x Ore (only Gold was still being processed).  This helped but didn't solve the issue, plus my game still randomly crashed when going into my Wireless Crafting Grid (Refined Storage).

Eventually, to help with the lag even more, I moved my Ore processing out of my base altogether and into one of my early bases (small island).  I kept the same setup and the lag seemed to dissipate a bit at base, but the crashes continued.

Since then, I moved on and blasted into space.  Different planets have not caused any issues yet.  However, I do have the same issue of crashes when back at my base, which happen frequently (typically within 5 or less minutes of loading up the game).  I can't really open my Wireless Crafting Grid without fear of a crash unless in an empty part of my base (typically the Ore processing room) or next to my bed.  Using a Crafting Grid is similar.

I'm unsure what is really causing the crashes at this point.  I unloaded several chunks (particularly the ones with my 2 Evaporation towers for Mekanism).  The 2 Evaporation towers are at least 1,000+ blocks away from my base, as well as my Ore processing area.

I don't think it is how much memory I have (though it could be) for the game.  I've dedicated 8 GB and can spare at most maybe 1-2 GB more (have 12 altogether but afraid to stretch my memory that thin).

### Steps to Reproduce Issue
1. Fill an area with multiple Mekanism factories (perform 3x Ore processing), Refined Storage, and Storage Drawers.  Ensure all of the above is connected together (allow for auto-crafting).
2. Set up an RFTools Builder with Quarry card.  Mine out an area and feed it back to the Ore processing area.

**Crash log/Log (if applicable):** [Link](https://pastebin.com/u/IyaTaisho)

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.4.7

**Where did this bug happen:** Single Player

### Additional Information
I provided a few logs to hopefully help.  If more details are needed or logs, let me know.  Thanks!

**Comment by MJRLegends** [comment]
Use please pastebin for the crash logs, i dont want to fill my desktop with files each time i look at the issue

**Comment by MJRLegends** [comment]
Will reopen when you have changed them

**Comment by IyaTaisho** [comment]
I think I figured out the issue.  It was my old friend Refined Storage again, lol.

Tonight, I decided to see if separating out my Refined Storage system from my base would help.  I moved it north about 700 blocks and took everything I could for it there, then set up a network connection back to base.  The results cured my crashing so far.

I think the issue is I have a crap ton of automation through Refined Storage, plus the brains of it along with my Storage Drawers are all in the same area, spread across 2-3 chunks.  When I took the brains away, the crashing stopped.  I also saw my lag lessen (minimal lag now in that same area).

The only other thing I think could have been attributing to the issue was my Wither Skeleton Spawner was running (had no idea till I heard skeletons dying).

It seems it was just my derpy base design more than anything.  I'm learning more and more that you have to spread out the base far more in 1.10.2 versus 1.7.10.  1.10.2 seems to be harder on resources.

My apologies for having to examine the issue.  Thanks for a great pack and I look forward to getting back into trying to finish playing it out.
