### ISSUE TITLE
crash when opening waypoints menu (pressing B)

### ISSUE THREAD

**Issue by TheMajesticPickle** [MJRLegends/Space-Astronomy-2-Feedback-#269]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
When I tried to create a waypoint Minecraft stopped responding and crashed.

### Steps to Reproduce Issue
1. [First step] Don't change any controls
2. [Second step] Press B before pressing J (see additional info)

**Crash log/Log (if applicable):** [ [here](https://pastebin.com/bVvY0b0H) ]

**Screenshots (if applicable):** n/a

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.5.2]

**Where did this bug happen:** [SinglePlayer]

### Additional Information
at first I thought It didn't like it when I pressed B before J, since journeymap insists on telling you what's new quite often. but looking at the crash log, it looks like galacticraft. Best to be safe though.

I have not modified the pack in any way aside from adding optifine and disabling blur.

I have also played on 1.5.2 prior to crashing from pressing B, so theres a chance this is a one time issue.

**Comment by MJRLegends** [comment]
Thanks. Btw optifine isnt supported and can cause issue

**Comment by TheMajesticPickle** [comment]
Yeah, optifine has caused me a few issues, but I just need to deal with it because I cant run the pack otherwise. Thanks though

**Comment by MJRLegends** [comment]
Im unable to reproduce this in the latest version please let me know if you still get the issue
