### ISSUE TITLE
Heavy performance issues

### ISSUE THREAD

**Issue by Axeri0n** [MJRLegends/Space-Astronomy-2-Feedback-#27]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
Even though I only allocated 4gb of ram to minecraft it actually uses up to 5 and a half gb and despite of that i only get about 10fps with severe 2s lag spikes, My graphics card is a gtx 760 and i have an intel i5-4570 (3.5ghz) and 8gb of ram.

### Steps to Reproduce Issue
1. start minecraft
2. get frustrated when trying to play

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [1.1.1 Beta]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by Axeri0n** [comment]
[http://imgur.com/a/Uwr8W](url)

**Comment by MJRLegends** [comment]
You changing the ram in the wrong place

**Comment by MJRLegends** [comment]
and yeah it needs 4-6 GB of ram

**Comment by MJRLegends** [comment]
Also when making a new world something is being ran so that will use performance but your fps is down to low amount of ram assigned to the mc and its a very heavy pack so you might not be able to run it
