### ISSUE TITLE
Will not let me join a server

### ISSUE THREAD

**Issue by Vanicko** [MJRLegends/Space-Astronomy-2-Feedback-#271]
### Description of Issue
Internal Exception: java.lang.NullPointerException appears when attempting to log into a server.

### Steps to Reproduce Issue
1. Go into multiplayer
2. Attempt to join a server

**Screenshots (if applicable):** 
![javaw 2018-07-28 12-31-17-352](https://user-images.githubusercontent.com/37759182/43359977-41196020-9262-11e8-8e73-1097f5382e20.jpg)

**Version of Mod Pack using:** [1.5.3]

**Where did this bug happen:** [Server]

### Additional Information
Server says version 1.5.2, usually a 0.0.1 version difference doesn't cause any problems but it might.

**Comment by MJRLegends** [comment]
Nothing to do with me i dont own any servers.
