### ISSUE TITLE
Modular powersuits Power Fist unable to cycle

### ISSUE THREAD

**Issue by TomaHawwke** [MJRLegends/Space-Astronomy-2-Feedback-#273]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes[/]
### Description of Issue
[after installing a battery and quite a few of the tools active for the power fist i have found that i cant only use the lux capacitor and not other tools even show up such as the plasma cannon or railgun]

### Steps to Reproduce Issue
1. [install tools on Power Fist]
2. [attempt to cycle through them using Sneak+Button 3(scroll)]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by TomaHawwke** [comment]
just looking back on this and realizing how terrible my usage of english was here and i apologize as i a very tired at the point of writing these

**Comment by MJRLegends** [comment]
Please dont open multiple issue reports for the same thing
