### ISSUE TITLE
Modular Powersuits, Power Fist Cycle not working

### ISSUE THREAD

**Issue by TomaHawwke** [MJRLegends/Space-Astronomy-2-Feedback-#274]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes[/]
### Description of Issue
[after installing a battery and quite a few of the tools active for the power fist i have found that i can only use the lux capacitor and not the other tools, they don't even show up such as the plasma cannon or railgun]

### Steps to Reproduce Issue
1. [install tools on Power Fist]
2. [attempt to cycle through them using Sneak+Button 3(scroll)]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.10.2]

**Where did this bug happen:** Single Player

### Additional Information
[i apoligize for the duplicate post but i almost completely butchered the first one because im quite a bit tired]

**Comment by MJRLegends** [comment]
You just need to change the cycle key in the controls menu

**Comment by TomaHawwke** [comment]
ill check controls but i dont think its there
