### ISSUE TITLE
Going to the nether

### ISSUE THREAD

**Issue by Kzazen** [MJRLegends/Space-Astronomy-2-Feedback-#276]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
[Description of the issue]
Not a bug but in order to go to the nether you need to start a fire and you can't make steel for flint and steel without going to the nether first. There is no clear explanation on how to start a fire to go to the nether so my friend and I had to google to find that if you put lava near wood right next to the portal it will light the portal. Could you please add a clear way to start the fire to enter the nether? Thank you

### Steps to Reproduce Issue
1. [First step]
Make a portal frame
2. [Second step]
Try to light it. oh no

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.27
**Where did this bug happen:** [Single Player or Server]
Private server (Creeperhost)
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You can make steal, may i suggestion you do more looking on jei on how to make steal ingots/dust
