### ISSUE TITLE
World keeps going back to peaceful difficulty.

### ISSUE THREAD

**Issue by SamuelJolaoso** [MJRLegends/Space-Astronomy-2-Feedback-#277]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Every time I load up the world the difficult always resets to peaceful when i set it to normal every time i leave the world. Now its locked on peaceful and i didn't not even do that, last time i locked it on normal.

### Steps to Reproduce Issue
1. Leave the world
2. Join back

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> There is no crash log.

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.5.3]

**Where did this bug happen:** [Its single player but i would see the world backup as a sever or something.]

### Additional Information
I can give logs and the world file if needed.

**Comment by MJRLegends** [comment]
Yeah its not fixed. Hence the fact it's got a waiting or reply / fix from mod dev label

**Comment by SamuelJolaoso** [comment]
Oh ok, I fixed it tho. I forcefully set it to normal in the world
properties file from 0 to 2 i think.
