### ISSUE TITLE
EnderIO Mod removed randomly

### ISSUE THREAD

**Issue by KrispyTV** [MJRLegends/Space-Astronomy-2-Feedback-#279]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [YES]

### Description of Issue
[Played the mod pack yesterday and enderIO was in the mod pack and it loaded up fine. Now today i load the mod pack and when i try to enter my world it says "blocks are missing" and it names all the enderIO blocks all like 263 blocks. I went into my world anyways and i typed in @enderIO in the search bar and nothing comes up only ender storage does.]

### Steps to Reproduce Issue
1. [Relaunched mod pack]
2. [made sure enderIO was installed]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 
http://prntscr.com/l4x56w

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.5.3]

**Where did this bug happen:** [Single Player]

### Additional Information
[when in world messages appear in chat box that i have put in the screen shot spot]

**Comment by KrispyTV** [comment]
well i didnt wanna lose the world i already started

**Comment by MJRLegends** [comment]
Copy your world from the saves folder to another place and then add it back after reinstall.

**Comment by KrispyTV** [comment]
thank you! havent played minecraft in a while so forgot i can do that! This is my favorite mod pack ive ever played tho great work!

**Comment by MJRLegends** [comment]
No problem, glad your enjoying it
