### ISSUE TITLE
coke oven

### ISSUE THREAD

**Issue by SpongeMatthew** [MJRLegends/Space-Astronomy-2-Feedback-#28]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
when i am making a coal coke multiblock from immersive engineering it glitches out and the coke bricks look like they moved to the left and forward one i tried breaking the multiblock but the image of it is still there

### Steps to Reproduce Issue
1. build the coal coke machine
2. hit it with the immersive engineering hammer
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** 1.1.1

### Additional Information

**Comment by MJRLegends** [comment]
looks fine to me?

are you using optifine?
![2017-07-02_01 34 45](https://user-images.githubusercontent.com/8526321/27766413-abe5d12a-5ec6-11e7-95b2-263a058c8607.png)

**Comment by MJRLegends** [comment]
Or a texture pack?
and does it do it in single player?

**Comment by SpongeMatthew** [comment]
im not using optifine and no texturepack and i havent tried it on single player its only happening when im on SAv2-1

**Comment by SpongeMatthew** [comment]
just tried it out its not happening on my single player world but in multiplayer it is

**Comment by SpongeMatthew** [comment]
![2017-07-01_20 02 28](https://user-images.githubusercontent.com/29210922/27766518-3c52dbce-5e98-11e7-9be0-0c7072a8bd35.png)

**Comment by MJRLegends** [comment]
its a sponge issue then
