### ISSUE TITLE
FPS drop when going outside in the world

### ISSUE THREAD

**Issue by modsareawesome** [MJRLegends/Space-Astronomy-2-Feedback-#280]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
FPS drop from 120 to 2 when going outside through my door
/kill @e[type=!Player] didnt help

### Steps to Reproduce Issue
1. go into world
2. get out of the house

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):**
1.5.3

**Where did this bug happen:**
Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
How much RAM have you assigned in the twitch app

**Comment by modsareawesome** [comment]
1024 mb

**Comment by MJRLegends** [comment]
Without a java profiler sample as i cant do anything as your not just using my mods so could be anything causing it like a million different things. If you need help getting a java profile sample let me know. I will reopen this when theres information to go off

Put this on your client & follow instructions on how to use on the link:  https://refinedstorage.raoulvdberge.com/wiki/profiling
