### ISSUE TITLE
Cannot Launch Modpack

### ISSUE THREAD

**Issue by KaiGin** [MJRLegends/Space-Astronomy-2-Feedback-#281]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
I open the launcher and press play but the launcher reopens and says unexpected crash.

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

https://pastebin.com/KRLTGBGi

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.5.3]

**Where did this bug happen:** [Single Player or Server]
Single Player Launch

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Reinstall the mod pack
