### ISSUE TITLE
Iron Nuggets and Compacting Drawers

### ISSUE THREAD

**Issue by LukeSkywalk3r** [MJRLegends/Space-Astronomy-2-Feedback-#283]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Putting Iron Ingot/Block into Compacting Drawer results in Backports Iron Nugget, but that seems useless (only craftable to Neotechs Nugget or Ingot) (Tested with OpenComputers Cable). Putting Neotechs Nugget into Drawer results in Drawer only giving Neotech Nugget.

### Steps to Reproduce Issue
1. Get Compacting Drawer
2. Put Iron Block/Ingot into it
3. Take back out, put Neotech Iron Nugget in

**Crash log/Log (if applicable):** n/a

**Screenshots (if applicable):** 
![2018-10-25_16 19 13](https://user-images.githubusercontent.com/6844160/47507304-3f9e2400-d872-11e8-8a76-865cc625d2d3.png)
![2018-10-25_16 19 48](https://user-images.githubusercontent.com/6844160/47507305-3f9e2400-d872-11e8-8d77-2c2aeac32fbe.png)

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.5.3

**Where did this bug happen:** Server (on local machine)

### Additional Information
[Any other information that may be able to help me with the problem]
(for a quickfix we now added Backports Nugget back to <ore:nuggetIron> , thus modifying the zs.
That way Poor Ore result can go into Drawer, and RS can craft stuff)

**Comment by MJRLegends** [comment]
You can convert Backports Iron Nugget to the intended Neotech Iron Nugget via a crafting recipe. The bug here is your able to get Backports Iron Nugget

**Comment by MJRLegends** [comment]
I dont think i can fix Compacting Drawer giving Backports Iron Nuggets. I might just have to leave it and continue to allow people to use the Backports Iron Nugget > Neotech Iron Nugget via a crafting recipe

**Comment by MJRLegends** [comment]
Added to known issues over at #99
