### ISSUE TITLE
Pressing H key crashes the game.

### ISSUE THREAD

**Issue by Gamebuster19901** [MJRLegends/Space-Astronomy-2-Feedback-#285]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes, it relates to #269

### Description of Issue
Pressing H crashes the game with a NullPointerException

### Steps to Reproduce Issue
1. Press H when in a world, with no GUI open and the chat window not visible.

**Crash log/Log (if applicable):** 
https://pastebin.com/6dNXWePU

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 
1.5.4

**Where did this bug happen:** 
Single Player

### Additional Information
Problem probably occurs [here](https://github.com/MJRLegends/ExtraPlanets/blob/66bd7abdcaf23b99bcc7dc522ff4e21a352a55b1/src/main/java/com/mjr/extraplanets/client/handlers/KeyHandlerClient.java#L65). I suspect the variable 'kb' is null. However the crash log says the NPE occured on line 94, but no line 94 exists in that file, so I'm not 100% sure, otherwise I would have opened a PR.

**Comment by Gamebuster19901** [comment]
Additional Information:

It appears to be the keybinding for Extra planets named "Open Module Manager" causing the issue.

Changing the keybind to NONE is a temporary fix for affected players.

**Comment by MJRLegends** [comment]
What armour were you wearing? @Gamebuster19901

**Comment by MJRLegends** [comment]
Thanks will see what i can do

**Comment by MJRLegends** [comment]
Pack update is being uploaded as we speak
