### ISSUE TITLE
Growth Crystal issues in Stoneblock

### ISSUE THREAD

**Issue by Khultzyfy** [MJRLegends/Space-Astronomy-2-Feedback-#286]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
All growth crystal tiers in Stoneblock Modpack are having an issue where they will end up only affect two plants that around them in a 3x3 area.

### Steps to Reproduce Issue
1. [First step]
First plant a 3x3 area of mystical agricultural crops. (keep an empty space in center of area)
2. [Second step]
Use acceleration wand from "Not Enough Wands" Mod on the Growth Crystals.
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 
![screenshot 12](https://user-images.githubusercontent.com/45643124/49551680-cbfe2680-f8b5-11e8-95e0-db33062af97a.png)

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
Version - 1.0.31
**Where did this bug happen:** [Single Player or Server]
Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Im confused to why your reporting a issue for the stone block mod pack on the Space Astronomy 2 mod pack issue tracker lol i think you derped
