### ISSUE TITLE
Placing 2 display screens together will create a crashzone

### ISSUE THREAD

**Issue by whyoucreepin100** [MJRLegends/Space-Astronomy-2-Feedback-#287]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
Placing 2 display screens next to each other crashes the game

### Steps to Reproduce Issue
1. Place 1 display screen down
2. Place/push another screen onto it while both are on and it will create a crash zone

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
https://pastebin.com/Dz76AFFB
**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
4.0.1.184
**Where did this bug happen:** [Single Player or Server]
Server
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You are reporting a bug without posting a crash log. So i can't fix it so im closing this. If you do decide to post the crash log it will be reopened

**Comment by MJRLegends** [comment]
This is a known issue. Thanks

**Comment by MJRLegends** [comment]
Also when your reporting a bug next time plz make sure to include the crash log from this pack. As you've included a  crash log showing only a few mods installed which one isnt even in the pack. It just so happens this time your lucky and i already know of the issue and dont have to do investigating to find the issue

**Comment by MJRLegends** [comment]
Ah ok from looking at your crash log more it seems your using the new GC version that i thought this was fixed it. So yeah. Plz actually include the crash log you got from this pack and i will reopen
