### ISSUE TITLE
Mod no lunching 

### ISSUE THREAD

**Issue by oldmanrob** [MJRLegends/Space-Astronomy-2-Feedback-#288]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Mod keeps craching on luncher
The game crashed whilst initializing game
Error: java.lang.OutOfMemoryError: Initializing game

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player
[crash-2018-12-22_15.43.33-client.txt](https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/files/2705765/crash-2018-12-22_15.43.33-client.txt)
]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
As the crash log says out of memory. You need to assign more to the launcher.

**Comment by oldmanrob** [comment]
I have 16gb of ram how much more do I need

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MJRLegends** [comment]
5 gb minimum assigned to the twitch app

**Comment by MJRLegends** [comment]
Just because you have 16gn doesnt mean Minecraft has access to it all. Java has pre assigned ram otherwise is will eat all your ram

**Comment by oldmanrob** [comment]
Ok thank you for getting back to me.
but is there anything I can do to fix this issue or is it just potluck if one can play the mod pack

Many thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MJRLegends** [comment]
Yes assign more to the launcher

**Comment by oldmanrob** [comment]
Ok thank you, is there any YouTube channel you can recommend as I'm a newbie when it comes to doing this type of computing

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
