### ISSUE TITLE
Space Astronomy Crashes on Start

### ISSUE THREAD

**Issue by RingoRage** [MJRLegends/Space-Astronomy-2-Feedback-#289]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
[When opening the launcher for space astronomy 2 versions 1.5.1 to 1.5.5 and pressing play, the game instantly crashes. (Not sure if this is an issue that comes with Mac)]

### Steps to Reproduce Issue
1. [Tried increasing RAM from 3GB to 4GB and then to 5GB just to check]
2. [Looked through issues and tried reinstalling other versions but does not work]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
[latest.log](https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/files/2716635/latest.log)

**Screenshots (if applicable):** 
![screen shot 2018-12-29 at 10 44 59 am](https://user-images.githubusercontent.com/46247756/50541274-d9c26700-0b56-11e9-92cc-8e9a5e1b363a.png)

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.5.5 (but same issue occurred in versions 1.5.1-1.5.4)]

**Where did this bug happen:** [Single Player]

### Additional Information
[Is this an issue that comes from playing on Mac?]

**Comment by MJRLegends** [comment]
Try reinstalling the whole mod pack make sure to backup your saves beforehand

**Comment by RingoRage** [comment]
it gave me a new error after reinstalling
![screen shot 2018-12-29 at 1 45 26 pm](https://user-images.githubusercontent.com/46247756/50542334-1189d880-0b70-11e9-85af-b6b103b64e01.png)

**Comment by RingoRage** [comment]
as it turns out...im now getting that message for every one of the packs I have on twitch...I would really appreciate some guidance on how to fix this.

**Comment by RingoRage** [comment]
I am still getting the same error. Is there anything else I could try to fix it?

**Comment by MJRLegends** [comment]
please contact twitch support this isnt a mod pack issue

**Comment by RingoRage** [comment]
I found the issue. My Java version was too new. I just went back a version and the problem was fixed. I can open up and play Space Astronomy again!
