### ISSUE TITLE
Broken Recipe (Furnace Generator)

### ISSUE THREAD

**Issue by Sidetrack15** [MJRLegends/Space-Astronomy-2-Feedback-#29]
### ---Issue Report---

Extra Util Furnace Generator Not Craftable/not in NEI

### Description of Issue
Their doesn't seem to be a way to craft the furnace generator which then makes it impossible to craft any other generator from extra util.  Was this intentional?

### Steps to Reproduce Issue
1. Search for recipe in NEI.  Not there.
2. Search for recipe online and attempt to craft anyway.  Doesn't work.

**Version of Mod Pack using:** 
1.1.0 Beta

**Comment by MJRLegends** [comment]
Its disabled you dont need to craft it

**Comment by MJRLegends** [comment]
(this intentional)

**Comment by Sidetrack15** [comment]
When I saw simple generators installed I wondered if that's what it was.  Any particular reason you chose that over the generators included in extra Ulil?  

Do you have a spot that lists disabled recipes?  I looked but couldn't find anything.
