### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by pmcma2271** [MJRLegends/Space-Astronomy-2-Feedback-#290]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
When initializing the game it fails on step 7

### Steps to Reproduce Issue
1. Launch through twitch launcher
2. press play

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

[PASTEBIN](https://pastebin.com/mw5aGJnm)

> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.5.5
**Where did this bug happen:** [Single Player or Server]
Initialization
### Additional Information
[Any other information that may be able to help me with the problem]
It seems to be client side, but do you mind looking through the crashlog and giving any tips?

**Comment by MJRLegends** [comment]
This is a general java crash not a minecraft/mod pack related server im unable to help you sorry

Please see https://www.google.com/search?q=Failed+to+write+core+dump.+Minidumps+are+not+enabled+by+default+on+client+versions+of+Windows
