### ISSUE TITLE
Server folders name issue due to curseforge download system adding +'s

### ISSUE THREAD

**Issue by itram2001** [MJRLegends/Space-Astronomy-2-Feedback-#291]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Through the files I have, which I downloaded through CurseForge, I can't create all the necessary files for the server. 

### Steps to Reproduce Issue
1. Execute ServerStart/forge-1.10.2-12.18.3.2511-universal
2. The window created when I execute ServerStart creates the following lines: https://pastebin.com/kfy8idrD
3. The window created when I execute forge-1.10.2-12.18.3.2511-universal does not create any lines

**Crash log/Log (if applicable):** [https://pastebin.com/kfy8idrD]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
Not applicable since there is no crash
**Screenshots (if applicable):** 
https://imgur.com/gallery/BoweGeP

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [v1.5.5]

**Where did this bug happen:** [Server]

### Additional Information
[server.properties is empty, eula.txt is set to true]

**Comment by MJRLegends** [comment]
Remove the files from the folder with the +'s in the folder name
