### ISSUE TITLE
When placing a solar generator (or advanced) in a crafting station it crashes

### ISSUE THREAD

**Issue by xMatze97x** [MJRLegends/Space-Astronomy-2-Feedback-#292]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
When placing a solar generator (or advanced) in a crafting station it crashes

### Steps to Reproduce Issue
1. Place a crafting station
2. Put a solar generator from mekanism in the station

**Crash log/Log (if applicable):** https://www.evernote.com/l/AldQx5O8h4dHtZO58OC_oRiy3ez4qBore0Q/

> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.5.5]

**Where did this bug happen:** [Single Player and Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You have edited the pack

`    PackGuard: ADDED: forestry v5.2.17.388, ADDED: morebees v1.10.2-1.4.1,`

so your bug report is void/and wont be looked at sorry
