### ISSUE TITLE
Need Nether resources to get to Nether

### ISSUE THREAD

**Issue by StarSailorXIV** [MJRLegends/Space-Astronomy-2-Feedback-#293]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
[I'm trying to get to the Nether, however flint and steel requires actual steel. I can't use immersive engineering because a blast furnace needs blaze powder. I can't use IC2 because there are no universal fluid cells to put air in the IC2 blast furnace. Also, all other methods of creating steel (tinkers construct alloying, railcraft, etc.) have been overwritten by NeoTech. This seems circular and impossible to accomplish.]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [v1.5.5]

**Where did this bug happen:** [Server]

### Additional Information
[Maybe updating to newest version of Tinkers Construct would help? It has an easier way to alloy steel in the smeltery.]

**Comment by MJRLegends** [comment]
You can do it with meknism https://wiki.aidancbrady.com/wiki/Steel_Ingot

**Comment by StarSailorXIV** [comment]
Awesome, thanks!
