### ISSUE TITLE
Can't craft Aluminum Ingot form GalactiCraft

### ISSUE THREAD

**Issue by EGuitar51** [MJRLegends/Space-Astronomy-2-Feedback-#294]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[For building the Falcon 9 Rocket from the SpaceCraftX-Mod you need to craft compressed Lithium-Aluminium (plates with compressor). These Plates are crafted with the Aluminium-Ingots form GalactiCraft only (Galacticraft Core say's NEI)(other ingots like Immersive Engineering Aluminium-Ingots don't work). The GalactiCraft-Ingots itself are not craftble.

### Steps to Reproduce Issue
1. put Aluminium-Ingots form different Mods with lithium ingots together in a compressor
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/
**Did'nt crash.

**Screenshots (if applicable):** 
![2019-03-26_16 32 24](https://user-images.githubusercontent.com/48957480/55010783-1d592f80-4fe5-11e9-9bb9-370208d6287c.png)

![2019-03-26_16 32 38](https://user-images.githubusercontent.com/48957480/55010791-22b67a00-4fe5-11e9-802f-f525ee5ced26.png)

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):**
V1.5.5

**Where did this bug happen:** [Single Player or Server]
Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Confirmed defo a issue, will see what i can do. might have to be a custom mod to fix it

**Comment by MJRLegends** [comment]
Added a simple crafting recipe to get this issue fixed, not the best thing but trying to tie up a few lose ends for this pack 

![](https://i.gyazo.com/807545617868f4e025a604d51b105e30.png)

**Comment by MJRLegends** [comment]
Update being released now
