### ISSUE TITLE
Sounds stopping when Alt+Tabbing

### ISSUE THREAD

**Issue by joserobjr** [MJRLegends/Space-Astronomy-2-Feedback-#295]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Which mod disables the sound when we change the window? I would like to have the sounds playing normally even when Minecraft is not focused

### Steps to Reproduce Issue
1. Open the game
2. Let some music play
3. Alt+Tab to an other window

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** v1.5.6

**Where did this bug happen:** Single Player

### Additional Information
It´s a question, not a bug. I just would like to revert this behaviour in my setup.

**Comment by MJRLegends** [comment]
Idk which mod it is sorry
