### ISSUE TITLE
Crash with digital miner/item conduits/dimensional transiever

### ISSUE THREAD

**Issue by Tskillz7799** [MJRLegends/Space-Astronomy-2-Feedback-#297]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
[Description of the issue]
Loading the chunk in the screenshot below with the digital miner with ender io item conduits hooked up to dimensional trans. automatically crashes my server or game. My character is currently trapped in this section of the server, and we know its this chunk, because my other friend can log in and play fine on a different chunk literally 300 blocks away.

### Steps to Reproduce Issue
1. [First step]
Start Server
2. [Second step]
Load chunk that contains digital miner with ender io item conduits hooked up to dimensional trans.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

https://pastebin.com/d2hkycxB

**Screenshots (if applicable):** 
https://gyazo.com/4d9dfb93fb7053720ab8f6cf983f4e01

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
V1.5.6

**Where did this bug happen:** [Single Player or Server]
Server and single player (tried copying the world over)

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by Tskillz7799** [comment]
Also forgot to add, the miner worked for a while, but this started happening randomly after another server launch whenever we tried to load the chunk.

**Comment by MJRLegends** [comment]
I think the chunk is messed up and is causing the high tick time causing things to break
