### ISSUE TITLE
Natura: potato bag

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-2-Feedback-#3]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
potato bag somehow become 9 carrots when  you look in JEI
and Carrots bag can't return to carrots 

### Steps to Reproduce Issue
http://imgur.com/a/LEm3y
http://imgur.com/a/QAuib

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Fixed in v1.0.8 Beta
