### ISSUE TITLE
Colossal Chest adding random items to my bag

### ISSUE THREAD

**Issue by bizzy401** [MJRLegends/Space-Astronomy-2-Feedback-#30]
### Description of Issue
I have a 3x3x3 Chest with a little more than 100 items in it. When ever I open it it just starts slowley adding random items to my bag.

### Steps to Reproduce Issue
1. build CC 3x3x3
2. add around 100 items then open the chest

**Version of Mod Pack using:** Mincraft - 1.10.2  CC 1.6.0

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
bag?? from what mod, or do you mean inventory?

**Comment by MJRLegends** [comment]
do you mean inventory?

**Comment by MJRLegends** [comment]
and do you mean when you scroll up and down it adds items to your inventory?

**Comment by MJRLegends** [comment]
If both my questions are correct this is going to be fixed in the next version which is out very soon, please let me know ASAP if this is not your issue i said about above

**Comment by MJRLegends** [comment]
Im going to close this as i think this must be the issue so i will reopen if you say its different :D
