### ISSUE TITLE
Server Crashing on Startup

### ISSUE THREAD

**Issue by BayonDeGalice** [MJRLegends/Space-Astronomy-2-Feedback-#304]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**
Yes

### Description of Issue
Server Crashing on Startup For no reason

### Steps to Reproduce Issue
1. Turn on the server
2. Server crash

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
[](http://pastebin.fr/57411)

**Screenshots (if applicable):** 
None

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):**
v1.5.6

**Where did this bug happen:**
Server

### Additional Information
[Any other information that may be able to help me with the problem]
My server is install in MTXServ .

**Comment by MJRLegends** [comment]
Not sure why you have reported a crash without the crash log seems a bit silly?

**Comment by MJRLegends** [comment]
Im unfortunately not able to do magic to read why your server isnt working. Once you post the crash log i will be able to help more

**Comment by BayonDeGalice** [comment]
I have that it's good for you ?

and I'm sorry I'm not good with a crash log

http://pastebin.fr/57414

http://pastebin.fr/57411

**Comment by MJRLegends** [comment]
Dont see anything wrong here so im closing this
