### ISSUE TITLE
lancher crash

### ISSUE THREAD

**Issue by y40775568** [MJRLegends/Space-Astronomy-2-Feedback-#305]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes
### Description of Issue
[Description of the issue]
After click play and to the loading screen,then the Minecraft will be crash and go back to the launcher shows the crash report
### Steps to Reproduce Issue
Start launcher and then crash

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/
https://pastebin.com/ExV3nT9X
**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
V1.5.6
**Where did this bug happen:** [Single Player or Server]
Single Player
### Additional Information
[Any other information that may be able to help me with the problem]
I have to try to reinstall again but still, have to crash

**Comment by MJRLegends** [comment]
#247
