### ISSUE TITLE
Material in Inventory Crafting is invisible bug

### ISSUE THREAD

**Issue by Kraffty83** [MJRLegends/Space-Astronomy-2-Feedback-#31]
**Version of Mod Pack using: v1.1.2 Beta

**Comment by MJRLegends** [comment]
Please dont just delete the template

### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Fixed in v1.1.3 Beta
