### ISSUE TITLE
Game crasher in luche

### ISSUE THREAD

**Issue by oldmanrob** [MJRLegends/Space-Astronomy-2-Feedback-#310]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] YES

### Description of Issue
Lucher crashing

### Steps to Reproduce Issue
1. start game in twech
2. crash on setup 

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to g
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/
https://pastebin.com/5UTZhe3j

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.5.6

**Where did this bug happen:** [Single Player or Server] Single player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by oldmanrob** [comment]
Hi MJELegeand
is there anyway i can fix this plz 
many thanx
