### ISSUE TITLE
can't join my own server

### ISSUE THREAD

**Issue by livinlike** [MJRLegends/Space-Astronomy-2-Feedback-#311]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]

when I try to load onto my own server; I crash. I was able to play the previous night.

### Steps to Reproduce Issue
1. [First step] 
click join server
2. [Second step]
wait about 1 minute; crash
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]

https://pastebin.com/uCu83VSN

> *How do I locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.7.3 (Beta)
**Where did this bug happen:** [Single Player or Server]
Server
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
v1.5.3 is the latest mod pack version, no idea what your playing dude

**Comment by livinlike** [comment]
1.7.3 is the only version accepted in my server so thats what i used

**Comment by livinlike** [comment]
on twitch they are all beta's, latest is 1.7.7-1.7.10

**Comment by MJRLegends** [comment]
Ahh you have posted this on the wrong mod pack tracker then
