### ISSUE TITLE
railcraft steel has problem

### ISSUE THREAD

**Issue by Blaze-The-Fox** [MJRLegends/Space-Astronomy-2-Feedback-#312]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. Have anvil, mekanismtools steel sword, and railcraft steel
2. Put both in anvil

**Crash log/Log (if applicable):** https://pastebin.com/r16cLGaS

> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.5.6

**Where did this bug happen:** single player

### Additional Information
It happens every time

**Comment by MJRLegends** [comment]
Already on known issues list its number 3 in there. Make sure your checking known issues before your posting
