### ISSUE TITLE
Terrible fps drop when entering inventory

### ISSUE THREAD

**Issue by Ks1999** [MJRLegends/Space-Astronomy-2-Feedback-#313]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**
Yes

### Description of Issue
Fps drops to almost 7 or 8 when entering the inventory screen

### Steps to Reproduce Issue
1. Enter World
2. Open inventory

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.5.7]

**Where did this bug happen:** [Single Player]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Yea remove the blur mod if you get this issue

**Comment by MJRLegends** [comment]
Its due to some people get issues with the mod for some reason.
