### ISSUE TITLE
Mekanism/MCMultipart crashes: java.lang.NullPointerException: Ticking block entity

### ISSUE THREAD

**Issue by RundownRhino** [MJRLegends/Space-Astronomy-2-Feedback-#318]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Random crashes (usually on dimension change or unpausing the game) with an exception "java.lang.NullPointerException: Ticking block entity". Stacktrace mentions mcmultipart and Mekanism.

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.5.7]

**Where did this bug happen:** [Single Player]

### Additional Information

After googling, I found that it's a known MCMultipart issue: [MCMultiPart/issues/71](https://github.com/amadornes/MCMultiPart/issues/71) (logs are identical to mine).
According to dev responses, this will not be fixed in 1.10.2 at all. So... I suppose I'm opening that issue so that it gets added to Common Issues, or so a workaround may be developed somehow.

**Comment by MJRLegends** [comment]
Yea as they said its never being fixed have a good day
