### ISSUE TITLE
The game crashes on startup. V. 1.5.7

### ISSUE THREAD

**Issue by WoxicS** [MJRLegends/Space-Astronomy-2-Feedback-#319]
![Screenshot_19](https://user-images.githubusercontent.com/58013485/69288816-fb0ec480-0bfa-11ea-84e8-9d1e0c7474e8.png)
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] [Yes]

### Description of Issue
[Description of the issue] [The issue is that the game won't launch at all. it simpley won't boot. giving the error message i sent it image format.]

### Steps to Reproduce Issue
1. [First step] [Well. for me is to just start the game and it crashes, so can't even add a second step.]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them] [I don't even have an crash-log folder, in my files. it's probably because it have never successfully booted properly on this PC before.]

> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/ [Tried this link. Ended up on your page. but not fully directed to your crash-log finder, but found it later. sadly didn't help me with finding it.]

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.5.7]

**Where did this bug happen:** [Single Player or Server] [I bet i can leave this one out.]

### Additional Information
[Any other information that may be able to help me with the problem] [Seem to not be dedicated to a specific version 1.5.7, and 1.5.6 seems to have the same problem. and this is a fresh installed version, no changes, no diffrent for any other fresh install. downloaded it off twitch. 2019-11-21.]

**Comment by MJRLegends** [comment]
Nothing to do with me please contact mojang support
