### ISSUE TITLE
Conflicting Recipe

### ISSUE THREAD

**Issue by Hazmatik** [MJRLegends/Space-Astronomy-2-Feedback-#32]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
The mini chest from ExtraUtilities2 cannot be crafted it gives Little Storage Block from LittleTiles mod.

### Steps to Reproduce Issue
1. Try to craft ExtraUtilities2 mini chest

**Crash log/Log (if applicable):** N/A

**Version of Mod Pack using:** 1.1.2 - Beta

**Comment by MJRLegends** [comment]
Will be Fixed in v1.1.3 Beta
