### ISSUE TITLE
Game launch failed

### ISSUE THREAD

**Issue by markusmeridius** [MJRLegends/Space-Astronomy-2-Feedback-#320]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
MC Launcher Error report:
Failed to download file, the file contents differ from what was expected.
Name: jopt-simple-4.6.jar
URL: https://libraries.minecraft.net/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
Filename on disk: jopt-simple-4.6.jar
Path: C:\Users\Erron\Documents\Curse\Minecraft\Install\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar
Exists: File

After trying to launch the pack through the MC launcher I get this error. Closing the error and launching again (the MC client doesn't close at this point) and clicking Play again closes the MC launcher as if it was loading the pack but Task Manager doesn't show Java starting up. Deleted and reinstalled the pack but the error persists.

### Steps to Reproduce Issue
1. Launch SA2 through Twitch launcher
2. Click launch on the MC launcher
3. Error occurs

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** v1.5.7

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Not a mod pack issue its mojangs. Theres nothing to indicate that its my issue so please dont report them to me

**Comment by nordicwolf77** [comment]
I'm getting the same issue. Did you resolve? Only happens with this mod pack and non of the other twitch mod packs
