### ISSUE TITLE
Crash with OptiFine 1.10 HD U H5 after Forge startup initalization

### ISSUE THREAD

**Issue by kylsiis** [MJRLegends/Space-Astronomy-2-Feedback-#321]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
Minecraft crashes right after Forge startup initalization while using OptiFine 1.10 HD U H5, giving this small crash report:
"The game crashed whilst unexpected error
Error: java.lang.VerifyError: Bad local variable type"

### Steps to Reproduce Issue
1. Download and install OptiFine 1.10 HD U H5 on clean modpack installation and launch minecraft.
2. Minecraft crashes after Forge startup initalization in main menu.

**Crash log/Log (if applicable): https://pastebin.com/ZW2K43gb ** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
https://pastebin.com/ZW2K43gb

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
v1.5.7
**Where did this bug happen:** [Single Player or Server]
Single player, while launching minecraft
### Additional Information
I'm currently using Twitch launcher to launch Space Astronomy 2 but I don't think it should have any great effect on this issue.

**Comment by MJRLegends** [comment]
Sorry we dont support optifine as it causes issues when used to mods as its mostly designed with vanilla minecraft in mind. Also even if i wanted to support it, half the mods in this pack dont support optifine and also are never updated anymore
