### ISSUE TITLE
doesnt launch

### ISSUE THREAD

**Issue by mrM6** [MJRLegends/Space-Astronomy-2-Feedback-#322]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes 

### Description of Issue
doesnt open
### Steps to Reproduce Issue
1. i downloaded it from twitch
2. i went to the launcher and launched it
**Crash log/Log (if applicable):** Failed to download file, the file contents differ from what was expected.
Name: jopt-simple-4.6.jar
URL: https://libraries.minecraft.net/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
Filename on disk: jopt-simple-4.6.jar
Path: C:\Users\mahal\Twitch\Minecraft\Install\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar
Exists: File

**Version of Mod Pack using (1.5.7)
**Where did this bug happen:** launcher
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Nothing to do with the pack contract twitch support
