### ISSUE TITLE
my game crashes when almost done loading in

### ISSUE THREAD

**Issue by herogann** [MJRLegends/Space-Astronomy-2-Feedback-#325]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes

[Description of the issue]
alright so when i launch it and wait for it to load up and it crashes at 7 out of 7 and 65 - 91 at the middle one and at the bottom its more than half way but it keeps crashing even with great internet so idk if its broken or its a bug. this mod is named: Space Astronomy 2

**Screenshots (if applicable):** 
![2020-03-27 (2)](https://user-images.githubusercontent.com/62779163/77810922-15532600-7065-11ea-9b82-f22d48156cdc.png)

**Version of Mod Pack 
12.18.3.2511

**Where did this bug happen:
when the launcher is loading in

**Comment by MJRLegends** [comment]
You havent included the crash log instead you just deleted the part of the template that says about it. No help can be given without it

**Comment by MJRLegends** [comment]
Read what it says out of memory assign more ram to launcher
