### ISSUE TITLE
Can't craft / make Tier 1 Armor Layer from Extra planets 

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-2-Feedback-#33]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
When placing the 4 aluminium required in the recipe, in an electric Compressor noting happen

### Steps to Reproduce Issue
1. Place the aluminium in the pattern show in JEI
2. Noting happen

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [1.1.2 beta]

### Additional Information
http://imgur.com/a/IGhx3

**Comment by MJRLegends** [comment]
Will be Fixed in v1.1.3 Beta
