### ISSUE TITLE
wait, freeze, crash, repeat

### ISSUE THREAD

**Issue by harrma** [MJRLegends/Space-Astronomy-2-Feedback-#330]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes ]

### Description of Issue
[crashes someties when first loading mostly when loading defalt world with defalt name (exept I said to add bounus chest] I gave it 5120mb of memory, I can only use 6 for it but that would be pushing it) and 12 render distance. Also all settings are set to performance.

### Steps to Reproduce Issue
1. [doble click game]
2. [wait]
3. click play
4. doble click world
5. wait, freeze, crash, repeat

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/
folder didn't show up
**Screenshots (if applicable):** 
it turned white and said process not responding stopping somthing.exe
**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION] 1.10.2

**Where did this bug happen:** [Single Player or Server]
single player
[latest.log](https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/files/4640789/latest.log)
[log.log](https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/files/4640793/log.log)

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Your not using an official launcher that the pack is on so no help provided sorry also your logs dont show a crash
