### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by Cooljs2002** [MJRLegends/Space-Astronomy-2-Feedback-#332]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
Every time I try to run the modpack, It crashes and I have no idea why

### Steps to Reproduce Issue
1. I install the modpack on twitch (the newest version)
2. I launch the game
3. It starts loading
4. Then right before it brings me to the main menu, it crashes.
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/
https://pastebin.com/aGQBWdFe
**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.10.2
**Where did this bug happen:** [Single Player or Server]
Both? It wont even load up all the way before it crashes
### Additional Information
It says to remove foamfix but I already tried that. It doesn't change anything. It's only on this modpack too. I can play any other modpack without running into this problem.

**Comment by MJRLegends** [comment]
Add more ram to your launcher
