### ISSUE TITLE
RFTools Haste Module uncraftable

### ISSUE THREAD

**Issue by vlekje513** [MJRLegends/Space-Astronomy-2-Feedback-#336]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
YES
### Description of Issue
[Description of the issue]
Can't craft RFTools Haste Module.
### Steps to Reproduce Issue
1. Enchant a diamond pickaxe with Enchanting Plus with Efficiency III
2. Try to combine it in the crafting table.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 
https://gfycat.com/pleasingserenearmyworm
**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.5.7
**Where did this bug happen:** [Single Player or Server]
Server, hosted locally
### Additional Information
[Any other information that may be able to help me with the problem]
regular diamond pickaxe also didnt work

**Comment by MJRLegends** [comment]
Fixed in v1.5.8+ of the pack
