### ISSUE TITLE
AstralSorcery worldskyhandler crash

### ISSUE THREAD

**Issue by vlekje513** [MJRLegends/Space-Astronomy-2-Feedback-#337]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
Random crash (3x)

### Steps to Reproduce Issue
1. Boot up my world
2. Wait and it'll probably crash in time

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/
https://pastebin.com/H4BcTfi2
https://pastebin.com/WBB39HwY
https://pastebin.com/MnpQF3Yr

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.5.7
**Where did this bug happen:** [Single Player or Server]
Server hosted locally
### Additional Information
[Any other information that may be able to help me with the problem]
Seemingly random, started only occuring later. I don't think any of my friends did anything with astral sorcery either.

**Comment by MJRLegends** [comment]
Known issue can be found here https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/issues/99
