### ISSUE TITLE
IndustrialCraft 2 Dusts not smelting into ingots

### ISSUE THREAD

**Issue by meadowsjustin** [MJRLegends/Space-Astronomy-2-Feedback-#338]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes.

### Description of Issue
I set up an ore processing chain with macerators, ore washing plants, and thermal centrifuges. However, when the dusts of the ores are obtained, they do not smelt in any furnace (including vanilla furnaces) despite NEI offering a smelting recipe.

### Steps to Reproduce Issue
1. Obtain IC2 dust.
2. Attempt to smelt the dust into ingots.

**Screenshots (if applicable):**
![silver dust](https://user-images.githubusercontent.com/55884692/97487109-cc34be80-1932-11eb-89d5-6e217eae069f.png)
![gold dust](https://user-images.githubusercontent.com/55884692/97487115-cfc84580-1932-11eb-9c13-561633e9d05b.png)
![alloy smelter showing recipe](https://user-images.githubusercontent.com/55884692/97487126-d2c33600-1932-11eb-8aa4-ba8380d4b246.png)
![silver dust will not go into alloy smelter](https://user-images.githubusercontent.com/55884692/97487136-d5259000-1932-11eb-892a-40f8c4b6618b.png)
 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** v1.5.6 on Minecraft version 1.10.2 available on Twitch

**Where did this bug happen:** [Single Player or Server]
Server

### Additional Information
Ores and other items smelt normally, as do purified crushed ores.

**Comment by meadowsjustin** [comment]
Edit: Dusts smelt into molten metal in a Tinker's Construct forge, however I don't want to have to automate that as well 😅

**Comment by MJRLegends** [comment]
how did you get IndustrialCraft 2 Dusts?

**Comment by MJRLegends** [comment]
https://i.gyazo.com/8104cbf7cfa8ef3c05abd0a7f99cfaea.mp4 use this.
