### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by techwarfare** [MJRLegends/Space-Astronomy-2-Feedback-#339]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes I have found one that was closed but the advice given did not help.

### Description of Issue
Well a fresh install of the mod packs server (1.5.7), results in errors being thrown and a crash.

### Steps to Reproduce Issue
1. Download fresh 1.5.7 mod pack
2. Try and run the start batch file
3. Wait till it shoots errors

**Crash log/Log (if applicable):**
https://pastebin.com/jGDBgEpv

**Screenshots (if applicable):** 
https://cdn.discordapp.com/attachments/770806165831286804/786459358690017281/unknown.png

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.5.7

**Where did this bug happen:** [Single Player or Server]
Server

### Additional Information
I have no more information regarding the issue other than I'm running java 8 version 271.

**Comment by MJRLegends** [comment]
Looks like where ever you are saving the files isnt allowing minecraft to have permission to do write or change files

**Comment by MJRLegends** [comment]
Also your screenshot shows a different error and that error you need to remove +'s from folder name
