### ISSUE TITLE
Recipe Conflict between 2 obsidian axes

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-2-Feedback-#34]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Im unable to craft the 2 different obsidian axes, one from tiny progressions and actually additions

### Steps to Reproduce Issue

1. When crafting 2 different obsidian axes they have the same recipes so im unable to make them both

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** 1.1.2 beta
### Additional Information
None

**Comment by MJRLegends** [comment]
Yeah, theres two but hows that a bug?

**Comment by MJRLegends** [comment]
Will be Fixed in v1.1.3 Beta
