### ISSUE TITLE
"Unexpected error" with mods not from this modpack

### ISSUE THREAD

**Issue by Jeremy5909** [MJRLegends/Space-Astronomy-2-Feedback-#342]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]
When I start the game, an error occurs saying: "An unexpected issue has occurred and the game has crashed. We're sorry for the inconvenience"
### Steps to Reproduce Issue
1. [First step] Use these mods: https://share.vidyard.com/watch/Lk9kxngCLAusJ3ZQCdNxM3?vyetoken=$token_placeholder&autoplay=1
2. [Second step] Launch the Game

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them] No crash report?
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 
![image](https://user-images.githubusercontent.com/52727624/104137722-2a7f1400-535c-11eb-81ef-19548d5b04e7.png)

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
Modpack + other mods: 
https://share.vidyard.com/watch/Lk9kxngCLAusJ3ZQCdNxM3?vyetoken=$token_placeholder&autoplay=1

**Where did this bug happen:** [Single Player or Server] Start of game

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please include the crash log, i cant look at your issue any more without it

**Comment by MJRLegends** [comment]
How do i locate a crash log see https://docs.mjrlegends.com/Minecraft/crash-log/
