### ISSUE TITLE
bug when log in

### ISSUE THREAD

**Issue by alexguay43** [MJRLegends/Space-Astronomy-2-Feedback-#35]
![minecraft 2017 07 05 - 12 10 34 01](https://user-images.githubusercontent.com/24687820/27873788-4c72e0d6-617b-11e7-862e-2373278554d2.png)

**Comment by MJRLegends** [comment]
This isnt a bug you just are not using the right version of the pack to join that server.

**Comment by alexguay43** [comment]
i use the last

**Comment by alexguay43** [comment]
![twitch 2017-07-05 12_18_01](https://user-images.githubusercontent.com/24687820/27874015-0aedc364-617c-11e7-8efa-244032d2bc3c.png)

**Comment by MJRLegends** [comment]
Your using the wrong version, just because there's a update doesnt mean the servers your joining is using it yet, i dont own any servers so idk what version they are using. You need to find out from who ever server is it.
