### ISSUE TITLE
Ender Ore is not in the Ore Dictionary

### ISSUE THREAD

**Issue by bizzy401** [MJRLegends/Space-Astronomy-2-Feedback-#36]
### ---Issue Report---
Since Ender Ore is not in the Ore Dictionary (the tooltip says, "None") you can't get it with the Digital Miner.

**Version of Mod Pack using:** 1.1.2 -Beta

**Comment by MJRLegends** [comment]
You can you just use the itemstack/block to configure it, also as i already said to you please dont just delete the template and post little information

**Comment by MJRLegends** [comment]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]
