### ISSUE TITLE
mekanism chemical dissolution chamber 

### ISSUE THREAD

**Issue by illegalevil** [MJRLegends/Space-Astronomy-2-Feedback-#37]
### ---Issue Report---
the chemical dissolution chamber is not allowing to take in its gases and not outputing through cables
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
the chemical dissolution chamber is not allowing to take in its gases and not allowing to output its ore slurry through a cable or should i say any cable can't connect to excpt a pressure cable from the mod itself
### Steps to Reproduce Issue
1. get a chemical dissolution chamber the get a gas tank or machine that makes sulfuric acid
2. try to connect to it and input the acid through a cable then try to output whatever is in the thing through a cable

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Guessing you fixed it?
