### ISSUE TITLE
[Suggestion/Discussion] Garden Cloche + Mystical Agriculture is a bit broken

### ISSUE THREAD

**Issue by fairyhell** [MJRLegends/Space-Astronomy-2-Feedback-#39]
I think we need a little balance for these 2 mods in the pack.

I have 2 IE Watermills running and they're enough to power 10 Cloches.
The Cloche itself requires little power and with bone meal, they grow is REALLY fast. 
With a little bit of automation crafting from Refined Storage, you can get everything you need in a little garden with little power required.

Compare this to Quarry or any other auto-mining for resources, It's definitely a lot cheaper which is why I think it's broken.

That's my thoughts, and I don't know where to post this so hope you don't mind it stay here.

**Comment by MJRLegends** [comment]
Garden Cloche is being removed from being able to be crafted due to many issues with it
