### ISSUE TITLE
Can't make Iron Casing from Rockhounding Mod: Chemistry

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-2-Feedback-#4]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
according to JEI it need 4 iron in a crafting table should become 8 Iron Casing , but it do not show up anything 

### Steps to Reproduce Issue
1. [First step]
Place 4 iron according to the recipe
2. 
Noting happen

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** 1.0.7 beta

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Fixed in v1.0.8 Beta
