### ISSUE TITLE
mekanism factory blocks

### ISSUE THREAD

**Issue by illegalevil** [MJRLegends/Space-Astronomy-2-Feedback-#41]
### ---Issue Report---
the mekanism not logistical not pulling items from other inventories
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
the logistical pipes in mekanism don't pull items from chest or other kinds of inventories and other cables like enderIO can't input into the factory machines 

### Steps to Reproduce Issue
1. get a chest then a logistical pipe 
2. then get a elite purifying block  and connect the cables to it 

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Im pretty sure thats just not a feature more than a bug

**Comment by illegalevil** [comment]
well it use to work like that in 1.7.10

**Comment by MJRLegends** [comment]
![2017-07-10_01 09 06](https://user-images.githubusercontent.com/8526321/27998786-6597f5a8-650c-11e7-858a-b971724f69f9.png)
Use the Configurator to change the cable ends and it works then :D
