### ISSUE TITLE
Fps drop on any user interface

### ISSUE THREAD

**Issue by H3CTICOG** [MJRLegends/Space-Astronomy-2-Feedback-#42]
### ---Issue Report---
Any time I open up a interface (even my inventory or crafting table) my frames drop to 3 or 4 fps. Normal gameplay outside of this is perfectly fine. No lag or rendering issues except when I pull up an interface. Any solution to this? Doesnt cause any crash either just becomes super annoying!
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of th3e issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
see #38
