### ISSUE TITLE
Server 

### ISSUE THREAD

**Issue by TheDeathArrowMC** [MJRLegends/Space-Astronomy-2-Feedback-#43]
### ---Issue Report--- 

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes
### Description of Issue
[Description of the issue]
cant connect to server

### Steps to Reproduce Issue
1. [First step] 

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Connect to what server?
