### ISSUE TITLE
Galacticraft Display Screen Crashes Game

### ISSUE THREAD

**Issue by feuerball11** [MJRLegends/Space-Astronomy-2-Feedback-#44]
[Description of the issue]
If you place an Display Screen from Galactic Craft in the World, The Game, or Server crashes.

### Steps to Reproduce Issue
1. Load a new World
2. Cheat yourself an Display Screen from Galactic Craft
3. Place the Screen
4. It Crashes

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/EzmNBdFE

**Version of Mod Pack using:**
testet on 1.1.3 and 1.1.4 -> Both Crashes

**Comment by MJRLegends** [comment]
Ive reported it to the developers

**Comment by radfast** [comment]
Hey @feuerball11, I'm one of the Galacticraft developers.

1.  Which world / planet are you placing this Display Screen in?

2.  Please can you post up your Galacticraft ```core.conf``` and ```planets.conf``` from the ```.minecraft/config/Galacticraft``` folder - **please post these config files from both client and server**.  I'm interested to look at whether somehow they don't match.

**Comment by feuerball11** [comment]
1. Its just in the Overworld. Where still in early stage of the Modpack. The only thing we have is a small base on the moon. But didnt tested the Screens there, couse they dont even work on Earth O.o 

2. Comming in a few minutes...

**Comment by radfast** [comment]
The Galacticraft configs look OK.

Testing this in Galacticraft alone (+ a handful of other common mods I keep installed: today it's Biomes o'Plenty, Buildcraft and Thermal Foundation/Thermal Expansion) there is no problem with the Display Screen.

It must be something else in the Space Astronomy modpack causing this (possibly including ExtraPlanets).  I think best if @MJRLegends figures this out.

**Comment by MJRLegends** [comment]
*Space Astronomy 2

**Comment by feuerball11** [comment]
If i can help in any way, just let me know. I'll have this thread open more then once a day ;-)

**Comment by MJRLegends** [comment]
@feuerball11 ok, i have just tested it myself and yeah it crashes for me too, i should be able to find the problem mod :D cc @radfast

**Comment by MJRLegends** [comment]
@feuerball11 ok I have found the issue mod, and hopefully it can be fixed :D

**Comment by feuerball11** [comment]
Just out of intrest: What are the conflicting Mods?

**Comment by MJRLegends** [comment]
see https://github.com/micdoodle8/Galacticraft/issues/2891

**Comment by chezpaul** [comment]
Got it
Thanks
