### ISSUE TITLE
Game freezes every few seconds

### ISSUE THREAD

**Issue by Frogliza** [MJRLegends/Space-Astronomy-2-Feedback-#45]
### ---Issue Report---
I have checked closed issues and did not notice the same issue anywhere.
### Description of Issue
The game freezes at 0 fps every few seconds and unfreezes 1-2 seconds later.  I have 4GB of RAM allocated to the launcher.
### Steps to Reproduce
1. Create World
2. Play and wait for freezes

**Version of Mod Pack using:** [V1.1.4]

**Comment by TrelLyX** [comment]
Switch to 6GB of ram fixed this :D This modpack need more Ram :O look on F3, on your Ram using.

**Comment by jbgrog** [comment]
optifine

**Comment by MJRLegends** [comment]
Yeah the comments above should help you out with fps but do note optifine isnt supported
