### ISSUE TITLE
No starting Items on server.

### ISSUE THREAD

**Issue by Arnaen** [MJRLegends/Space-Astronomy-2-Feedback-#46]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 

Yes

### Description of Issue

I have deleted the player data, the server re-setup. 
I also tried to login with my 2nd account.
But do not get starting items.

**Version of Mod Pack using:
testet in
1.1.1
1.1.2
1.1.3
1.1.4

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Not my issue i own the mod pack not any servers sorry

**Comment by Arnaen** [comment]
Do you not you also provide the server data? (on curse)
