### ISSUE TITLE
Iron Backpack Issue

### ISSUE THREAD

**Issue by RussianSanity** [MJRLegends/Space-Astronomy-2-Feedback-#47]
Pack: Space Astronomy 2 (1.10.2)
Mod: Iron Backpacks 
Issue: Duping
Version of Pack: 1.1.4 Beta 

Steps to Reproduce:
1: Place what you want to dupe inside the backpack.
2: As you go to open (right-click) the backpack, hit Q to drop it. It leaves a phantom Gui open to take whatever item was placed inside. 
3: Pick up backpack on the ground, open it, take original item out and continue duping. 
It takes quite a number of times before you can properly do this. For me it took about 10 times

**Comment by MJRLegends** [comment]
Seems its a reported bug https://github.com/gr8pefish/IronBackpacks/issues/176

**Comment by MJRLegends** [comment]
Will be fixed in v1.1.9
