### ISSUE TITLE
Chunk borders do not go away

### ISSUE THREAD

**Issue by Frogliza** [MJRLegends/Space-Astronomy-2-Feedback-#48]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
The chunk borders do not go away once activated with F3 + g. It says chunk borders hidden in the chat but they do not go away.
### Steps to Reproduce Issue
1. Load world
2. Hit F3 + g to show chunk borders
3. Hit F3 + g to hide them

**Version of Mod Pack using:** [1.1.4]

**Comment by MJRLegends** [comment]
Press F9
