### ISSUE TITLE
mystical Agriculture

### ISSUE THREAD

**Issue by bl4d3fiir3** [MJRLegends/Space-Astronomy-2-Feedback-#49]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]
There is a problem when crafting tier 2 seeds they wont plant in the ground little bit of a  problem, Some of the items in JEI are not working and present error,  also why is applied energetics 2 not in the pack

**Comment by MJRLegends** [comment]
You need to make the tier 2 seeds the normal ones not the tier 2 crafting seeds, please reopen this issue if you still have issues. Screenshot would help a lot if you still have issues :)
