### ISSUE TITLE
Recipe conflict, iron nugget and crusing gear from rockhounding mod chemistry

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-2-Feedback-#5]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
one iron should become one crusing gear from rockhounding mod chemistry
but can only make iron nuggets

http://imgur.com/a/5xqgp
### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** 1.0.7 beta

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Fixed in v1.0.8 Beta
