### ISSUE TITLE
Quantum Solar Panel

### ISSUE THREAD

**Issue by bdspark** [MJRLegends/Space-Astronomy-2-Feedback-#50]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING): Yes
### Description of Issue
From Industrialcraft2 mod the quantum solar panel produce at day time 4096 eu/t but the output is 2048 eu/t which is not correct coz it should do output 4096eu/t as well because 8 ultimate hybrid solar need to make 1 quantum. and 8 ultimate hybrid solar produce 4096eu/t at day time. I think this is bug.

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [1.1.4]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by Spellkaze** [comment]
Change the advanced_solar_panels.cfg:

I:QuantumSPTier=4 to I:QuantumSPTier=5 .

For some reason the mod gives it like that by default, dunno if is intentional or just a mistake.

**Comment by MJRLegends** [comment]
@Spellkaze thanks :D it will be fixed in v1.1.6
