### ISSUE TITLE
Crash when opening Astral Sorcery book on new world

### ISSUE THREAD

**Issue by DeadlyAccurate** [MJRLegends/Space-Astronomy-2-Feedback-#51]
I created a new singleplayer game and as soon as I tried to read the Astral Sorcery book, my game crashed. Removing the Astral Sorcery mod eliminated the crash.

**Comment by MJRLegends** [comment]
Please provide the crash log....

**Comment by DeadlyAccurate** [comment]
I don't actually have it, unfortunately. I ended up starting a new world altogether and deleting the old content. Sorry. If you can't recreate it, it may just be on my end. I just figured I'd report it in case.

**Comment by MJRLegends** [comment]
Ok no problem
