### ISSUE TITLE
Filled Canister of Liquid Oxygen disappear when used to refill heavy Oxygen tank

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-2-Feedback-#54]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
When refilling a heavy Oxygen tank, you do not get Canister of Liquid Oxygen back

### Steps to Reproduce Issue
1. Place a not full heavy Oxygen tank in a your hud crafting grid together with Canister of Liquid Oxygen
2. take out the now filled heavy Oxygen tank, and try to take the Canister of Liquid Oxygen, it now show a 0 beside it and then disappear when try taken 

###Screenshots
![](https://i.gyazo.com/a47d4f6741284cb4d8b78c76da9d0175.png)
![](https://i.gyazo.com/471cb5c71dddaffde24b6a0aeb2e3808.png)
![](https://i.gyazo.com/3ee014acc1a5ebf4bd927bbd1c1c9d48.png)

**Crash log/Log (if applicable):** None
**Version of Mod Pack using:** 1.1.6

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Reported to the mod devs https://github.com/micdoodle8/Galacticraft/issues/2910

**Comment by MJRLegends** [comment]
Will be fixed in v1.1.9
