### ISSUE TITLE
Modpack crash with launching

### ISSUE THREAD

**Issue by KontranRUS** [MJRLegends/Space-Astronomy-2-Feedback-#55]
My log: https://drive.google.com/open?id=0BxjkeM3UWhJUQkdoNkVWdXJtVUE

**Comment by MJRLegends** [comment]
Please dont just delete the template its there to be filled out not deleted...

What GPU are you using?

**Comment by MJRLegends** [comment]
From what i can tell your using a Radeon R9 200 Series GPU which are dated 2013/2014 GPU's in this case you will not be able to run the mod pack and most 1.10.2+ mod packs without a more up to date GPU more 2015/2016+

**Comment by MJRLegends** [comment]
Try adding -Dfml.skipFirstTextureLoad=false to the java arguments.

**Comment by MJRLegends** [comment]
I think the issue is the GPU doesn't have enough graphics memory, which means you could try and research a way to add more or get a virtual amount of more.. im not sure as never needed to do it myself :D sorry

**Comment by KontranRUS** [comment]
Thank you for help me!

**Comment by KontranRUS** [comment]
But i can run older (1.1.6) version of this modpack...  It's a strange...

**Comment by MJRLegends** [comment]
@KontranRUS yeah textures probably have changed, i know my mods in the pack have some new 64x64 images :D

**Comment by MJRLegends** [comment]
also one thing i forgot to suggest is try a lower res 16x16 texture/resource pack

**Comment by KontranRUS** [comment]
Okaaaaay. I just set default minecraft resolution in twich settings and you modpack started :D
