### ISSUE TITLE
Industrialcraft 2 Crop

### ISSUE THREAD

**Issue by XXXTheOnlyOneXXX** [MJRLegends/Space-Astronomy-2-Feedback-#56]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

## Description of Issue
The Crop sticks are broken

### Steps to Reproduce Issue
1. Till dirt
2. Place crop sticks
3. Wait

**Screenshots (if applicable):** 
![2017-07-23_22 53 53](https://user-images.githubusercontent.com/30393653/28502904-8096602e-6ffc-11e7-8fb6-d0ee35ab0ecb.png)
![2017-07-23_22 54 51](https://user-images.githubusercontent.com/30393653/28502905-80ca5f6e-6ffc-11e7-8c1c-73bdd253e55e.png)
![2017-07-23_22 54 58](https://user-images.githubusercontent.com/30393653/28502906-80d2ba74-6ffc-11e7-9007-1a2ed9132f46.png)

**Version of Mod Pack using:** v1.1.7

**Comment by MJRLegends** [comment]
Please fill out this

### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
I will reopen this issue for you when its been updated :D

**Comment by XXXTheOnlyOneXXX** [comment]
---Issue Report---

Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING): [Yes]

Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING): [Yes]
Description of Issue

The Crop sticks are brocken
Steps to Reproduce Issue

    Till dirt
    2.Place crop sticks
    3.Wait

Version of Mod Pack using: [v1.1.7]
Additional Information

I got some pictures for you so you can see see bug
![2017-07-23_22 53 53](https://user-images.githubusercontent.com/30393653/28502904-8096602e-6ffc-11e7-8fb6-d0ee35ab0ecb.png)
![2017-07-23_22 54 51](https://user-images.githubusercontent.com/30393653/28502905-80ca5f6e-6ffc-11e7-8c1c-73bdd253e55e.png)
![2017-07-23_22 54 58](https://user-images.githubusercontent.com/30393653/28502906-80d2ba74-6ffc-11e7-9007-1a2ed9132f46.png)

**Comment by XXXTheOnlyOneXXX** [comment]
how do i delet that one in the wrong forum ?

**Comment by MJRLegends** [comment]
@XXXTheOnlyOneXXX I've sorted it out dont worry, thanks for updating this issue :D

**Comment by MJRLegends** [comment]
Just please make sure future you do fill out the template and with detail otherwise i cant fix the issue and it just looks messy without correct information

**Comment by MJRLegends** [comment]
Will be fixed in v1.1.8 that is out later today, im fixing in the way of removing them so please just delete them :D
