### ISSUE TITLE
EnderIO vials can not capture Cyberware zombies

### ISSUE THREAD

**Issue by bizzy401** [MJRLegends/Space-Astronomy-2-Feedback-#58]
### ---Issue Report---
Yes

### Description of Issue
When holding a Soul Vial right clicking on a Zombie from the Cyberware mod does not capture the mob.

### Steps to Reproduce Issue
1. Hold Soul Vial in hand
2. Approach Zombie from Cyberware mod
3. Rick click Cyberware zombie 

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Screenshots (if applicable):** 

**Version of Mod Pack using:** 1.1.6

**Where did this bug happen:** SA2-1

### Additional Information
I am not sure if this is a bug or intended (or EnderIo just doesn't support Cyberwar)

**Comment by MJRLegends** [comment]
Yeah the pack is made like that :) hope that helps

**Comment by bizzy401** [comment]
Thanks for the quick reply! Well, if this is working as intended then I have to rework my plans...back to the drawing board!!!

**Comment by MJRLegends** [comment]
Yep the idea is you cant farm the zombies in most cases, and you have to find them in the world

**Comment by bizzy401** [comment]
Its cool, this is still the best mod pack ever, I'll find something else to murder in my laser chamber of death, lol.

**Comment by MJRLegends** [comment]
Thank you
