### ISSUE TITLE
Modular Powersuits Hotkeys not working

### ISSUE THREAD

**Issue by bizzy401** [MJRLegends/Space-Astronomy-2-Feedback-#59]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Setting hotkeys in Modular Powersuits seems to have no effect

### Steps to Reproduce Issue
1. Equip Power Chest with Jetpack addon
2. Set Any key to toggle jetpack

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Screenshots (if applicable):** 

**Version of Mod Pack using:** 1.1.6

**Where did this bug happen:** SA2-1

### Additional Information
I may be missing something but I can't seem to get the hotkeys to work. I ensure that the little line is connected in the gui and added the hotkey to the hud to ensure that it was setup correctly.

**Comment by MJRLegends** [comment]
Which keys are you trying? and have they already been assigned to feature in the controls menu on the pause screen of normal minecraft?

**Comment by bizzy401** [comment]
I have tried tons of key, as a test I just tried Left Bracket to no avail. I ensured that it wasn't in the main Keybind settings first.

**Comment by MJRLegends** [comment]
Ok, please try it on single player

**Comment by bizzy401** [comment]
I just tried it in Single player survival and it had the same effect (or lack there of). Tried Left Bracket and could not toggle the Jetpack.

**Comment by MJRLegends** [comment]
ok thanks i will take a look later

**Comment by bizzy401** [comment]
Thank you.

**Comment by MJRLegends** [comment]
Ok i have got it to work, it seems to work when no other feature is set to it, so decide on a key you want but make it a main key like arrows, letters and that and then remove any feature using it in control menu  and it will work :D
