### ISSUE TITLE
Crash when visiting the Asteroids 

### ISSUE THREAD

**Issue by backgtx** [MJRLegends/Space-Astronomy-2-Feedback-#60]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING): yes

### Description of Issue
When you use the Tier 3 rocket to go to the planet asteroids the game close

### Steps to Reproduce Issue
1. Just go to the planet
2. Just go to the planet

**Crash log/Log (if applicable):** https://pastebin.com/Bb7vBqJ9
**Screenshots (if applicable):** 

**Version of Mod Pack using:** 1.1.8
**Where did this bug happen:** Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Thanks i will report this to Galacticraft

**Comment by MJRLegends** [comment]
Ok just looked at your issue closer and your not using v1.1.8 according to the crash log but this doesn't related to the bug as its still a bug :D its been reported already by someone else and will be fixed very soon, you could try delete your "GCAsteroidData.dat" in "/saves/WORLDNAME/data/" it might work

**Comment by MJRLegends** [comment]
Reported issue https://github.com/micdoodle8/Galacticraft/issues/2908

**Comment by MJRLegends** [comment]
Will be fixed in v1.1.9
