### ISSUE TITLE
Cannot download pack from Twitch Client

### ISSUE THREAD

**Issue by TheMCProf** [MJRLegends/Space-Astronomy-2-Feedback-#61]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
Whenever I try to download the pack from the Twitch Client, nearing the end of the download, the download stops as it said that the addons do not have a full path. I'm not sure if it's my problem or yours. 
**Version of Mod Pack using:** v1.1.7

**Comment by MJRLegends** [comment]
Please restart launcher if not please contact twitch/curse support
