### ISSUE TITLE
Can u add The Spice of Life? Please )

### ISSUE THREAD

**Issue by akimbaev** [MJRLegends/Space-Astronomy-2-Feedback-#62]
Can u add The Spice of Life? Please , because mod pack have Pam's harvestcraft , and more food, but why should I use it if it makes no sense .

**Comment by MJRLegends** [comment]
Im going to say no for adding that mod, only due to the fact i dont want food to be a hard element in the pack :D, Pam's harvestcraft is there for fun of having different foods :D thanks for the suggestion though

**Comment by akimbaev** [comment]
okey
