### ISSUE TITLE
Crash when using Galacticraft Wires with Mekanism Machines/Blocks

### ISSUE THREAD

**Issue by lucasvip1** [MJRLegends/Space-Astronomy-2-Feedback-#63]
### Description of Issue
This a game breaking crash issue that prevents me from making progress im not sure if it is only the induastrial craft 2 generator that does this but when it happens I can't reload my world. It has taken two worlds from me (It seems that every generator crashes when used with the metallurgical infuser)
Blocks used and tested : (Stirling generator, Industrial generator, Metallurgic Infuser and Aluminum wires

BLOCKS

### Steps to Reproduce Issue
1. Industrial craft 2 basic generator hooked up to metallurgic infuser with aluminum wires
2. POWER the generator with coal wood etc.,,
3. Game Crashes and save is broken

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/z9TnrXHG 
**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]
Latest Version of Space astronomy 2 Version is 1.1.8 
**Where did this bug happen:** [Single Player or Server]
Single PLAYER
### Additional Information
[Any other information that may be able to help me with the problem]
it breaks your save permanent and won't let me load the world again

**Comment by MJRLegends** [comment]
Will be fixed in v1.2.1

**Comment by MJRLegends** [comment]
Will be fixed in v1.2.2

**Comment by MJRLegends** [comment]
Due to Galacticraft not releasing a build yet due to they are busy, this will be in v1.2.3

**Comment by lucasvip1** [comment]
suck my tiny cok
