### ISSUE TITLE
Inventory Resetting Consistently

### ISSUE THREAD

**Issue by 23Scanlon32** [MJRLegends/Space-Astronomy-2-Feedback-#66]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
The night before, I had went mining and had numerous different high tier ores, backpacks, and tinker tools.  The next time I logged in, I saw that my inventory had reset to what it once was a couple of days ago.  Everything I had previously was gone, but the items I put in my chests from the expedition were still there.  I banked what I had and re-logged.  When i logged back in, I had the same exact inventory as before I logged off, and the items I literally just put in the chest were still there.  I am not sure how to fix this issue.  I receive the same inventory every time I re-log onto that world.

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
*How do i to locate a crash log? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]

**Where did this bug happen:** Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Delete your playerdata should fix the issue :D

**Comment by 23Scanlon32** [comment]
Thank you, Legends!  Also, any multiplayer servers up for this yet that you know of?

**Comment by MJRLegends** [comment]
yeah check your server list :D

**Comment by 23Scanlon32** [comment]
Will do!  :D

**Comment by 23Scanlon32** [comment]
I'm having another problem.  So, I decided to use a backup instead, as well as delete player data.  Once I logged into the world, I was back where I was before the inventory glitch.  However, I logged out then re-logged.  The game gave me the inventory I was talking about earlier and also brought me back to a time in the early stages of my world.  What could be causing this issue?

**Comment by MJRLegends** [comment]
Not sure try reinstalling the pack

**Comment by 23Scanlon32** [comment]
I might as well go creative and give myself everything I lost lol

**Comment by 23Scanlon32** [comment]
Thanks for your help man, I really do appreciate it!

**Comment by MJRLegends** [comment]
Ok

**Comment by MJRLegends** [comment]
No problem
