### ISSUE TITLE
Recipe Conflict between pam's harvestcraft fresh water and water from LittleTiles

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-2-Feedback-#67]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
pam's harvestcraft fresh water and water from LittleTiles have the same Recipe

### Steps to Reproduce Issue
1. Place a bucket of water in any crafting grid 
2. none

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
*How do i to locate a crash log? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 
http://imgur.com/a/nMYD7

**Version of Mod Pack using:** [1.2.0]

**Where did this bug happen:** [Single Player]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Will be fixed in v1.2.1
