### ISSUE TITLE
Tier 4 key not give

### ISSUE THREAD

**Issue by bdspark** [MJRLegends/Space-Astronomy-2-Feedback-#69]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING): Yes

### Description of Issue
In single player if i kill magma boss in Mercury dimension i get tier 4 key. but in multiplayer in the frozen soul server i dont get any keys also I killed 2 of them still give no keys. without key we cant get schematic. server staff said post about it here so here is my post. Requesting you to check it out in multiplayer.
Thank you in advance.
### Steps to Reproduce Issue
1. you should know the step :D

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION 1.1.8

**Where did this bug happen:** Online Multiplayer server (Frozen Soul)

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please test on single player

**Comment by bdspark** [comment]
I have just tested it again. In single player it boss gives a tier 4 key. but in multiplayer does not. pic attached

![img1](https://user-images.githubusercontent.com/30198168/28802463-5b21c658-7678-11e7-899e-0853518edb98.jpg)
![img2](https://user-images.githubusercontent.com/30198168/28802462-5b219430-7678-11e7-8f31-4d9429faa644.jpg)

**Comment by MJRLegends** [comment]
This is a weird sponge thing but i can fix it i think

**Comment by MJRLegends** [comment]
Fixed in v1.2.1 once the servers update it will work for you :D

**Comment by bdspark** [comment]
Thank you. :D

**Comment by MJRLegends** [comment]
Also the Spider Queen boss from GC is also broken with sponge but i've reported it and should be fixed in the next pack update (v1.2.2)
