### ISSUE TITLE
Natura: bone meal bag and bone meal block, have the same recipe

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-2-Feedback-#7]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
when trying to make a bag of bonemeal from natura, it make a block of bone meal instad 

### Steps to Reproduce Issue
1. place 9 bonemena in a crafting grid

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** 1.0.7 beta

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Fixed in v1.0.8 Beta
