### ISSUE TITLE
hello, growth crystal tier 3

### ISSUE THREAD

**Issue by akimbaev** [MJRLegends/Space-Astronomy-2-Feedback-#71]
hello, growth crystal tier 3 (tiny progressions) it doesn't work and tier 2 too don't work . what we did 
wrong ?
![image](https://user-images.githubusercontent.com/30404027/28848028-359a5e70-7733-11e7-9b7e-95c5d9da59a6.png)

**Comment by MJRLegends** [comment]
Please fill out the issue template i will reopen when the edit has been made to include the filled out template
