### ISSUE TITLE
GUI over lap between the armor status indicator, and the radiation gui

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-2-Feedback-#73]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. Go to mercury
2. see screenshot 

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
*How do i to locate a crash log? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 
http://imgur.com/a/GY55e

**Version of Mod Pack using:** [1.2.1]

**Where did this bug happen:** [Single Player ]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Set your gui scale to normal
