### ISSUE TITLE
Crashing with rockhound chemistry?

### ISSUE THREAD

**Issue by koolkid293** [MJRLegends/Space-Astronomy-2-Feedback-#74]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
N/A
### Description of Issue
[Description of the issue]
Crashing when loading game
### Steps to Reproduce Issue
1. I installed a few mods via twitch
2. I opened the game and it said Rockhound chemistry

https://pastebin.com/11Ff3DhJ

1.2.1

Single Player

P.S. sorry if this is wrong I am new to github repository

**Comment by MJRLegends** [comment]
Your link does point to a crash log only a log with no errors

**Comment by MJRLegends** [comment]
How do i locate a crash log on Minecraft on Curse/Twitch? https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Comment by MJRLegends** [comment]
Please reinstall the pack
