### ISSUE TITLE
Need help assigning more RAM as im getting lag below 5Gb

### ISSUE THREAD

**Issue by debilman** [MJRLegends/Space-Astronomy-2-Feedback-#75]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):
Yes
### Description of Issue
FPS drops from 60 to 0 and back to 60

### Steps to Reproduce Issue
1. Install modpack with twitch desktop app
2. Create world (biomes'o'plenty) and wait ~10 sec

**Crash log/Log (if applicable): No crash
**Screenshots (if applicable):** 
![2017-08-04_14 34 49](https://user-images.githubusercontent.com/30725330/28968975-f07d439c-7922-11e7-8074-241541b3d2ef.png)
![2017-08-04_14 35 00](https://user-images.githubusercontent.com/30725330/28968988-fcbba068-7922-11e7-90a6-370292e9cd31.png)

**Version of Mod Pack using:** 1.2.2

**Where did this bug happen:** Single Player

### Additional Information
I have computer with 16GB RAM and in description of modpack you can read that 5GB RAM is recommended but when i wrote in JVM arguments RAM section Xmx 5120 it changes to 4096 after i close advanced settings window

**Comment by MJRLegends** [comment]
To change the ram you dont type the jmv args theres settings in the launchers to do that and thats why your getting the lag as you dont have 5GB+ ram assigned to minecraft, which launcher are you using

**Comment by MJRLegends** [comment]
Since the pack is only on curse im guessing that one, so go to the settings at the bottom left and then go to the minecraft section and scrolldown to the ram part and change to 5GB

**Comment by MJRLegends** [comment]
![dc7f8d56e48757536d049b50554355d8](https://user-images.githubusercontent.com/8526321/28969431-7ea00b3e-791c-11e7-92b6-70bb23c624fd.png)
![5b2d63ab708297660081fd218debdd8b](https://user-images.githubusercontent.com/8526321/28969433-7fa410d4-791c-11e7-9a75-a0c3524e199d.png)
![4c064c43f47ff150549b0effe357240c](https://user-images.githubusercontent.com/8526321/28969435-80f4594e-791c-11e7-8dd6-ea44396350ae.png)

**Comment by MJRLegends** [comment]
You can always change to more than 5GB but dont go above 8-9GB

**Comment by debilman** [comment]
thanks this worked <3

**Comment by MJRLegends** [comment]
No problem
