### ISSUE TITLE
Advanced Solar Panel Issue/ 

### ISSUE THREAD

**Issue by FizzleBopp** [MJRLegends/Space-Astronomy-2-Feedback-#76]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes, even other forums on this topic.
### Description of Issue
After I hit play during the forge loading screen it crashes when it tries to load something from advanced solar panels, not sure what to do about this issue
### Steps to Reproduce Issue
Press play
Crashes after loading what I assume to be a solar panel Model

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/qfD1hmP4

**Version of Mod Pack using:**
v1.2.2

**Where did this bug happen:** [Single Player or Server]
Loading screen after hitting play

**Comment by MJRLegends** [comment]
see and go the last comment https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/issues/55
