### ISSUE TITLE
Overpowered Neotech Coal generator? (200 RF/t / 320000 RF per coal)

### ISSUE THREAD

**Issue by Sceppie** [MJRLegends/Space-Astronomy-2-Feedback-#77]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
[Description of the issue]
No Issue, just an OP Generator. Don't look intentional to me, especially for the cheap recipe.

### Steps to Reproduce Issue
1. Grab a coal generator
2. Insert Coal
3. ????
4. Profit!

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
n/a

**Screenshots (if applicable):** 
Video available at: https://youtu.be/BZXeXWgHyZk

**Version of Mod Pack using:** [VERSION]
v.1.2.2

**Where did this bug happen:** [Single Player or Server]
Single Player

**Comment by MJRLegends** [comment]
Thanks for the bug report, any chance you could make that video unlisted please as promoting dupe/op issues is never a good idea.

**Comment by Sceppie** [comment]
Unlisted. Np

**Comment by Sceppie** [comment]
Sorry to say, but it's still generating the same amount at the same RF/t for one piece of coal. Dunno why, but looks like something to do with the 1 to 1 conversion of "Energy/Tick" to "RF/Tick". Advisable would be 20 RF/t and 32000 RF generated (divided by 10). It's around the same as the rest then.

Did try to fix it myself with the config file "Space Astronomy 2\config\energyconverters.cfg"
   Line:14   D:rfConversionFactor=1.0 and changed it to D:rfConversionFactor=10.0
Obviously it didn't work and didn't do anything 👎 .

**Comment by MJRLegends** [comment]
Yeah ive removed the recipe and hidden it from jei so please burn the block
