### ISSUE TITLE
Tiny Progressions: Overpowered "Birthday Pickaxe" and Cheap recipe

### ISSUE THREAD

**Issue by Sceppie** [MJRLegends/Space-Astronomy-2-Feedback-#78]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
Tiny Progressions "Birthday Pickaxe" is able to mine up to Ardite/Cobalt. Requires only one diamond, 10 iron bars, 8 obsidian and some sticks to make. It's an easy way to bypass the natural tiering Tinkers' Construct has to offer. Also has an insane speed and durability (2561).

### Steps to Reproduce Issue
1. Craft the Birthday Pickaxe/Cheat it in
2. Mine Cobalt/Ardite
3. Easy loot

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
n/a

**Screenshots (if applicable):** 
n/a

**Version of Mod Pack using:** 
v1.2.2

**Where did this bug happen:** [Single Player or Server]
Single Player

### Additional Information
Non game-breaking, overpowered none-the-less. Easy way to skip certain Tiering from Tinkers' Construct.

**Comment by MJRLegends** [comment]
Thank you i will fix this, it seems you are good at the whole finding overpowered features haha, only joking with you :P

**Comment by MJRLegends** [comment]
Its been disabled for v1.2.3 onwards

**Comment by Sceppie** [comment]
My pleasure ;)

**Comment by MJRLegends** [comment]
FYI the update (v1.2.30) is now released :D

**Comment by blobber19** [comment]
how, do you make the birthday pickaxe?

**Comment by MJRLegends** [comment]
You cant as said above its disabled!!
