### ISSUE TITLE
Server bug 

### ISSUE THREAD

**Issue by Toto6LP** [MJRLegends/Space-Astronomy-2-Feedback-#79]
Server Absturz. wenn man Galacticraft kabel mit einem Energi Würfel verbinden will. oder beim verbinden von Energi würfel mit Galacticraft Batteriebox. Solarmodul von Galacticraft will kein Strom ausgeben über Ender-energieleitung/ Universelles kabel von Mekanism.
Kann auch keine Capacitor Bank von Ender über Galacticraft kabe aufladen.

Server crash. If you want to connect Galacticraft cable to an Energi cube. Or when connecting power cubes with Galacticraft Energy Storage Module. Solar module from Galacticraft does not want to emit any current via Mekanism's Universal Power Cable / Universal Cable.
Can not recharge Capacitor bank from Ender via Galacticraft cable.

**Comment by MJRLegends** [comment]
Fixed update to v1.2.3
