### ISSUE TITLE
Recipe conflict, stable glass from SonarCore and test tube from rockhounding mod chemistry

### ISSUE THREAD

**Issue by Jin16** [MJRLegends/Space-Astronomy-2-Feedback-#8]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
when trying to make  test tube from  rockhounding mod chemistry it make stable glass from SonarCore

### Steps to Reproduce Issue
1. place 2 glass in a crafting grid 
2.  makes stable glass instad of the wanted test tube

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:** 1.0.7 beta

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Fixed in v1.0.8 Beta
