### ISSUE TITLE
Crashes on Finished Screen

### ISSUE THREAD

**Issue by Jackstew1115** [MJRLegends/Space-Astronomy-2-Feedback-#80]
### ---Issue Report---
Yes
### Description of Issue
When the modpack finishes loading it crashes with the message "It looks like you are using an unsupported modified version of the game."
### Steps to Reproduce Issue
1. Launch the modpack through the Twitch App/Program using the latest version
2. Wait for it to load

**Crash log/Log (if applicable):** https://pastebin.com/m4cK4X5D

**Screenshots (if applicable):** http://imgur.com/a/Occqe

**Version of Mod Pack using:** v. 1.2.3

**Where did this bug happen:** Default Singleplayer/Multiplayer Screen

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Your using to little ram haha
You need 5GB assigned 

How do i change my RAM Assignment/Usage for Minecraft on Curse/Twitch? http://imgur.com/a/s6OXF
