### ISSUE TITLE
Using Mechanical Crafter Crashes Server

### ISSUE THREAD

**Issue by BrutusTheGuppy** [MJRLegends/Space-Astronomy-2-Feedback-#81]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Placing and attempting to use the mechanical crafter from extra utilities 2 crashes the server. Server crashes on relog aswell.

### Steps to Reproduce Issue
1. place mechanical crafter
2. attempt to input the compressed cobblestone recipe 
3. Server crashed after left clicking in five of the required cobblestone

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/nkTaZiuq

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [1.2.2]

**Where did this bug happen:** [Server]

### Additional Information
You can msg me on curse: BrutusTheGuppy

**Comment by MJRLegends** [comment]
Seems, its crashing for MC 1.10.2 and 1.11.2 and 1.12 so i will just disable to completely in till its fixed, expect this to be removed in v1.2.4 since thats the next version
