### ISSUE TITLE
mekanism in space astronomy 2

### ISSUE THREAD

**Issue by Aghosted** [MJRLegends/Space-Astronomy-2-Feedback-#82]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
In the oficial server, when your try to pick up any mekanism multiblock machine (as the astrominer or windmils) with a pickaxe, sometimes doesnt dorp anything.

### Steps to Reproduce Issue
1. Just mine the block

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using:** 1.2.2

**Where did this bug happen:** Oficial server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
This is just due to server lag
