### ISSUE TITLE
curse install error

### ISSUE THREAD

**Issue by jarnoburger** [MJRLegends/Space-Astronomy-2-Feedback-#83]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes

### Description of Issue
[Description of the issue]
Error: Cannot find child addon: 51195

### Steps to Reproduce Issue
1. [First step]
I installed it
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by USMC2017** [comment]
I have got the same Issue in the latest version (Version 7.5.6432.4222) of the Twitch Launcher. (11. August 2017)
I have got the same Steps to Reproduce the Issue but my Error is: **Cannot find addon: 245549**

![unbenannt](https://user-images.githubusercontent.com/30958521/29242621-97395a36-7f90-11e7-9934-2e24362090de.JPG)

**Comment by USMC2017** [comment]
I found a new Issue when I retry to download the Modpack again. Now it say's: **Addon instance has no full path** But it  #Has...
![unbenannt2](https://user-images.githubusercontent.com/30958521/29242814-f81c4e3c-7f93-11e7-903c-8b8170b2da08.JPG)

**Comment by MJRLegends** [comment]
Please contact curse/twitch support support as its a launcher issue

**Comment by MJRLegends** [comment]
https://support.curse.com/hc/en-us/requests/new

**Comment by MJRLegends** [comment]
Btw all issues with the twitch app with installing mod pack have been fixed update your twitch app if you havent already before downloading a pack

**Comment by MJRLegends** [comment]
@jarnoburger @USMC2017 The Twitch App mod pack install/update issues have been solved, You just need to switch to be using the Beta Version and then install or update the mod pack/s. This is how you change your launcher to the Beta Version: http://imgur.com/a/un33N
