### ISSUE TITLE
Diamond Sword recipe conflict

### ISSUE THREAD

**Issue by Hazmatik** [MJRLegends/Space-Astronomy-2-Feedback-#84]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]
When trying to craft a diamond sword with the recipe in JEI it instead gives a Diamond Carving Tool from Literal Ascension
### Steps to Reproduce Issue
1. Try to craft diamond sword

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 
https://gyazo.com/2aec181a0f190e44a1fb84cb4c2c71c0
**Version of Mod Pack using:** [VERSION]
1.2.2
**Where did this bug happen:** [Single Player or Server]
On the FrozenSoul server
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Thanks for the bug report
