### ISSUE TITLE
Launch issue

### ISSUE THREAD

**Issue by Xhalty** [MJRLegends/Space-Astronomy-2-Feedback-#85]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Can't launch ]

### Steps to Reproduce Issue
1. [First step] Open SA2
2. [Second step] Nothing cause it wont load

**Crash log/Log (if applicable):** [https://pastebin.com/e5ryxK9n Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using:*1.2.3* [VERSION]

**Where did this bug happen:** [Launch time, on my pc?(lol)]

### Additional Information
[I changed my Ram cause i thought that was the isssue]

**Comment by MJRLegends** [comment]
Please contact curse/twitch support support as its a launcher issue

**Comment by MJRLegends** [comment]
https://support.curse.com/hc/en-us/requests/new

**Comment by MJRLegends** [comment]
Btw all issues with the twitch app with installing mod pack have been fixed update your twitch app if you havent already before downloading a pack
