### ISSUE TITLE
When downloading space astronomy 2 

### ISSUE THREAD

**Issue by Tripalink** [MJRLegends/Space-Astronomy-2-Feedback-#86]
when I download space astronomy 2 at around mod 109 it says  addon install Eroor Twitch encountered a problem during this operation Error: addon instance has no path pls help

**Comment by Tripalink** [comment]
I have tried installing it multiple times and shut down twitch

**Comment by MJRLegends** [comment]
Contact Curse support its nothing to do with me or my mod pack

**Comment by MJRLegends** [comment]
Btw all issues with the twitch app with installing mod pack have been fixed update your twitch app if you havent already before downloading a pack

**Comment by MJRLegends** [comment]
@Tripalink The Twitch App mod pack install/update issues have been solved, You just need to switch to be using the Beta Version and then install or update the mod pack/s. This is how you change your launcher to the Beta Version: http://imgur.com/a/un33N
