### ISSUE TITLE
I can't join a friend on a lan sever

### ISSUE THREAD

**Issue by Drdiddy25** [MJRLegends/Space-Astronomy-2-Feedback-#87]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please put some time in to filling out the issue report and i will reopen

**Comment by Drdiddy25** [comment]
awesome modpack btw

**Comment by MJRLegends** [comment]
Using a ip isnt a lan connection

**Comment by Drdiddy25** [comment]
i mean his Ipv.4

**Comment by MJRLegends** [comment]
Juat type localhost

**Comment by MJRLegends** [comment]
He has to be on the same internet as you  and this isnt a mod pack bug

**Comment by Drdiddy25** [comment]
does local host work if it's a networking connection like hamachi?

**Comment by MJRLegends** [comment]
No idea but lan should work,  unable to provide hamachi supoort since i dont use it but im sure google ans youtube will have lots on it

**Comment by Drdiddy25** [comment]
ok thanks anyway sorry for wasting your time

**Comment by MJRLegends** [comment]
No problem
