### ISSUE TITLE
Bug When Installing Modpack

### ISSUE THREAD

**Issue by Pokeben10** [MJRLegends/Space-Astronomy-2-Feedback-#88]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
The mods load in the modpack, but when it gets to the end it stops loading and gives me the error "Addon Instal Error.  Twitch encountered a problem during this operation.  Error:  Addon instance has no full path!"

### Steps to Reproduce Issue
1. [First step] Find Space Astronomy on the Twitch App.
2. [Second step] Install the modpack.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]

**Where did this bug happen:** [Single Player or Server] Neither, it happened when I tried to install the modpack.  I never had it downloaded previously either.  

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by Pokeben10** [comment]
Does anyone know the fix? I've tried around 10 times and it hasn't worked.  This got closed and I don't see a solution? Just wanted to know if anyone could help me out.

**Comment by MJRLegends** [comment]
Launcher issue i cant do nothing for it sorry its not pack related

**Comment by Pokeben10** [comment]
:(

**Comment by MJRLegends** [comment]
@Pokeben10 The Twitch App mod pack install/update issues have been solved, You just need to switch to be using the Beta Version and then install or update the mod pack/s. This is how you change your launcher to the Beta Version: http://imgur.com/a/un33N
