### ISSUE TITLE
Issue with advanced Galacticraft solar panel

### ISSUE THREAD

**Issue by gimba92** [MJRLegends/Space-Astronomy-2-Feedback-#91]
### Description of Issue
There is a problem with the advanced Galacticraft solar panels.
The panel will not transfer the power generated to a Ender IO capacitator bank, and that is regardless of which type of cables are being used (tried with both the energy conduit from Ender IO and the Galacticraft aluminium wire). This has not been a problem in your 1.7 pack, and when I looked up the Galacticraft 4 mod (which I assume is being used since MC patch 1.10) it said there should be full RF compatibility. Both the conduit and the wire connects to both machines but doesn't "speak same language" so to say. 

I wouldn't know if the solar panel will transfer energy to other types power banks. That I haven't tested.

I know for a fact that the galacticraft machinery (atleast the circuit fabricator) accepts RF.
I have a circuit fabricator set up with conduits and a capacitator bank, with no issues - So in my logic it must be the solar panel itself there is an issue with.

**Comment by MJRLegends** [comment]
Try mekanism cables or GC wires

**Comment by MJRLegends** [comment]
I can confirm ender io cables or GC cables work but mekanism cables ones do

**Comment by MJRLegends** [comment]
Reported the issue to the Galacticraft Dev, see https://github.com/micdoodle8/Galacticraft/issues/2958

**Comment by MJRLegends** [comment]
@gimba92 Just a quick update, this is being worked on, currently the GC wires work with the Ender IO stuff as of the next update for the pack, but might be fully fixed for the next update will post here any news on it

**Comment by MJRLegends** [comment]
Mekanism and Galacticraft cables work for this see information below but ender io cables between GC and ender io wont ones wont

**These setups works ok**
![2017-10-03_19 19 47](https://user-images.githubusercontent.com/8526321/31141651-e35bb7d0-a86f-11e7-8aec-46994cd7638b.png)

![2017-10-03_19 21 37](https://user-images.githubusercontent.com/8526321/31141724-1af42434-a870-11e7-9afe-b33043e48dcd.png)

**These dont:**
![2017-10-03_19 23 19](https://user-images.githubusercontent.com/8526321/31141829-58d0b8da-a870-11e7-9529-625b67e46b81.png)
![2017-10-03_19 22 19](https://user-images.githubusercontent.com/8526321/31141758-327ad6c0-a870-11e7-843f-af02613d37f7.png)
![2017-10-03_19 22 20](https://user-images.githubusercontent.com/8526321/31141762-33ffb6e6-a870-11e7-9a4f-93289110e1ec.png)
