### ISSUE TITLE
game crashes when putting any upgrade into transfer node

### ISSUE THREAD

**Issue by Thelm76** [MJRLegends/Space-Astronomy-2-Feedback-#94]
I think everything is in this post :
https://github.com/rwtema/extrautilities/issues/1656

[crash-2017-08-23_00.09.39-client.txt](https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/files/1249600/crash-2017-08-23_00.09.39-client.txt)

I have a setup with a server : the client crashes, nothing on the server console

Pack version : 1.2.5

**Comment by MJRLegends** [comment]
Please fill our the template with your crash log please

**Comment by MJRLegends** [comment]
Fixed in v1.2.7 of the mod pack
