### ISSUE TITLE
Mekanism Tools Crash when using a Anvil to apply Silk Touch

### ISSUE THREAD

**Issue by Ravalli03** [MJRLegends/Space-Astronomy-2-Feedback-#95]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
 Yes
### Description of Issue
[Description of the issue]

While trying to enchant an Osmium Pickaxe with silk touch book, game crashes.

### Steps to Reproduce Issue
1. [First step]
Make Osmium Pickaxe

2. [Second step]

Place in an anvil with enchanted book

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

https://pastebin.com/f4TVY3py

**Screenshots (if applicable):** 

**Version of Mod Pack using:** [VERSION]

v1.2.5

**Where did this bug happen:** [Single Player or Server]
Single 

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
I've reported the issue here: https://github.com/aidancbrady/Mekanism/issues/4652

**Comment by Ravalli03** [comment]
Ok, thanks

**Comment by MJRLegends** [comment]
@Ravalli03 This should be fixed very soon hopefully, the developers of mekanism are going to take a look

**Comment by MJRLegends** [comment]
I've added this to the known issues over at #99

**Comment by Ravalli03** [comment]
Thank you for the update

**Comment by STOKE-STER** [comment]
has this been fixed on 1.10.2? Or was the fix added to a later MC version of the mod?
