### ISSUE TITLE
Crash when open GAN Controller's GUI

### ISSUE THREAD

**Issue by spaut33** [MJRLegends/Space-Astronomy-2-Feedback-#96]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**
Yes

### Description of Issue
[Description of the issue]
NPE when opening GUI of GAN Controller from Rockhounding Chemistry mod.

### Steps to Reproduce Issue
1. Place Gan controller
2. Open its GUI

**Crash log/Log (if applicable):** 
https://pastebin.com/4TbyP5vK

**Version of Mod Pack using:** 
1.2.5

**Where did this bug happen:** 
both SSP and server

**Comment by MJRLegends** [comment]
I've reported the issue here: https://github.com/GlobbyPotato/Rockhounding_Chemistry/issues/13

**Comment by spaut33** [comment]
@MJRLegends Thanks! 👍

**Comment by MJRLegends** [comment]
@spaut33 no problem the update is coming out very soon :)
