### ISSUE TITLE
GUI loading every item/block

### ISSUE THREAD

**Issue by DedBoii** [MJRLegends/Space-Astronomy-2-Feedback-#98]
when I'm in creative I open the search menu in the creative menu and search some thing my game lags then I see the results before every item is loaded in like I didn't search anything.

**Comment by MJRLegends** [comment]
Thanks for the bug report, For future issues please make its a fully bug before posting and make sure to fill out the template as deleting it will just make it harder and take more time to get things fixed

**Comment by DedBoii** [comment]
i'm redoing it because I did mess it up

**Comment by MJRLegends** [comment]
Ok its not a issue, You just need 5GB of RAM if not it will lag and you need a good computer. Its not a bug so please try the things i posted here
